### ISSUE TITLE
[Error] mobilebert/run_classifier.py : 'NoneType' object has no attribute 'op'

### ISSUE THREAD

**Issue by yuchiwang** [google-research/google-research#1002]
SST-2 and CoLA both.  PLZ help. Thanks

**[LOG]**
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
INFO:tensorflow:**** Trainable Variables ****
I0212 13:33:31.735677 139904805205824 run_classifier.py:770] **** Trainable Variables ****
ERROR:tensorflow:Error recorded from training_loop: 'NoneType' object has no attribute 'op'
E0212 13:33:31.758976 139904805205824 error_handling.py:75] Error recorded from training_loop: 'NoneType' object has no attribute 'op'
INFO:tensorflow:training_loop marked as finished
I0212 13:33:31.759163 139904805205824 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0212 13:33:31.759236 139904805205824 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "run_classifier.py", line 1219, in <module>
    tf.app.run()
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_classifier.py", line 1082, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1994, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_classifier.py", line 782, in model_fn
    total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu)
  File "/data/wangyuchi/google_research/mobilebert/optimization.py", line 96, in create_optimizer
    grads = tf.gradients(loss, tvars)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_core/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_core/python/ops/gradients_util.py", line 550, in _GradientsHelper
    gradient_uid)
  File "/root/anaconda3/envs/mobilebert/lib/python3.6/site-packages/tensorflow_core/python/ops/gradients_util.py", line 166, in _DefaultGradYs
    with _maybe_colocate_with(y.op, gradient_uid, colocate_gradients_with_ops):
AttributeError: 'NoneType' object has no attribute 'op'

**[CMD]**
python run_classifier.py \
--bert_config_file=config/uncased_L-24_H-128_B-512_A-4_F-4_OPT_QAT.json \
--data_dir=data/CoLA \
--task_name=cola \
--do_train \
--do_lower_case \
--init_checkpoint=mobilebert/mobilebert_variables.ckpt \
--learning_rate=5e-5 \
--max_seq_length=64 \
--num_train_epochs=5 \
--output_dir=cola_output \
--train_batch_size=96 \
--vocab_file=mobilebert/vocab.txt \
--warmup_proportion=0.1 \
--export_dir=cola_export \
--verbose_logging=True \
--use_quantized_training=true

**Comment by yuchiwang** [comment]
**[ENV]**
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
tensorflow = 1.15.2, CPU

**Comment by yuchiwang** [comment]
Is the init_checkpoint file wrong? Where can I get the init_checkpoint of classify?

**Comment by yuchiwang** [comment]
sloved
