### ISSUE TITLE
Dream Fields Docker Tensorflow Errors

### ISSUE THREAD

**Issue by hanhung** [google-research/google-research#1005]
Hello, I am trying to run the run_docker.sh file from Dream Fields according to the README. However, I encounter a tensorflow error while running the container.

`Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from dreamfields import helpers
  File "/dreamfields/dreamfields/helpers.py", line 29, in <module>
    from scenic.projects.baselines.clip import model as clip
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/baselines/clip/model.py", line 12, in <module>
    from scenic.projects.baselines.clip import download
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/baselines/clip/download.py", line 9, in <module>
    from tensorflow.io import gfile
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 479, in <module>
    keras._load()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.8/dist-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/usr/local/lib/python3.8/dist-packages/keras/metrics/__init__.py", line 23, in <module>
    from keras.metrics.base_metric import Metric
  File "/usr/local/lib/python3.8/dist-packages/keras/metrics/base_metric.py", line 25, in <module>
    from keras.engine import base_layer
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/usr/local/lib/python3.8/dist-packages/keras/mixed_precision/loss_scale_optimizer.py", line 20, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.`

**Comment by fanhong19** [comment]
I have the same problem. How can I solve it?thank you!!

**Comment by hanhung** [comment]
So originally I solved the problem described here: https://github.com/google-research/scenic/issues/213. However, I have also tried with newer versions of jax and scenic (0.5.3) and this error no longer pops up.

**Comment by fanhong19** [comment]
I'd like to know what you've done，
 What is the version number of Pillow, Keras and TensFlow?  and jax

thank you so much
