### ISSUE TITLE
"expected str instance, bytes found" to "list index out of range"

### ISSUE THREAD

**Issue by zsweet** [google-research/google-research#105]
when i run run_squad_sp.py , error occur :
```
Traceback (most recent call last):
  File "run_squad_sp.py", line 1350, in <module>
    tf.app.run()
  File "/usr/local/app/.conda/envs/convlab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad_sp.py", line 1257, in main
    output_fn=train_writer.process_feature)
  File "run_squad_sp.py", line 396, in convert_examples_to_features
    tok_cat_text = "".join(para_tokens).replace(
TypeError: sequence item 89: expected str instance, bytes found
```
and i find that the para_tokens as below:
```
['▁greece', '▁attract', 's', '▁more', '▁than', '▁16', '▁million', '▁tourists', '▁each', '▁year', ',', '▁thus', '▁contributing', '▁18', '.', '2%', '▁to', '▁the', '▁nation', "'", 's', '▁gdp', '▁in', '▁2008', '▁according', '▁to', '▁an', '▁', 'oe', 'cd', '▁report', '.', '▁the', '▁same', '▁survey', '▁showed', '▁that', '▁the', '▁average', '▁tourist', '▁expenditure', '▁while', '▁in', '▁greece', '▁was', '▁$1', ',', '07', '3', ',', '▁ranking', '▁greece', '▁10', 'th', '▁in', '▁the', '▁world', '.', '▁the', '▁number', '▁of', '▁jobs', '▁directly', '▁or', '▁indirectly', '▁related', '▁to', '▁the', '▁tourism', '▁sector', '▁were', '▁8', '40,000', '▁in', '▁2008', '▁and', '▁represented', '▁', '19%', '▁of', '▁the', '▁country', "'", 's', '▁total', '▁labor', '▁force', '.', '▁in', "b'\\xe2\\x96\\x812009'", ',', '▁greece', '▁welcomed', '▁over', '▁19', '.', '3', '▁million', '▁tourists', ',', '▁a', '▁major', '▁increase', '▁from', '▁the', '▁17', '.', '7', '▁million', '▁tourists', '▁the', '▁country', '▁welcomed', '▁in', '▁2008', '.']
```
so i modify my code from ` tok_cat_text = "".join(para_tokens).replace(tokenization.SPIECE_UNDERLINE.decode("utf-8"), " ")` to`tok_cat_text = "".join([w.decode() if type(w)==bytes else w for w in para_tokens]).replace(  tokenization.SPIECE_UNDERLINE.decode("utf-8"), " ")` and another error occurs as below:
```
Traceback (most recent call last):
  File "run_squad_sp.py", line 1350, in <module>
    tf.app.run()
  File "/usr/local/app/.conda/envs/convlab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad_sp.py", line 1257, in main
    output_fn=train_writer.process_feature)
  File "run_squad_sp.py", line 471, in convert_examples_to_features
    n, is_start=False)
  File "run_squad_sp.py", line 316, in _convert_index
    if index[pos] is not None:
IndexError: list index out of range
```
what's wrong with it？ thx

**Comment by kamalkraj** [comment]
https://github.com/google-research/google-research/blob/c5a0b1ecfd1e55df5e3edd00bea902a9d9c5b0f5/albert/run_squad_sp.py#L377

REPLACE 

for i, token in enumerate(para_tokens):
      new_token = token.decode("utf-8")
      chartok_to_tok_index.extend([i] * len(new_token))
      tok_start_to_chartok_index.append(char_cnt)
      char_cnt += len(new_token)
      tok_end_to_chartok_index.append(char_cnt - 1)

**Comment by zsweet** [comment]
cool ! thank you very much ! I just found another method that convert all
token to utf-8 after tokenizer document .
thank you!

**Comment by YanDavKMS** [comment]
> cool ! thank you very much ! I just found another method that convert all token to utf-8 after tokenizer document . thank you!

Can you please share your solution?
Thanks in advance.
