### ISSUE TITLE
dreamfields:     raise ValueError("a must be an integer or 1-dimensional")

### ISSUE THREAD

**Issue by derrick-xwp** [google-research/google-research#1060]
File "/home/google-research/dreamfields/dream/lib/python3.6/site-packages/jax/_src/random.py", line 599, in choice
    raise ValueError("a must be an integer or 1-dimensional")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: a must be an integer or 1-dimensional

**Comment by ajayjain** [comment]
Hi @derrick-xwp, I don't see this error with our Colab notebook. Could you provide a full stack trace? Are you running the code on your own server?

**Comment by zloc-alz** [comment]
I have the same issue when running on our own server. 
Full stacktrace looks like this:
```
Traceback (most recent call last):
  File "run.py", line 136, in <module>
    run(train=lib.run_train, eval=lib.run_eval)
  File "run.py", line 132, in run
    app.run(functools.partial(main, executable_dict))
  File "/home/jovyan/.conda_envs/dreamfieldsgg/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/jovyan/.conda_envs/dreamfieldsgg/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run.py", line 124, in main
    **extra_args)
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/lib.py", line 809, in run_train
    yield_results=False):
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/lib.py", line 426, in run_train
    state, rays_in, keys_pstep, lrs, scs, sns, mrs, betas, accts, acclams)
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/lib.py", line 220, in train_step
    state, aux = body_fn(state, np.squeeze(multistep_constants))
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/lib.py", line 209, in body_fn
    (_, aux), grad = grad_fn(state.target, grad_fn_key, *step_constants)
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/lib.py", line 151, in loss_fn
    augs = augment.augment_rendering(config, rgb_est, acc_est, aug_key)
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/augment.py", line 144, in augment_rendering
    return jax.vmap(random_aug)(random.split(key, config.n_local_aug))
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/augment.py", line 139, in random_aug
    bg = random_bg(bg_key)
  File "/home/jovyan/alz/dreamfields_gg/gh/dreamfields/dreamfields/augment.py", line 96, in random_bg
    bg = random.choice(bg_sel_key, bgs, p=np.array(probs))
  File "/home/jovyan/.conda_envs/dreamfieldsgg/lib/python3.7/site-packages/jax/_src/random.py", line 459, in choice
    raise ValueError("a must be an integer or 1-dimensional")
ValueError: a must be an integer or 1-dimensional
```
