### ISSUE TITLE
Dreamfields error in jax.random

### ISSUE THREAD

**Issue by INF800** [google-research/google-research#1071]
Hey @ajayjain. Thankyou for the amazing work with dreamfields.

Can you please have a look at the error logs for `bash run_docker.sh all "elephant origami"`? 

```
bash run_docker.sh all "elephant origami"
GPUS all
QUERY elephant origami

================
== TensorFlow ==
================

NVIDIA Release 21.12-tf2 (build 29871111)
TensorFlow Version 2.6.2

Container image Copyright (c) 2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Copyright 2017-2021 The TensorFlow Authors.  All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 11.5 driver version 495.29.05 with kernel driver version 470.103.01.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py:400: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
  warnings.warn(
I0420 18:58:23.989800 140279365150528 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0420 18:58:24.167545 140279365150528 xla_bridge.py:231] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py:413: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  warnings.warn(
I0420 18:58:24.167988 140279365150528 run.py:65] JAX host: 0 / 1
I0420 18:58:24.168152 140279365150528 run.py:66] JAX devices: [GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0)]
I0420 18:58:24.168639 140279365150528 local.py:45] Setting task status: host_id: 0, host_count: 1
I0420 18:58:24.169077 140279365150528 local.py:50] Created artifact experiment_dir of type ArtifactType.DIRECTORY and value results.
I0420 18:58:24.169288 140279365150528 local.py:50] Created artifact work_unit_dir of type ArtifactType.DIRECTORY and value results/'elephant origami' 20220420-185824.
I0420 18:58:24.169421 140279365150528 run.py:93] experiment_dir=results work_unit_dir=results/'elephant origami' 20220420-185824
I0420 18:58:24.981649 140279365150528 run.py:108] config={
    "acc_lam": 0.5,
    "acc_lam_after": 0,
    "acc_target0": 0.5,
    "acc_target1": 0.1,
    "acc_target_i_split": 500,
    "adam_eps": 1e-05,
    "augment_backgrounds": true,
    "beta_after": 20000,
    "bg_blur_std_range": [
        0.0,
        10.0
    ],
    "checker_bg_nsq": 8,
    "checker_bg_prob": 0.333,
    "checkpoint_every": 1000,
    "clip_width": 224,
    "crop_width": 80,
    "defragment_every": 200,
    "ema_scene_origin": true,
    "far": 5.732050807568877,
    "features_early": [
        128
    ],
    "features_late": [
        128,
        4
    ],
    "features_residual": [
        [
            256,
            128
        ],
        [
            256,
            128
        ],
        [
            256,
            128
        ],
        [
            256,
            128
        ]
    ],
    "fft_bg_prob": 0.334,
    "flush_every": 500,
    "focal_mult_range": [
        1.2,
        1.2
    ],
    "fourfeat": true,
    "hq_video_every": 10000,
    "iters": 10000,
    "jitter": true,
    "keep_every_n_steps": 10000,
    "log_scalars_every": 50,
    "loss_model": "clip_vit_b16",
    "lr0": 1e-05,
    "lr1": 0.0001,
    "lr2": 0.0001,
    "lr_cosine_decay": false,
    "lr_i_split": 1500,
    "min_aug_acc": 0.0,
    "mipnerf": {
        "decay_iters": 1000,
        "decay_start": 1.0,
        "sigma_activation": "softplus",
        "use_cov": true
    },
    "mlp_activation": "swish",
    "mr0": 1.0,
    "mr1": 1.0,
    "mr_i_split": 10000,
    "mr_norm": "inf",
    "n_local_aug": 8,
    "near": 2.267949192431123,
    "noise_bg_prob": 0.333,
    "num_samples": 192,
    "parameterization": "mipnerf",
    "phi_range": [
        -30,
        -30
    ],
    "posenc_deg": 8,
    "posenc_dirs_deg": 4,
    "queries_r": [
        "a blue bicycle parked by a metal gate.",
        "an orange bike leaning on a pole in the snow.",
        "there are some colored lights hanging from street lamps.",
        "the apple symbol is show on the premacy car.",
        "an orange motorcycle is shown at close range.",
        "a blue motorbike has a \"minnesota\" license plate.",
        "the side of an american aircraft showing the door.",
        "a floor drain is set in concrete with an advisory not to step on it.",
        "a bus covered with assorted colorful graffiti on the side of it.",
        "a bus covered in graffiti is stationary on the pavement.",
        "a bike image on some double doors with windows.",
        "a red train cart is shown at close range.",
        "a truck is drying several items of clothing in the sun.",
        "the rotted out bed of a truck left in the woods.",
        "a boat on the water tied down to a stake.",
        "an inflatable raft that has its top open.",
        "a red light in front of a tall building.",
        "a street sign says walk and don't walk.",
        "a red and blue fire hydrant with flowers around it.",
        "a red fire hydrant with an open sign on it.",
        "a street sign with stickers on the back of it.",
        "a red stop sign with lots of writing all over it.",
        "a parking meter with a time expired label on it.",
        "a blue faced machine for printing parking passes.",
        "a bag full of trash sitting on a old park bench.",
        "a park bench sits under a tree with the sun shining.",
        "a picture of a flamingo scratching its neck.",
        "a large blue bird standing next to a painting of flowers.",
        "a cat is staring ahead as the back another cat's head is seen in front of him.",
        "an orange cat looking upside down through glasses.",
        "a bulldog is wearing a black pirate hat.",
        "a dog standing at a gate wanting to get out of the fence.",
        "a brown and white horse wearning a harness eating some hay.",
        "a brown and white horse is wearing a blue muzzle.",
        "a sheep standing in the grass with something on its ears.",
        "a sheep looking through the slats of a wired fence.",
        "a black cow looks directly at the camera.",
        "a horned cow  standing in a green grass field.",
        "an elephant with trimmed tusks relaxing with a covering of hay on its back.",
        "an elephant placing some leaves in its mouth with its trunk.",
        "the polar bear swimming briskly through the ocean current.",
        "a large black bear is facing straight ahead.",
        "the painting is of a zebra in a cage.",
        "a zebra is eating grass on the ground.",
        "a giraffe leaning it's long neck over the fence to eat leaves off a bush.",
        "a very big giraffe that is siting on the ground.",
        "a stuffed animal in a bag in a room.",
        "a large umbrella open wide on a pole.",
        "the plants can be seen through the orange mesh.",
        "a fireplace mantle that has been faced in a light stone.",
        "a tan table top hosts a pen and a necktie.",
        "a gold tie is tied under a brown dress shirt with stripes.",
        "a piece of gray luggage with travel stickers.",
        "a cat relaxes in a suitcase next to a pile of clothes.",
        "a yellow frisbee next to a box with nike cleats.",
        "blue frisbee and envelope it was shipped in.",
        "a large pair of skis rests against a wall.",
        "appears to be some old skis propped up against a stone memorial.",
        "a snowboard standing upright in a snow bank.",
        "a snowboard and gloves laying in the snow.",
        "a blue and white traffic sign on a grey brick wall.",
        "a cat shaped kite sits in the grass.",
        "there is a very colorful kite that is in the air.",
        "a bat and shin guard in the closet.",
        "a baseball bat with a batting helmet upsidedown.",
        "a stuffed animal that is frowning is on a skateboard.",
        "an very well used upside down skateboard on grass.",
        "white surfboard leaning against a brown tiki wall.",
        "a small surfboard sign that says trader vic's, los angeles.",
        "a couple of snowmen have been built in suburban backyards after a recently fallen snow.",
        "very large tennis racket with hello kitty on it.",
        "a blender and jar of red liquid on a table.",
        "a plastic jar of honey glowing in the middle of the dark.",
        "a table with a blender and a glass on it.",
        "a glass of wine sitting on the top of a swimming pool side.",
        "a glass measuring cup with yellow liquid in it.",
        "a blender full of liquid is spilling everywhere.",
        "a dish of food topped with sour cream and a fork.",
        "a pizza and fork on a tray on the table.",
        "a knife sitting on top of a wooden table next to a knife.",
        "beet tops and a chef's knife on a cutting board.",
        "a pile of cabbage, noodles, and meat next to chopsticks.",
        "blender half full of a slurry, next to other electrical appliances.",
        "a bowl of a meal with an egg, \"sunny side up\", laid on top of everything.",
        "a pork dish with onions and peppers on a white plate.",
        "someone wrote a message on a bunch of bananas.",
        "fruit growing on the side of a tree in a jungle.",
        "a bunch of apples stacked on a plate.",
        "apples on tree ready to pick in garden area.",
        "a sandwich with meat, vegetables, peppers, and lettuce.",
        "a pile of crab is seasoned and well cooked.",
        "cut up blood red oranges lay on a blue surface.",
        "a plate of oranges sliced on top of a table.",
        "a pile of broccoli laying on a plastic cutting board.",
        "a plate of food has noodles and broccoli.",
        "a tray that has meat and carrots on a table.",
        "a stuffed grey rabbit holding a pretend carrot.",
        "the two hotdogs have brown mustard on them.",
        "a plate with a couple of hot dogs on it.",
        "view of what could possibly be a pizza with colorful vegetables as toppings.",
        "a pizza that is covered in a lot of toppings.",
        "a picture of a glazed donut with meat in the middle.",
        "a donut is covered with glaze and sprinkles.",
        "fresh red strawberries on a whipped dessert.",
        "colorful icing on a pastry in the shapes of flowers.",
        "the cat is sleeping comfortably on the chair.",
        "a white cat curled up on a wooden chair.",
        "a dog is sleeping on a pile of pillows.",
        "a girl laying on the couch while on an laptop.",
        "a bouguet of wilted red roses on a table.",
        "a small green vase displays some small yellow blooms.",
        "a tear in a black, blue, white and yellow piece of material.",
        "a bed with white comforter and two black stiletto heels.",
        "a plate of food consisting of rice, meat and vegetables.",
        "a plate of food is centered around a portion of rice.",
        "a porcelian scuplture sitting on a table next to a cup.",
        "a bucket collects drips of water, inside a metal basin.",
        "the back of a flat screened tv connected to a ipad.",
        "a cluster of pine trees are in a barren area.",
        "a bobble head is placed on a laptop keyboard.",
        "a computer mouse sitting on a keyboard on a desk.",
        "a silver and black wired computer mouse on a wooden surface.",
        "a slug crawling on the ground around flower petals.",
        "two remotes sitting on a table together.",
        "the wii controller remote is turned on and has one light showing.",
        "a black computer keyboard with a bunch of keys on it.",
        "a keyboard that is missing some keys in the bottom row.",
        "a cellphone standing upright with its camera side facing forward.",
        "there is a cell phone on a table.",
        "a microwave with fake eyes and a beard on it.",
        "food steaming machine on the shelf of a store.",
        "a yellow shallow baking dish in an open oven.",
        "some food cooking on trays in an oven.",
        "the toaster oven is turned on, on the counter in the kitchen.",
        "a picture of a toaster plastered on a do not enter sign.",
        "a old kitchen with no appliances inside of it.",
        "two pictures of a hole in a counter with a lid.",
        "a fridge is slightly open in a room.",
        "the poster board is a special place for remembrances.",
        "a stuffed animal sitting in the grass, with a book in front of it.",
        "a run down windows with a broken fence outside.",
        "an old and rusted clock is mounted on a brick wall.",
        "a big metal clock sitting on the wall by itself.",
        "bouquet of flowers sitting in a clear glass vase.",
        "a blue jug in a garden filled with mud.",
        "a sign that is advertising a barber shop.",
        "a pair of scallop scrapbooking scissors on top of an envelope.",
        "a stuffed bear is wearing a shirt with personalized writing.",
        "a pair of yellow and pink teddy bears leaning against a wall.",
        "a large statue of a female cow with a blonde wig.",
        "rubber shoes lying on a carpet with floral prints.",
        "a frog with teeth is on a purple toothbrush.",
        "a worn toothbrush sits on a windowsill near the screen."
    ],
    "query": "elephant origami",
    "query_template": "{query}",
    "rad_range": [
        4.0,
        4.0
    ],
    "render_every": 1000,
    "render_hq_video": true,
    "render_lq_video": true,
    "render_width": 88,
    "retrieve_models": [
        "clip_vit_b32"
    ],
    "retrieve_widths": [
        224
    ],
    "seed": 0,
    "sn0": 0.0,
    "sn1": 0.0,
    "sn_i_split": 10000,
    "substeps": 1,
    "test": {
        "jitter": false,
        "num_samples": 256,
        "white_bkgd": true
    },
    "test_hq": {
        "intersect_box": false,
        "jitter": false,
        "num_samples": 512,
        "white_bkgd": true
    },
    "th_range": [
        0,
        360
    ],
    "transparency_loss": "neg_lam_transmittance_clipped",
    "video_every": 5000,
    "viewdirs": false,
    "white_bkgd": false,
    "zero_origin_lam": 0.0
}
I0420 18:58:24.981802 140279365150528 run.py:112] Running executable: train
I0420 18:58:24.981907 140279365150528 lib.py:61] Local devices: [GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0)]
I0420 18:58:24.981965 140279365150528 lib.py:62] All devices: [GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0)]
100%|█████████████████████████████████████| 1.29M/1.29M [00:00<00:00, 20.6MiB/s]
I0420 18:58:26.345784 140279365150528 tokenizer.py:47] Downloaded vocabulary from https://github.com/openai/CLIP/blob/main/clip/bpe_simple_vocab_16e6.txt.gz?raw=true to /root/.cache/scenic/clip
100%|█████████████████████████████████████| 1.29M/1.29M [00:00<00:00, 20.0MiB/s]
I0420 18:58:31.982127 140279365150528 tokenizer.py:47] Downloaded vocabulary from https://github.com/openai/CLIP/blob/main/clip/bpe_simple_vocab_16e6.txt.gz?raw=true to /root/.cache/scenic/clip
/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py:3660: UserWarning: Explicitly requested dtype <class 'jax._src.numpy.lax_numpy.float64'> requested in zeros is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax._check_user_dtype_supported(dtype, "zeros")
I0420 18:58:36.377778 140279365150528 lib.py:241] n_device 2
I0420 18:58:42.307506 140279365150528 lib.py:262] did not find checkpoint in results/'elephant origami' 20220420-185824
I0420 18:58:42.307700 140279365150528 helpers.py:67] starting defragment...
I0420 18:58:42.703572 140279365150528 helpers.py:70] finished defragment
I0420 18:58:42.724392 140279365150528 helpers.py:67] starting defragment...
I0420 18:58:43.137570 140279365150528 helpers.py:70] finished defragment
I0420 18:58:43.140103 140279365150528 lib.py:326] Experiment dir results
I0420 18:58:43.140221 140279365150528 lib.py:327] Work unit dir results/'elephant origami' 20220420-185824
training:   0%|          | 0/10001 [00:02<?, ?it/s]
====================================================
bg_sel_key
Traced<ShapedArray(uint32[2])>with<BatchTrace(level=3/1)> with
  val = Traced<ShapedArray(uint32[8,2])>with<DynamicJaxprTrace(level=0/1)>
  batch_dim = 0
====================================================
bgs
Traced<ShapedArray(float32[3,224,224,3])>with<BatchTrace(level=3/1)> with
  val = Traced<ShapedArray(float32[8,3,224,224,3])>with<DynamicJaxprTrace(level=0/1)>
  batch_dim = 0
====================================================
probs
[0.333, 0.333, 0.334]
====================================================
Traceback (most recent call last):
  File "run.py", line 136, in <module>
    run(train=lib.run_train, eval=lib.run_eval)
  File "run.py", line 132, in run
    app.run(functools.partial(main, executable_dict))
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run.py", line 119, in main
    executable_dict[FLAGS.executable_name](
  File "/dreamfields/dreamfields/lib.py", line 805, in run_train
    for _ in DreamField(config).run_train(
  File "/dreamfields/dreamfields/lib.py", line 425, in run_train
    new_state, augs, mean_losses, new_scene_origin = train_pstep(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1899, in cache_miss
    out_tree, out_flat = f_pmapped_(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1778, in f_pmapped
    out = pxla.xla_pmap(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1705, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1630, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1708, in process
    return trace.process_map(self, fun, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 631, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py", line 710, in xla_pmap_impl
    compiled_fun, fingerprint = parallel_callable(fun, backend, axis_name, axis_size,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 263, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py", line 798, in parallel_callable
    jaxpr, out_sharded_avals, consts = pe.trace_to_jaxpr_final(
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1529, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1507, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/dreamfields/dreamfields/lib.py", line 220, in train_step
    state, aux = body_fn(state, np.squeeze(multistep_constants))
  File "/dreamfields/dreamfields/lib.py", line 209, in body_fn
    (_, aux), grad = grad_fn(state.target, grad_fn_key, *step_constants)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 993, in value_and_grad_f
    ans, vjp_py, aux = _vjp(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2270, in _vjp
    out_primal, out_vjp, aux = ad.vjp(
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 118, in vjp
    out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 103, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 512, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/dreamfields/dreamfields/lib.py", line 151, in loss_fn
    augs = augment.augment_rendering(config, rgb_est, acc_est, aug_key)
  File "/dreamfields/dreamfields/augment.py", line 157, in augment_rendering
    return jax.vmap(random_aug)(random.split(key, config.n_local_aug))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1405, in batched_fun
    out_flat = batching.batch(
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/dreamfields/dreamfields/augment.py", line 152, in random_aug
    bg = random_bg(bg_key)
  File "/dreamfields/dreamfields/augment.py", line 109, in random_bg
    bg = random.choice(bg_sel_key, bgs, p=np.array(probs))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/random.py", line 459, in choice
    raise ValueError("a must be an integer or 1-dimensional")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: a must be an integer or 1-dimensional

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 136, in <module>
    run(train=lib.run_train, eval=lib.run_eval)
  File "run.py", line 132, in run
    app.run(functools.partial(main, executable_dict))
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run.py", line 119, in main
    executable_dict[FLAGS.executable_name](
  File "/dreamfields/dreamfields/lib.py", line 805, in run_train
    for _ in DreamField(config).run_train(
  File "/dreamfields/dreamfields/lib.py", line 425, in run_train
    new_state, augs, mean_losses, new_scene_origin = train_pstep(
  File "/dreamfields/dreamfields/lib.py", line 220, in train_step
    state, aux = body_fn(state, np.squeeze(multistep_constants))
  File "/dreamfields/dreamfields/lib.py", line 209, in body_fn
    (_, aux), grad = grad_fn(state.target, grad_fn_key, *step_constants)
  File "/dreamfields/dreamfields/lib.py", line 151, in loss_fn
    augs = augment.augment_rendering(config, rgb_est, acc_est, aug_key)
  File "/dreamfields/dreamfields/augment.py", line 157, in augment_rendering
    return jax.vmap(random_aug)(random.split(key, config.n_local_aug))
  File "/dreamfields/dreamfields/augment.py", line 152, in random_aug
    bg = random_bg(bg_key)
  File "/dreamfields/dreamfields/augment.py", line 109, in random_bg
    bg = random.choice(bg_sel_key, bgs, p=np.array(probs))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/random.py", line 459, in choice
    raise ValueError("a must be an integer or 1-dimensional")
ValueError: a must be an integer or 1-dimensional
```

**Comment by ajayjain** [comment]
@INF800 Looks like this error comes up with some versions of Jax. Changing line 109 in your version of augment.py should fix it:
```
# Fixed version
bg_idx = random.choice(bg_sel_key, bgs.shape[0], p=np.array(probs))
bg = bgs[bg_idx]
```

```
# Old version
bg = random.choice(bg_sel_key, bgs, p=np.array(probs))
```

I can try to get a fix out next week.

**Comment by INF800** [comment]
Thanks!
