### ISSUE TITLE
[VATT] Issues Loading Pretrianed Checkpoint

### ISSUE THREAD

**Issue by Maddy12** [google-research/google-research#1080]
Hello, I am trying to evaluate VATT on YouCook2 dataset for text-video retrieval. I am having errors trying to load a previous checkpoint among many other package issues with tensorflow v2.7, DMVR, and more (but will save that for another ticket). 

The weights I am trying to load are for ut_fac and are stored in `weights/vatt` which I am passing as the param to `override_checkpoint`:

The link to data is: https://storage.cloud.google.com/tf_model_garden/vision/vatt/pretrain/ut_fac_medium/ckpt-500000.data-00000-of-00001
The link to index is: https://storage.cloud.google.com/tf_model_garden/vision/vatt/pretrain/ut_fac_medium/ckpt-500000.index
Then I am passing the architecture as ut_fac.

What I am calling:
```
WEIGHTS_DIR=weights/vatt
python main.py --task=pretrain \
                    --mode=eval \
                    --model_dir=$WEIGHTS_DIR \
                    --model_arch=ut_fac \
                    --strategy_type=mirrored \
                     --override_checkpoint=$WEIGHTS_DIR
```

Error: 
```
022-04-28 16:53:59.807821: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /share/apps/anaconda3-2019.03-1/lib
2022-04-28 16:53:59.807863: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0428 16:53:59.813026 22875650352960 main.py:87] Model Parameters: {'checkpoint_path': 'weights/vatt',
 'eval': {'input': {'audio_mixup': False,
                    'audio_stride': 1,
                    'batch_size': 8,
                    'color_augment': True,
                    'crop_resize_style': 'VGG',
                    'frame_size': 224,
                    'has_data': True,
                    'linearize_vision': True,
                    'max_area_ratio': 1.0,
                    'max_aspect_ratio': 2.0,
                    'max_num_words': 16,
                    'mel_bins': 80,
                    'min_area_ratio': 0.08,
                    'min_aspect_ratio': 0.5,
                    'min_resize': 224,
                    'mixup_alpha': 10,
                    'mixup_beta': 1,
                    'multi_crop': False,
                    'name': ('youcook2',),
                    'num_augmentation': 1,
                    'num_examples': 4096,
                    'num_frames': 32,
                    'num_windows_test': 4,
                    'raw_audio': True,
                    'scale_jitter': True,
                    'space_to_depth': False,
                    'split': 'test',
                    'stft_length': 0.04267,
                    'stft_step': 0.02134,
                    'text_tokenizer': 'WordTokenizer',
                    'video_stride': 2,
                    'zero_centering_image': True}},
 'mode': 'eval',
 'model_config': {'backbone_config': {'name': 'unified_backbone',
                                      'unified_backbone': 'ut_medium'},
                  'head_config': {'bridge': ({'aud_to_vid_txt_kwargs': {'d_model': 512,
                                                                        'modality': 'audio',
                                                                        'name': 'audio_mlp_module'},
                                              'bn_config': {'epsilon': 1e-05,
                                                            'momentum': 0.9,
                                                            'name': 'batch_norm',
                                                            'scale': True},
                                              'name': 'mlp_fac',
                                              'txt_to_vid_aud_kwargs': {'d_model': 256,
                                                                        'modality': 'text',
                                                                        'name': 'text_mlp_module'},
                                              'use_xreplica_bn': True,
                                              'vid_to_aud_txt_kwargs': {'d_model': 512,
                                                                        'modality': 'video',
                                                                        'name': 'video_mlp_module'}},)},
                  'loss_config': {'bridge': ({'aud_txt_weight': 0.0,
                                              'loss_weight': 1.0,
                                              'name': 'asymmetric_nce',
                                              'temperature': 0.07,
                                              'vid_aud_weight': 1.0,
                                              'vid_txt_weight': 1.0},)},
                  'model_name': 'uvatt_mlp_fac'},
 'model_dir': 'weights/vatt',
 'strategy_config': {'distribution_strategy': 'mirrored', 'tpu': None},
 'task': 'Pretrain',
 'train': {'gradient_clip_norm': 0.0,
           'gradient_clip_norm_cls': None,
           'input': {'audio_mixup': False,
                     'audio_noise': 0.01,
                     'audio_stride': 1,
                     'batch_size': 8,
                     'color_augment': True,
                     'crop_resize_style': 'VGG',
                     'frame_size': 224,
                     'has_data': True,
                     'linearize_vision': True,
                     'max_area_ratio': 1.0,
                     'max_aspect_ratio': 2.0,
                     'max_context_sentences': 4,
                     'max_num_words': 16,
                     'mel_bins': 80,
                     'min_area_ratio': 0.08,
                     'min_aspect_ratio': 0.5,
                     'min_resize': 224,
                     'mixup_alpha': 10,
                     'mixup_beta': 2,
                     'name': 'howto100m+audioset',
                     'num_examples': -1,
                     'num_frames': 32,
                     'raw_audio': True,
                     'scale_jitter': True,
                     'space_to_depth': False,
                     'split': 'train',
                     'stft_length': 0.04267,
                     'stft_step': 0.02134,
                     'text_tokenizer': 'WordTokenizer',
                     'video_stride': 1,
                     'zero_centering_image': True},
           'iterations_per_loop': 50,
           'max_checkpoints': 50,
           'optimizer': {'beta_1': 0.9,
                         'beta_2': 0.999,
                         'epsilon': 1e-07,
                         'learning_rate': {'learning_rate_base': 0.0001,
                                           'learning_rate_levels': (0.0001,
                                                                    5e-05),
                                           'learning_rate_steps': (5000,
                                                                   500000),
                                           'total_steps': 500000,
                                           'warmup_learning_rate': 0.0,
                                           'warmup_steps': 5000},
                         'name': 'Adam'},
           'save_checkpoint_freq': 10000}}
2022-04-28 16:53:59.814110: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:0
W0428 16:53:59.815804 22875650352960 cross_device_ops.py:1382] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:localhost/replica:0/task:0/device:GPU:0
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0428 16:53:59.829632 22875650352960 mirrored_strategy.py:376] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0428 16:54:00.367541 22875650352960 mlp_lib.py:122] Using Cross Replica BatchNorm in Relu-Dense-BN.
I0428 16:54:00.374226 22875650352960 mlp_lib.py:122] Using Cross Replica BatchNorm in Relu-Dense-BN.
I0428 16:54:00.376174 22875650352960 factory.py:123] Head stack mlp_fac created successfully.
I0428 16:54:00.501415 22875650352960 factory.py:134] Unified backbone ut_medium created successfully.
I0428 16:54:00.505504 22875650352960 factory.py:173] Entire MM model uvatt_mlp_fac created successfully.
I0428 16:54:09.682963 22875650352960 pretrain.py:99] Language embedding weights word2vec restored successfully.
I0428 16:54:09.692070 22875650352960 pretrain.py:130] Number of parameters in model: 182.653696 M.
I0428 16:54:09.701606 22875650352960 base.py:446] Override checkpoint found. Restoring the model from the checkpoint at weights/vatt.
2022-04-29 16:36:17.254240: W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open weights/vatt: DATA_LOSS: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/schiappa/.conda/envs/vatt_v2/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 96, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unable to open table file weights/vatt: DATA_LOSS: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 110, in <module>
    app.run(main)
  File "conda/envs/vatt_v2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File ".conda/envs/vatt_v2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "main.py", line 106, in main
    return executor.run(mode=params.mode)
  File "models/vatt/experiments/base.py", line 500, in run
    self.evaluate()
  File "models/vatt/experiments/base.py", line 450, in evaluate
    checkpoint.restore(self.params.checkpoint_path).expect_partial().assert_existing_objects_matched()
  File ".conda/envs/vatt_v2/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 2354, in restore
    status = self.read(save_path, options=options)
  File ".conda/envs/vatt_v2/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 2229, in read
    result = self._saver.restore(save_path=save_path, options=options)
  File "/home/schiappa/.conda/envs/vatt_v2/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 1322, in restore
    reader = py_checkpoint_reader.NewCheckpointReader(save_path)
  File "/home/schiappa/.conda/envs/vatt_v2/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 100, in NewCheckpointReader
    error_translator(e)
  File "schiappa/.conda/envs/vatt_v2/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 44, in error_translator
    raise errors_impl.DataLossError(None, None, error_message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file weights/vatt: DATA_LOSS: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
```

I know it says to run in python3.7 but DMVR does not work for me otherwise.

**Comment by Maddy12** [comment]
The solutions is to pass the override checkpoint with out the `.data*`

```
CHECKPOINT_PTH=weights/vatt/vision_vatt_pretrain_ut_fac_medium_ckpt-500000

python main.py --task=pretrain \
                    --mode=eval \
                    --model_dir=$MODEL_DIR \
                    --model_arch=ut_fac \
                    --strategy_type=mirrored \
                     --override_checkpoint=CHECKPOINT_PTH
```
