### ISSUE TITLE
Build ScaNN on Macos M1?

### ISSUE THREAD

**Issue by vamossagar12** [google-research/google-research#1082]
Building Scann from source on MacOs M1 fails with 
```
Original error was: dlopen(/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): tried: '/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/_multiarray_umath.cpython-38-darwin.so' (no such file), '/usr/lib/_multiarray_umath.cpython-38-darwin.so' (no such file)
Is numpy installed?
ERROR: /Users/sagarrao/gitprojects/google-research/scann/scann/scann_ops/cc/python/BUILD.bazel:8:17: //scann/scann_ops/cc/python:scann_pybind.so depends on @local_config_python//:python_headers in repository @local_config_python which failed to fetch. no such package '@local_config_python//': Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): tried: '/Users/sagarrao/gitprojects/google-research/scann/venv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/_multiarray_umath.cpython-38-darwin.so' (no such file), '/usr/lib/_multiarray_umath.cpython-38-darwin.so' (no such file)
```
after a lot of other steps which needed to be done. Anybody knows any workaround for this?

**Comment by sammymax** [comment]
ScaNN doesn't support MacOS and likely also has problems with the M1 chip, because ScaNN uses x86-specific intrinsics.

**Comment by tripathysa** [comment]
@DavidMChan : Can you please elaborate the steps to install using the patch file?

**Comment by tripathysa** [comment]
@DavidMChan : Just realized I have Intel Core in my MacOS. would the steps be same?

**Comment by DavidMChan** [comment]
Possibly/probably... I don't think there was any M1 specific optimizations that I had to make, but I don't really know. The best thing to do would be to try it and see if it works.

**Comment by tripathysa** [comment]
@DavidMChan : I am trying this https://github.com/tensorflow/recommenders/issues/597. basically trying to infer a scann powered savedmodel in Java through native TF. Is it possible? Does installing scann like above would help since this will only install scann in a python venv.?

**Comment by iozyigit0** [comment]
was able to build but getting this error
`ERROR: scann-1.2.9-cp38-cp38-macosx_13_0_x86_64.whl is not a supported wheel on this platform.`
