### ISSUE TITLE
AutoML Zero Build did not complete successfully

### ISSUE THREAD

**Issue by jds39** [google-research/google-research#1089]
Running on Windows 10 Version 20H2 (OS Build 19042.1645)

Installed Bazel, cloned git, ran:

`./run_demo.sh`

and get the following output:

> Starting local Bazel server and connecting to it...
> INFO: Repository rules_cc instantiated at:
>   C:/users/jack/documents/google-research/automl_zero/WORKSPACE:26:13: in <toplevel>
> Repository rule http_archive defined at:
>   C:/users/jack/_bazel_jack/n5bafl7x/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
> ERROR: An error occurred during the fetch of repository 'rules_cc':
>    Traceback (most recent call last):
>         File "C:/users/jack/_bazel_jack/n5bafl7x/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
>                 download_info = ctx.download_and_extract(
> Error in download_and_extract: java.io.IOException: Error extracting C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767/master.zip to C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
> ERROR: C:/users/jack/documents/google-research/automl_zero/WORKSPACE:26:13: fetching http_archive rule //external:rules_cc: Traceback (most recent call last):
>         File "C:/users/jack/_bazel_jack/n5bafl7x/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
>                 download_info = ctx.download_and_extract(
> Error in download_and_extract: java.io.IOException: Error extracting C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767/master.zip to C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
> ERROR: Skipping ':run_search_experiment': no such package '@rules_cc//cc': java.io.IOException: Error extracting C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767/master.zip to C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
> WARNING: Target pattern parsing failed.
> ERROR: no such package '@rules_cc//cc': java.io.IOException: Error extracting C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767/master.zip to C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
> INFO: Elapsed time: 23.970s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> FAILED: Build did NOT complete successfully (0 packages loaded)
>     currently loading:
>     Fetching C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc; Extracting C:/users/jack/_bazel_jack/n5bafl7x/external/rules_cc/temp1749116481683058767/master.zip

**Comment by 3dvg** [comment]
I have the same issue here, just trying to run the demo. A new window would pop up, print the above output and close immediately. 

Windows 10
Bazel 5.1.1
GCC 11.3.0

**Comment by Andy-d-g** [comment]
Same issue with the demo on macOS

Monterey 12.3.1
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Bazel 5.0.0

**Comment by rmkn85** [comment]
please try the fix here https://github.com/google-research/google-research/pull/1222
