### ISSUE TITLE
KeyError: '[CLS]' in tokenization.py

### ISSUE THREAD

**Issue by acmilannesta** [google-research/google-research#113]
INFO:tensorflow:Writing example 0 of 123163
I1104 20:48:08.980587 140516005656448 run_classifier_sp.py:804] Writing example 0 of 123163
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/albert/run_classifier_with_tfhub.py", line 319, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/albert/run_classifier_with_tfhub.py", line 233, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer)
  File "/content/albert/run_classifier_sp.py", line 807, in convert_examples_to_features
    max_seq_length, tokenizer)
  File "/content/albert/run_classifier_sp.py", line 464, in convert_single_example
    input_ids = tokenizer.convert_tokens_to_ids(tokens)
  File "/content/albert/tokenization.py", line 270, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)
  File "/content/albert/tokenization.py", line 212, in convert_by_vocab
    output.append(vocab[item])
KeyError: '[CLS]'

**Comment by jdongca2003** [comment]
First you need to upgrade tensorflow with version 1.15.  Once you download pre-trained model file locally https://tfhub.dev/google/albert_large/2), you can untar it and find the file "YOUR_PATH/assets/30k-clean.model" (sentencepiece tokenization model)
updated your script:
python -m albert.run_classifier_with_tfhub \
        --albert_hub_module_handle=https://tfhub.dev/google/albert_large/2 \
        --spm_model_file=YOUR_PATH/assets/30k-clean.model \
        --data_dir=input \
        --task_name=cola \
        --do_train=True \
        --do_eval=True \
        --train_batch_size=16 \
        --eval_batch_size=16 \
        --max_seq_length=128 \
        --learning_rate=1e-4 \
        --num_train_epochs=2 \
        --output_dir=output
