### ISSUE TITLE
[MUSIQ] Has anyone had any success in running a prediction with the MUSIQ IQA code posted here?

### ISSUE THREAD

**Issue by TimHunt12** [google-research/google-research#1160]
@junjiek or @andrewluchen

- I have downloaded the code for MUSIQ IQA and also the checkpoint models. 
- I have updated the libraries to overcome the deprecated version of TensorFlow by upgrading to version 2.9.1
- I ran the prediction with the KONIQ checkpoint and it processes the image initially.

I run into the following error when the application starts to do the prediction in line 143 in original code line 141 in my revised code.

```
Traceback (most recent call last):
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 174, in <module>
    app.run(main)
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 169, in main
    pred_mos = run_model_single_image(model_config, FLAGS.num_classes, pp_config, params, FLAGS.image_path)
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 141, in run_model_single_image
    model = model_mod.Model.partial(num_classes=num_classes, train=False, **model_config)
AttributeError: type object 'Model' has no attribute 'partial'
```

The model_mod.Model class is referenced from the multiscale_transformer.py script in the model directory.  When I go into that file there is no Class method for the Model Class called partial.  

Is this app posted by Google Research missing some code to run the prediction or am I misunderstaning something here and not setting it up right?

Thanks.

**Comment by junjiek** [comment]
Hi,

Thank you for the interest in the project. I suspect the issue is because of the flax migration from flax.nn to flax.linen. We were using the deprecated API, it is moved from flax.nn to flax.deprecated.nn. The partial function is part of the flax.nn.Module parent class. 

I just tried the code again with flax==0.3.3 and it was working for me. Could you try `pip3 install flax==0.3.3` and see if it fixes the issue?

Best

**Comment by TimHunt12** [comment]
Thanks @junjiek

I did upgrade the flax, but I'll make sure I use this version and see if that fixes the problem.  Thanks.

Tim

**Comment by TimHunt12** [comment]
@junjiek

I changed my flax to be 0.3.3, but I am getting conflicts with my tensorflow>=2.9.1 and a related library daal==2021.2.3

What version of tensor flow are you running?  Could you share with me the updated requirements.txt file or update it here?

This is what is in the requirements file now tensorflow>=2.0.0-beta1.  That version has been deprecated.

Thanks
 Tim

**Comment by junjiek** [comment]
Sorry for the late reply. I used tensorflow==2.9.1 and it worked for me.

**Comment by TimHunt12** [comment]
@junjiek 

Thanks for responding.  I have to look at what I am doing wrong then.  I need to obviously come up with a better question for you.  Thanks.

**Comment by TimHunt12** [comment]
@junjiek 

Ok I got it running with a prediction.  I did have to fix one thing in the code that is wrong in this repo.

line 40 in resent.py currently reads:
     'param = weight_standardize(param, axis=[0, 1, 2], eps=1e-5)'

However, weight_standarize is a method in the IdentiyLayer class so I changed it to:
    'param = IdentityLayer.weight_standardize(param, axis=[0, 1, 2], eps=1e-5)'

Another question for you.  I got a MOS score on an image that was 37.871147.  What is the scale top to bottom for the MOS score?  I thought initially they were on a 1 to 5 scale.  

Thanks

**Comment by TimHunt12** [comment]
@junjiek 

When I run a prediction I get a couple deprecated code warnings.  

The first 2 are the same issue.

`
WARNING:tensorflow:From /Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py:157: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
`

`
W0622 16:08:59.331060 4690888192 deprecation.py:350] From /Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py:157: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
`

`
/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/flax/nn/base.py:273: DeprecationWarning: The `flax.nn` module is Deprecated, use `flax.linen` instead. Learn more and find an upgrade guide at https://github.com/google/flax/blob/master/flax/linen/README.md
  warnings.warn("The `flax.nn` module is Deprecated, use `flax.linen` instead. Learn more and find an upgrade guide at https://github.com/google/flax/blob/master/flax/linen/README.md", DeprecationWarning)
`

I tried to upgrade to flax.linen but then it wouldn't run for me.  Do you have any suggestions? 

Thanks,

Tim

**Comment by junjiek** [comment]
flax.linen has a different way of defining modules. The documentation is here: https://flax.readthedocs.io/en/latest/flax.linen.html
For example, you will need to put the arguments as class variables and override the __call__() function. Calling the model is also a bit different (see the `model.apply` example in the documentation). In short, the current code does not work with if we just change the library from flax.nn to flax.linen. Hope it helps.

Best,
Junjie

**Comment by TimHunt12** [comment]
Thanks @junjiek

**Comment by ma7555** [comment]
can someone advise on upgrading the code from flax.nn to flax.linen?

**Comment by SDIDSA** [comment]
anyone managed to ugrade the code to flax.linen ?

i got the original code to run using these versions

`absl-py>=0.12.0
chex>=0.0.7
clu>=0.0.3
einops>=0.3.0
ml-collections==0.1.0
pandas>=1.1.0
numpy<2
tensorflow[and-cuda]==2.17.0
flax==0.3.3
jax[cuda12]<0.4.24`
