### ISSUE TITLE
unable to run Contrastive_RL

### ISSUE THREAD

**Issue by dljzx** [google-research/google-research#1182]

**Comment by dljzx** [comment]
While running run.sh, It comes the error like this:
Traceback (most recent call last):
  File "/home3/yc/Workspaces/jzx/contrastive_rl/lp_contrastive.py", line 31, in <module>
    import contrastive
  File "/home3/yc/Workspaces/jzx/contrastive_rl/contrastive/__init__.py", line 18, in <module>
    from contrastive.agents import DistributedContrastive
  File "/home3/yc/Workspaces/jzx/contrastive_rl/contrastive/agents.py", line 21, in <module>
    from acme import specs
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/acme/__init__.py", line 35, in <module>
    from acme.environment_loop import EnvironmentLoop
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/acme/environment_loop.py", line 26, in <module>
    from acme.utils import signals
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/acme/utils/signals.py", line 22, in <module>
    import launchpad
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/launchpad/__init__.py", line 36, in <module>
    from launchpad.nodes.courier.node import CourierHandle
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/launchpad/nodes/courier/node.py", line 21, in <module>
    import courier
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/courier/__init__.py", line 26, in <module>
    from courier.python.client import Client  # pytype: disable=import-error
  File "/home/yc/anaconda3/envs/contrastive_rl/lib/python3.9/site-packages/courier/python/client.py", line 30, in <module>
    from courier.python import py_client
ImportError: libtensorflow_framework.so.2: cannot open shared object file: No such file or directory


It seems to be the wrong edition of dm-acme and dm-lanuchpad. But my environment is consistent with yml. Can anyone help?

**Comment by dljzx** [comment]
@ben-eysenbach

**Comment by ben-eysenbach** [comment]
Hmm. This seems like a problem with some of the dependencies. Can you try creating a new Conda environment using these alternative instructions?

* Delete the old environment: `conda env remove -n contrastive_rl`
* Download [`requirements.txt`](https://github.com/google-research/google-research/files/9033178/requirements.txt)
* `conda create -n contrastive_rl python=3.9 -y`
* `conda activate contrastive_rl`
* `pip install -r requirements.txt --no-deps`

**Comment by alfaevc** [comment]
Same issue here:( I'm using ubuntu 20.04 FYI

**Comment by dljzx** [comment]
> Hmm. This seems like a problem with some of the dependencies. Can you try creating a new Conda environment using these alternative instructions?
> 
> * Delete the old environment: `conda env remove -n contrastive_rl`
> * Download [`requirements.txt`](https://github.com/google-research/google-research/files/9033178/requirements.txt)
> * `conda create -n contrastive_rl python=3.9 -y`
> * `conda activate contrastive_rl`
> * `pip install -r requirements.txt --no-deps`

Thanks for your reply. I reinstalled the conda environment following your instructions, but still the same problem...

**Comment by ben-eysenbach** [comment]
OK, spent some more time looking into this. I think the root cause is a missing `tensorflow` dependency for `dm-launchpad` (note that all the code in the contrastive-rl repository is written in JAX, not TensorFlow). Can you try following the instructions above again, using this updated [`requirements.txt`](https://github.com/google-research/google-research/files/9041874/requirements.3.txt) file?

**Comment by dljzx** [comment]
> OK, spent some more time looking into this. I think the root cause is a missing `tensorflow` dependency for `dm-launchpad` (note that all the code in the contrastive-rl repository is written in JAX, not TensorFlow). Can you try following the instructions above again, using this updated [`requirements.txt`](https://github.com/google-research/google-research/files/9041874/requirements.3.txt) file?

Well it did work. Thank you so much!

**Comment by alfaevc** [comment]
In our case, we had to install metaworld, d4rl and dm-acme[jax, tensorflow] after all the other packages to get it runnable. Another great news is that it also works on ubuntu 20.04. Thx for updating everything so efficiently and marvellous work!
