### ISSUE TITLE
Dream Fields : Colab notebook takes multiple hours for installation and never completes

### ISSUE THREAD

**Issue by zloc-alz** [google-research/google-research#1185]
Currently, installing the dependencies takes multiple hours and eventually never finishes. 
My previous attempt shortly after code release went fine, but now its not getting past the first code cell.

Here is a slice of pips progress after about 5 hours of installing dependencies:

```INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading pandas-1.1.5-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 52.4 MB/s 
Collecting pytz
  Downloading pytz-2017.2-py2.py3-none-any.whl (484 kB)
     |████████████████████████████████| 484 kB 67.5 MB/s 
Collecting pandas>=0.22.0
  Downloading pandas-1.1.4-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 65.9 MB/s 
  Downloading pandas-1.1.3-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 72.3 MB/s 
  Downloading pandas-1.1.2-cp37-cp37m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 41.9 MB/s 
  Downloading pandas-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 39.4 MB/s 
  Downloading pandas-1.1.0-cp37-cp37m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 3.7 MB/s 
  Downloading pandas-1.0.5-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 75.4 MB/s 
  Downloading pandas-1.0.4-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 84.1 MB/s 
  Downloading pandas-1.0.3-cp37-cp37m-manylinux1_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 70.1 MB/s 
  Downloading pandas-1.0.2-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 39.6 MB/s 
  Downloading pandas-1.0.1-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 79.9 MB/s 
  Downloading pandas-1.0.0-cp37-cp37m-manylinux1_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 41.4 MB/s 
  Downloading pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
     |████████████████████████████████| 10.4 MB 29.6 MB/s 
  Downloading pandas-0.25.2-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
     |████████████████████████████████| 10.4 MB 25.4 MB/s 
  Downloading pandas-0.25.1-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
     |████████████████████████████████| 10.4 MB 47.5 MB/s 
  Downloading pandas-0.25.0-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
     |████████████████████████████████| 10.4 MB 38.0 MB/s 
  Downloading pandas-0.24.2-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 69.1 MB/s 
Collecting pytz
  Downloading pytz-2016.10-py2.py3-none-any.whl (483 kB)
     |████████████████████████████████| 483 kB 85.3 MB/s 
  Downloading pytz-2016.7-py2.py3-none-any.whl (480 kB)
     |████████████████████████████████| 480 kB 66.2 MB/s 
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481 kB)
     |████████████████████████████████| 481 kB 86.3 MB/s 
  Downloading pytz-2016.6-py2.py3-none-any.whl (481 kB)
     |████████████████████████████████| 481 kB 64.3 MB/s 
  Downloading pytz-2016.4-py2.py3-none-any.whl (480 kB)
     |████████████████████████████████| 480 kB 93.3 MB/s 
  Downloading pytz-2016.3-py2.py3-none-any.whl (479 kB)
     |████████████████████████████████| 479 kB 84.1 MB/s 
  Downloading pytz-2016.2-py2.py3-none-any.whl (478 kB)
     |████████████████████████████████| 478 kB 88.2 MB/s 
  Downloading pytz-2016.1-py2.py3-none-any.whl (476 kB)
     |████████████████████████████████| 476 kB 87.5 MB/s 
  Downloading pytz-2015.7-py2.py3-none-any.whl (476 kB)
     |████████████████████████████████| 476 kB 100.4 MB/s 
  Downloading pytz-2015.6-py2.py3-none-any.whl (475 kB)
     |████████████████████████████████| 475 kB 96.8 MB/s 
  Downloading pytz-2015.4-py2.py3-none-any.whl (475 kB)
     |████████████████████████████████| 475 kB 89.2 MB/s 
  Downloading pytz-2015.2-py2.py3-none-any.whl (476 kB)
     |████████████████████████████████| 476 kB 97.4 MB/s 
  Downloading pytz-2014.10-py2.py3-none-any.whl (477 kB)
     |████████████████████████████████| 477 kB 90.9 MB/s 
  Downloading pytz-2014.9-py2.py3-none-any.whl (477 kB)
     |████████████████████████████████| 477 kB 85.6 MB/s 
  Downloading pytz-2014.7.zip (492 kB)
     |████████████████████████████████| 492 kB 87.3 MB/s 
  Downloading pytz-2014.4.zip (483 kB)
     |████████████████████████████████| 483 kB 76.4 MB/s 
  Downloading pytz-2014.3.zip (482 kB)
     |████████████████████████████████| 482 kB 85.3 MB/s 
  Downloading pytz-2014.2.zip (486 kB)
     |████████████████████████████████| 486 kB 77.4 MB/s 
  Downloading pytz-2014.1.1.zip (488 kB)
     |████████████████████████████████| 488 kB 72.4 MB/s 
  Downloading pytz-2014.1.zip (485 kB)
     |████████████████████████████████| 485 kB 81.5 MB/s 
  Downloading pytz-2013.9.zip (485 kB)
     |████████████████████████████████| 485 kB 75.3 MB/s 
  Downloading pytz-2013.8.zip (504 kB)
     |████████████████████████████████| 504 kB 74.5 MB/s 
  Downloading pytz-2013.7.zip (504 kB)
     |████████████████████████████████| 504 kB 66.9 MB/s 
  Downloading pytz-2013.6.zip (504 kB)
     |████████████████████████████████| 504 kB 78.2 MB/s 
  Downloading pytz-2013b.zip (535 kB)
     |████████████████████████████████| 535 kB 83.1 MB/s 
  Downloading pytz-2012c.zip (520 kB)
     |████████████████████████████████| 520 kB 5.2 MB/s 
  Downloading pytz-2012b.zip (519 kB)
     |████████████████████████████████| 519 kB 71.1 MB/s 
  Downloading pytz-2013d.zip (543 kB)
     |████████████████████████████████| 543 kB 82.0 MB/s 
  Downloading pytz-2012j.zip (535 kB)
     |████████████████████████████████| 535 kB 72.8 MB/s 
  Downloading pytz-2012h.tar.gz (255 kB)
     |████████████████████████████████| 255 kB 72.9 MB/s 
  Downloading pytz-2012g.zip (524 kB)
     |████████████████████████████████| 524 kB 77.1 MB/s 
  Downloading pytz-2012f.zip (523 kB)
     |████████████████████████████████| 523 kB 76.8 MB/s 
  Downloading pytz-2012d.zip (520 kB)
     |████████████████████████████████| 520 kB 78.4 MB/s 
  Downloading pytz-2011n.zip (519 kB)
     |████████████████████████████████| 519 kB 77.3 MB/s 
  Downloading pytz-2011k.zip (517 kB)
     |████████████████████████████████| 517 kB 80.3 MB/s 
Collecting pandas>=0.22.0
  Downloading pandas-0.24.1-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 74.8 MB/s 
  Downloading pandas-0.24.0-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 23.8 MB/s 
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /packages/67/a7/12261a51ac2e7be4c698ca27cbe364ca5f16d64999456ee47ea8c7b44417/pandas-0.23.4-cp37-cp37m-manylinux1_x86_64.whl
  Downloading pandas-0.23.4-cp37-cp37m-manylinux1_x86_64.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 5.2 MB/s 
  Downloading pandas-0.23.3-cp37-cp37m-manylinux1_x86_64.whl (8.9 MB)
     |████████████████████████████████| 8.9 MB 811 kB/s 
  Downloading pandas-0.23.2-cp37-cp37m-manylinux1_x86_64.whl (8.9 MB)
     |████████████████████████████████| 8.9 MB 13.1 MB/s 
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /packages/27/85/f9e4f0e47a6f1410b1d737b74a1764868e9197e3197a2be843507b505636/pandas-0.23.1.tar.gz
  Downloading pandas-0.23.1.tar.gz (13.1 MB)
     |████████████████████████████████| 13.1 MB 4.8 MB/s 
  Downloading pandas-0.23.0.tar.gz (13.1 MB)
     |████████████████████████████████| 13.1 MB 5.7 MB/s 
  Downloading pandas-0.22.0.tar.gz (11.3 MB)
     |████████████████████████████████| 11.3 MB 37.2 MB/s 
  Installing build dependencies ... error
WARNING: Discarding https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz#sha256=44a94091dd71f05922eec661638ec1a35f26d573c119aa2fad964f10a2880e6c (from https://pypi.org/simple/pandas/). Command errored out with exit status 1: /usr/bin/python3 /tmp/pip-standalone-pip-rmvyhaa6/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3p8ugjqk/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://us-python.pkg.dev/colab-wheels/public/simple/ -- wheel setuptools Cython 'numpy==1.9.3; python_version=='"'"'3.5'"'"'' 'numpy==1.12.1; python_version=='"'"'3.6'"'"'' 'numpy==1.13.1; python_version>='"'"'3.7'"'"'' Check the logs for full command output.
INFO: pip is looking at multiple versions of kaggle to determine which version is compatible with other requirements. This could take a while.
Collecting kaggle>=1.3.9
  Downloading kaggle-1.5.12.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 7.1 MB/s 
  Downloading kaggle-1.5.10.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 2.5 MB/s 
```

Is there any way to update this notebook to work like it did two months ago?

**Comment by zloc-alz** [comment]
After some more hours, the installation fails:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 199, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 384, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

**Comment by a-sumo** [comment]
> After some more hours, the installation fails:
> 
> ```
> ERROR: Exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
>     status = self.run(options, args)
>   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 199, in wrapper
>     return func(self, options, args)
>   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 319, in run
>     reqs, check_supported_wheels=not options.target_dir
>   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
>     requirements, max_rounds=try_to_avoid_resolution_too_deep
>   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
>     state = resolution.resolve(requirements, max_rounds=max_rounds)
>   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 384, in resolve
>     raise ResolutionTooDeep(max_rounds)
> pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
> ```

This is caused by pip's dependency resolver. See [pip-install-rasa-x-takes-forever](https://stackoverflow.com/questions/65806524/pip-install-rasa-x-takes-forever).
I had the same error with pip 21.1.3, I upgraded to the latest version as of writing this, 22.1.3 by running
``pip install --upgrade pip`` which fixed the error.
