### ISSUE TITLE
Install ROUGE from source: `AttributeError: module 'tokenize' has no attribute 'open'`

### ISSUE THREAD

**Issue by lvwerra** [google-research/google-research#1203]
Since there hasn't been a release of `rouge_score` in a while (#1199) I tried to install the package from source with:

```bash
pip install git+https://github.com/google-research/google-research.git#subdirectory=rouge
```

Which returns:
```bash
(env)  ~/git/tmp  pip install git+https://github.com/google-research/google-research.git#subdirectory=rouge
Collecting git+https://github.com/google-research/google-research.git#subdirectory=rouge
  Cloning https://github.com/google-research/google-research.git to /private/var/folders/l4/2905jygx4tx5jv8_kn03vxsw0000gn/T/pip-req-build-4q0gbc1a
  Running command git clone --filter=blob:none --quiet https://github.com/google-research/google-research.git /private/var/folders/l4/2905jygx4tx5jv8_kn03vxsw0000gn/T/pip-req-build-4q0gbc1a
  Resolved https://github.com/google-research/google-research.git to commit f3033edb77b3f4549858482c91db6131a7a7af11
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 84, in <module>
          __import__('pkg_resources.extern.packaging.requirements')
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 10, in <module>
          from pkg_resources.extern.pyparsing import (  # noqa
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 565, in module_from_spec
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/extern/__init__.py", line 52, in create_module
          return self.load_module(spec.name)
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/extern/__init__.py", line 37, in load_module
          __import__(extant)
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing/__init__.py", line 140, in <module>
          from .core import __diag__, __compat__
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 5663, in <module>
          _escapedPunc = Word(_bslash, r"\[]-*.$+^?()~ ", exact=2).set_parse_action(
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 677, in set_parse_action
          self.parseAction = [_trim_arity(fn) for fn in fns]
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 677, in <listcomp>
          self.parseAction = [_trim_arity(fn) for fn in fns]
        File "/Users/leandro/git/tmp/env/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 286, in _trim_arity
          _trim_arity_call_line = (_trim_arity_call_line or traceback.extract_stack(limit=2)[-1])
        File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 211, in extract_stack
          stack = StackSummary.extract(walk_stack(f), limit=limit)
        File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 366, in extract
          f.line
        File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 288, in line
          self._line = linecache.getline(self.filename, self.lineno).strip()
        File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 30, in getline
          lines = getlines(filename, module_globals)
        File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 46, in getlines
          return updatecache(filename, module_globals)
        File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 136, in updatecache
          with tokenize.open(fullname) as fp:
      AttributeError: module 'tokenize' has no attribute 'open'
      [end of output]
```

The issue is that there is a file `tokenize.py` in the root directory which interferes with Python's `tokenize` module. Are there any workarounds for this besides renaming the file before installation?

**Comment by chebee7i** [comment]
Still an issue.  Any plan to fix?  I can't create a proper conda package of `rouge` without a patch.
