### ISSUE TITLE
[MUSIQ] Error in Image Dimensionality

### ISSUE THREAD

**Issue by TimHunt12** [google-research/google-research#1206]
@junjiek 

I get the following error when I run inference with only some images.  Some images are fine.  My guess is that the image dimensions are somehow not compatible.  I noticed that the issue comes on images that are tall and narrow but not always.

Does the images have to be a specific dimension to have them do inference correctly?.

`
Image size: 728x2048
Image ratio: 0.35546875

Traceback (most recent call last):

  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 267, in <module>
    main()
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 251, in main
    pred = run_model_single_image(model_config, num_classes, pp_config, params, image_data)
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 160, in run_model_single_image
    image = prepare_image(image_path, pp_config)
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 137, in prepare_image
    data = pp_fn(data)
  File "/Users/timothyhunt/PycharmProjects/image_quality/model/preprocessing.py", line 301, in _preprocess_fn
    image = get_multiscale_patches(image, **preprocessing_kwargs)
  File "/Users/timothyhunt/PycharmProjects/image_quality/model/preprocessing.py", line 210, in get_multiscale_patches
    out = _extract_patches_and_positions_from_image(resized_image, patch_size, patch_stride, hse_grid_size,
  File "/Users/timothyhunt/PycharmProjects/image_quality/model/preprocessing.py", line 164, in _extract_patches_and_positions_from_image
    out = tf.concat([p, spatial_p, scale_p, mask_p], axis=2)
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimension 1 in both shapes must be equal: shape[0] = [1,28,3072] vs. shape[1] = [1,21,1] [Op:ConcatV2] name: concat
`

I get another error with a different image shape.
`
Image size: 2480x3509
Image ratio: 0.7067540609860359

Traceback (most recent call last):

  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 267, in <module>
    main()
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 243, in main
    pred_mos = run_model_single_image(model_config, num_classes, pp_config, params, image_path)
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 160, in run_model_single_image
    image = prepare_image(image_path, pp_config)
  File "/Users/timothyhunt/PycharmProjects/image_quality/run_predict_image.py", line 137, in prepare_image
    data = pp_fn(data)
  File "/Users/timothyhunt/PycharmProjects/image_quality/model/preprocessing.py", line 301, in _preprocess_fn
    image = get_multiscale_patches(image, **preprocessing_kwargs)
  File "/Users/timothyhunt/PycharmProjects/image_quality/model/preprocessing.py", line 210, in get_multiscale_patches
    out = _extract_patches_and_positions_from_image(resized_image, patch_size, patch_stride, hse_grid_size,
  File "/Users/timothyhunt/PycharmProjects/image_quality/model/preprocessing.py", line 144, in _extract_patches_and_positions_from_image
    p = tf.reshape(p, [n_crops, -1, patch_size * patch_size * c])
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/timothyhunt/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 35840 values, but the requested shape requires a multiple of 3072 [Op:Reshape]
`

These image dimensions I get a successful inference.

`
Image size: 2550x3301
Image ratio: 0.7724931838836716

36.122936 36.12_2de0e5a9-67b8-4011-bb1e-163a85863314-page-1.jpeg
`

Here is another one that processed successfully.
`
Image size: 2550x3301
Image ratio: 0.7724931838836716

35.829983 35.83_2550590.jpeg
`

Can you help?

**Comment by junjiek** [comment]
Sorry I cannot reproduce your error. I tried putting `image = tf.ones([1, 728, 2048, 3]` before [prepreocessing.py#L336](https://github.com/google-research/google-research/blob/master/musiq/model/preprocessing.py#L336) but the program finished successfully.

**Comment by TimHunt12** [comment]
@junjiek 

Thanks for getting back to me.  If I shared an image with you that fails would that help?
![2645084](https://user-images.githubusercontent.com/2401628/179618968-98930dbd-e80a-43a3-ad70-0fd714248414.jpeg)

**Comment by junjiek** [comment]
Currently the code only handles RGB images with 3 channels, you can tile the gray scale image to 3 channels if you want to handle it.

**Comment by TimHunt12** [comment]
@junjiek 

Thanks,  I think that is the problem. I am trying to now figure out how to tile the grayscale image to 3 channels.

Tim
