### ISSUE TITLE
[Poem] L2-VIPE checkpoint exception

### ISSUE THREAD

**Issue by YQZ530** [google-research/google-research#1216]
Hello,
when I try to run infer.py with L2-VIPE checkpoint I got couples of exceptions and they all related to something called " NOT_FOUND: Key SimpleModel/OutputLogits/C0/embedding_stddevs/bias not found in checkpoint".  Anyone has any idea to fix that? Thank you.

full stack trace:

WARNING:tensorflow:From /Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
/Users/labptop/Desktop/Models/ViewInvariantModel/poem/core/models.py:85: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  net = tf.layers.batch_normalization(
INFO:tensorflow:Graph was finalized.
I0728 11:22:16.444565 4388341248 monitored_session.py:243] Graph was finalized.
2022-07-28 11:22:16.444939: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:tensorflow:Restoring parameters from ./poem/tmp/checkpoint2/model.ckpt-01104395
I0728 11:22:16.446062 4388341248 saver.py:1412] Restoring parameters from ./poem/tmp/checkpoint2/model.ckpt-01104395
2022-07-28 11:22:16.450572: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-07-28 11:22:16.479388: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at save_restore_v2_ops.cc:228 : NOT_FOUND: Key SimpleModel/OutputLogits/C0/embedding_stddevs/bias not found in checkpoint
Traceback (most recent call last):
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: Key SimpleModel/OutputLogits/C0/embedding_stddevs/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1417, in restore
    sess.run(self.saver_def.restore_op_name,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1370, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 283, in <module>
      app.run(main)
    File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 308, in run
      _run_main(main, args)
    File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
      sys.exit(main(argv))
    File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 253, in main
      saver = tf.train.Saver()
Node: 'save/RestoreV2'
Key SimpleModel/OutputLogits/C0/embedding_stddevs/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

Original stack trace for 'save/RestoreV2':
  File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 283, in <module>
    app.run(main)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 253, in main
    saver = tf.train.Saver()
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 933, in __init__
    self.build()
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 945, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 973, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 543, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 363, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 611, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1501, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3754, in _create_op_internal
    ret = Operation(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 66, in get_tensor
    return CheckpointReader.CheckpointReader_GetTensor(
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1749, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 71, in get_tensor
    error_translator(e)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 283, in <module>
    app.run(main)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 262, in main
    with tf.train.MonitoredSession(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1054, in __init__
    super(MonitoredSession, self).__init__(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 757, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1263, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1268, in _create_session
    return self._sess_creator.create_session()
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 910, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 669, in create_session
    return self._get_session_manager().prepare_session(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/session_manager.py", line 310, in prepare_session
    sess, is_loaded_from_checkpoint = self._restore_checkpoint(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/session_manager.py", line 229, in _restore_checkpoint
    _restore_checkpoint_and_maybe_run_saved_model_initializers(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/session_manager.py", line 67, in _restore_checkpoint_and_maybe_run_saved_model_initializers
    saver.restore(sess, path)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1433, in restore
    raise _wrap_restore_error_with_msg(
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Graph execution error:

Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 283, in <module>
      app.run(main)
    File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 308, in run
      _run_main(main, args)
    File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
      sys.exit(main(argv))
    File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 253, in main
      saver = tf.train.Saver()
Node: 'save/RestoreV2'
Key SimpleModel/OutputLogits/C0/embedding_stddevs/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

Original stack trace for 'save/RestoreV2':
  File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 283, in <module>
    app.run(main)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/labptop/Desktop/Models/ViewInvariantModel/infer.py", line 253, in main
    saver = tf.train.Saver()
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 933, in __init__
    self.build()
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 945, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 973, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 543, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 363, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 611, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1501, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3754, in _create_op_internal
    ret = Operation(
  File "/Users/labptop/opt/anaconda3/envs/model1/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by YQZ530** [comment]
It turns out that I need to check all_flag.json and setting the correct flag in infer.py

**Comment by jenjsun** [comment]
Glad you figured it out! Essentially the layer "SimpleModel/OutputLogits/C0/embedding_stddevs/bias" should only exist for Pr-VIPE, but you were using a L2-VIPE checkpoint. L2-VIPE checkpoints do not include this layer, since the embeddings don't have standard deviations.

Let us know if there's anything else!

**Comment by YQZ530** [comment]
Thank you!
