### ISSUE TITLE
[bam] bam/task_specific/classification/classification_tasks.py", line 136, in featurize . self._distill_inputs[eid]) KeyError: 97

### ISSUE THREAD

**Issue by vikotse** [google-research/google-research#124]
I changed several config code position (includes `bert_dir` and `self.bert_config_file`) on `configure.Config`, so I can distill 12 layer teacher model's output to 3 layer student model by use another `bert_config_file`.

I could train teacher model normally.
But when I train the student model of distillation, error occurs.

command for train teacher model:
`python -m bam.run_classifier news-model-teacher $BAM_DIR '{"debug": false, "task_names": ["news"], "pretrained_model_name": "chinese_L-12_H-768_A-12", "learning_rate": 2e-5, "num_train_epochs": 3.0, "distill": false, "max_seq_length": 512, "train_batch_size": 4, "save_checkpoints_steps": 10000}'`

command for train student model:
`python -m bam.run_classifier news-model-student $BAM_DIR '{"debug": false, "task_names": ["news"], "pretrained_model_name": "chinese_L-12_H-768_A-12", "learning_rate": 2e-5, "num_train_epochs": 3.0, "distill": true, "bert_config_file": "/home/work/repo/google-research-master/bam/bam_dir/pretrained_models/chinese_L-12_H-768_A-12/bert_config_3_layer.json", "teachers": {"news": "news-model-teacher"}, "max_seq_length": 512, "train_batch_size": 4, "save_checkpoints_steps": 10000}'`

error message:
```
Traceback (most recent call last):
  File "/home/work/anaconda2/envs/py3-tf.1.12/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/work/anaconda2/envs/py3-tf.1.12/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/repo/google-research-master/bam/run_classifier.py", line 276, in <module>
    tf.app.run()
  File "/home/work/anaconda2/envs/py3-tf.1.12/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run 
    _sys.exit(main(argv))
  File "/data/repo/google-research-master/bam/run_classifier.py", line 253, in main
    model_runner = ModelRunner(config, tasks)
  File "/data/repo/google-research-master/bam/run_classifier.py", line 152, in __init__
    sizes) = self._preprocessor.prepare_train()
  File "/data/repo/google-research-master/bam/data/preprocessing.py", line 63, in prepare_train
    return self._serialize_dataset(self._tasks, True, "train")
  File "/data/repo/google-research-master/bam/data/preprocessing.py", line 108, in _serialize_dataset
    self.serialize_examples(examples, is_training, tfrecords_path)
  File "/data/repo/google-research-master/bam/data/preprocessing.py", line 127, in serialize_examples
    tf_example = self._example_to_tf_example(example, is_training)
  File "/data/repo/google-research-master/bam/data/preprocessing.py", line 136, in _example_to_tf_example
    example, is_training))
  File "/data/repo/google-research-master/bam/task_specific/classification/classification_tasks.py", line 136, in featurize
    self._distill_inputs[eid])
KeyError: 97
```

**Comment by vikotse** [comment]
@clarkkev Looking forward to your reply! Thanks.
