### ISSUE TITLE
[Felix] ValueError: Unexpected result of `train_function` (Empty logs). 

### ISSUE THREAD

**Issue by Vimos** [google-research/google-research#1317]
I have to patch the code to resolve some warnings and errors using `tensorflow==2.9.2`. 

```shell
diff --git a/felix/felix_models.py b/felix/felix_models.py
index 71412d51..cea1d2b2 100644
--- a/felix/felix_models.py
+++ b/felix/felix_models.py
@@ -18,7 +18,9 @@ from typing import Union
 
 import numpy as np
 from official.modeling import activations
-from official.nlp.legacy import configs
+# from official.nlp.legacy import configs
+from official.legacy.bert import configs
+# from official.nlp import configs
 from official.nlp.modeling import losses
 from official.nlp.modeling import models
 from official.nlp.modeling import networks
@@ -90,7 +92,8 @@ class BertPretrainLossAndMetricLayer(tf.keras.layers.Layer):
     return mask_label_loss

   def get_config(self):
-    return self._config
+    config = super().get_config()
+    return config


 def get_insertion_model(bert_config,
@@ -129,7 +132,7 @@ def get_insertion_model(bert_config,
       activation=activations.gelu,
       dropout_rate=bert_config.hidden_dropout_prob,
       attention_dropout_rate=bert_config.attention_probs_dropout_prob,
-      sequence_length=seq_length,
+      # sequence_length=seq_length,
       max_sequence_length=bert_config.max_position_embeddings,
       type_vocab_size=bert_config.type_vocab_size,
       initializer=tf.keras.initializers.TruncatedNormal(
@@ -301,8 +304,8 @@ class FelixTagLoss(tf.keras.layers.Layer):
     return total_loss

   def get_config(self):
-    return self._config
-
+    config = super().get_config()
+    return config

 def get_tagging_model(bert_config,
                       seq_length,
@@ -339,7 +342,7 @@ def get_tagging_model(bert_config,
       activation=activations.gelu,
       dropout_rate=bert_config.hidden_dropout_prob,
       attention_dropout_rate=bert_config.attention_probs_dropout_prob,
-      sequence_length=seq_length,
+      # sequence_length=seq_length,
       max_sequence_length=bert_config.max_position_embeddings,
       type_vocab_size=bert_config.type_vocab_size,
       initializer=tf.keras.initializers.TruncatedNormal(
diff --git a/felix/felix_tagger.py b/felix/felix_tagger.py
index a3a912f1..54b5b092 100644
--- a/felix/felix_tagger.py
+++ b/felix/felix_tagger.py
@@ -86,7 +86,7 @@ class FelixTagger(tf.keras.Model):
           inner_activation=activations.gelu,
           output_dropout=self._bert_config.hidden_dropout_prob,
           attention_dropout=self._bert_config.hidden_dropout_prob,
-          output_range=seq_length,
+          # output_range=seq_length,
       )

     self._query_embeddings_layer = tf.keras.layers.Dense(
@@ -140,6 +140,7 @@ class FelixTagger(tf.keras.Model):
       The logits of the edit tags and optionally the logits of the pointer
         network.
     """
+    tf.print(inputs)
     if self._is_training:
       input_word_ids, input_mask, input_type_ids, edit_tags = inputs
     else:

diff --git a/felix/run_felix.py b/felix/run_felix.py
index 95569938..f3488905 100644
--- a/felix/run_felix.py
+++ b/felix/run_felix.py
@@ -126,10 +126,13 @@ def run_train(bert_config,
       num_train_steps=steps_per_mini_epoch * mini_epochs_per_epoch * epochs,
       num_warmup_steps=warmup_steps)

+  tf.config.run_functions_eagerly(True)
+  tf.data.experimental.enable_debug_mode()
+
   pretrain_model.compile(
       optimizer=optimizer,
       loss=loss_fn,
-      experimental_steps_per_execution=FLAGS.steps_per_loop)
+      steps_per_execution=FLAGS.steps_per_loop)
   train_dataset = _get_input_data_fn(
       train_file,
       seq_length,
@@ -183,7 +186,6 @@ def run_train(bert_config,
   logging.info('Starting training from iteration: %s.', checkpoint_iteration)
   summary_dir = os.path.join(model_dir, 'summaries')
   summary_cb = tf.keras.callbacks.TensorBoard(summary_dir, update_freq=1000)
-
   manager = tf.train.CheckpointManager(
       checkpoint, directory=model_dir, max_to_keep=FLAGS.keep_checkpoint_max,
       checkpoint_name=_CHECKPOINT_FILE_NAME)
```

However, I still get the error below, is there any hint on how to solve this?

```
I1009 17:18:30.512812 140272607400896 optimization.py:90] using Adamw optimizer
I1009 17:18:30.512971 140272607400896 legacy_adamw.py:56] AdamWeightDecay gradient_clip_norm=1.000000
I1009 17:18:30.710452 140272607400896 run_felix.py:169] Initializing from a BERT checkpoint...
I1009 17:18:30.976909 140272607400896 run_felix.py:186] Starting training from iteration: 0.
Epoch 1/500
Traceback (most recent call last):
  File "/home/vimos/Data/Text/chn_nlp/TextEditing/felix/run_felix.py", line 239, in <module>
    app.run(main)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/vimos/Data/Text/chn_nlp/TextEditing/felix/run_felix.py", line 228, in main
    return run_train(bert_config, FLAGS.max_seq_length,
  File "/home/vimos/Data/Text/chn_nlp/TextEditing/felix/run_felix.py", line 196, in run_train
    pretrain_model.fit(
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1576, in fit
    raise ValueError(
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```

**Comment by Jmallins** [comment]
Hi, is there a reason to use 2.9.2 and not 2.9.1? 

But it might be worth checking that your dev/train tfrecords arn't empty. There should be a text file that specifies the size.

**Comment by Vimos** [comment]
I also tried 2.9.1 but the error is the same.

```bash
+ python run_felix.py --train_file=data/output/train.tfrecord --eval_file=data/output/tune.tfrecord --model_dir_tagging=data/output/model_tagging --bert_config_tagging=/home/vimos/Data/NFS/corpus/discofuse/discofuse_v1/wikipedia/felix_config.json --max_seq_length=128 --num_train_epochs=500 --num_train_examples=8 --num_eval_examples=8 --train_batch_size=32 --eval_batch_size=32 --log_steps=100 --steps_per_loop=100 --train_insertion=False --use_pointing=True --learning_rate=0.00003 --pointing_weight=1 --use_weighted_labels=True --init_checkpoint=data/models/uncased_L-12_H-768_A-12/bert_model.ckpt
2022-10-20 20:30:29.765338: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:29.792027: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:29.792335: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:29.803386: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-20 20:30:29.803798: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:29.804118: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:29.804264: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:30.241821: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:30.242105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:30.242309: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-20 20:30:30.242487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10399 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
I1020 20:30:32.546360 140492064822208 optimization.py:87] using Adamw optimizer
I1020 20:30:32.546533 140492064822208 optimization.py:140] gradient_clip_norm=1.000000
I1020 20:30:32.734020 140492064822208 run_felix.py:169] Initializing from a BERT checkpoint...
I1020 20:30:33.160571 140492064822208 run_felix.py:186] Starting training from iteration: 0.
Epoch 1/500
Traceback (most recent call last):
  File "/home/vimos/Data/Text/chn_nlp/TextEditing/felix/run_felix.py", line 239, in <module>
    app.run(main)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/vimos/Data/Text/chn_nlp/TextEditing/felix/run_felix.py", line 228, in main
    return run_train(bert_config, FLAGS.max_seq_length,
  File "/home/vimos/Data/Text/chn_nlp/TextEditing/felix/run_felix.py", line 196, in run_train
    pretrain_model.fit(
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1420, in fit
    raise ValueError('Unexpected result of `train_function` '
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```

I have suceessfully created `tfrecords`.
```bash
(base)  ➜  felix vimos@vimos-Z270MX-Gaming5  % ll data/output/*.tfrecord
-rw-rw-r-- 1 vimos vimos 35G Oct  9 14:04 data/output/train.tfrecord
-rw-rw-r-- 1 vimos vimos 98M Oct  9 15:54 data/output/tune.tfrecord
```

**Comment by Jmallins** [comment]
Could you try making your datasets (train/eval) size (currently 8) bigger than your batch size (currently 32).

**Comment by Vimos** [comment]
Thank you! Problem solved!
