### ISSUE TITLE
[layout-bert] can't run any data type

### ISSUE THREAD

**Issue by ryhhtn** [google-research/google-research#1319]
Thanks for the very interesting paper.

I try to train script, but got an error.

```
main.py --config configs/bert_layout_publaynet_config.py --workdir exp

Traceback (most recent call last):
  File "main.py", line 87, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 77, in main
    trainer.train()
  File "*/layout-blt/trainers/base_trainer.py", line 255, in train
    train_ds, eval_ds, _, vocab_size, pos_info = input_pipeline.get_all_dataset(
  File "*/layout-blt/input_pipeline.py", line 149, in get_all_dataset
    train_ds, vocab_size, pos_info = get_dataset(batch_size, dataset_folder,
  File "*/layout-blt/input_pipeline.py", line 113, in get_dataset
    dataset = LayoutDataset(dataset_name, ds_path, add_bos, shuffle)
  File "*/layout-blt/input_pipeline.py", line 192, in __init__
    self.data = _normalize_entries(data, shuffle)
  File "*/layout-blt/input_pipeline.py", line 65, in _normalize_entries
    children = document["children"]
TypeError: string indices must be integers

```

There is no key named children in publaynet. Do you plan to provide the appropriate code for each data

**Comment by aisagarw** [comment]
Were you able to solve this issue?

**Comment by ryhhtn** [comment]
Still unresolved.

**Comment by Warren-swr** [comment]
I have the same problem
