### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry

### ISSUE THREAD

**Issue by ntaherkhani** [google-research/google-research#132]
I am trying to creat tensorflow-hub Module using locally saved ALBER pre-trained model and I am getting this error :
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry.
I have:
tensorflow: 1.14.0
tensorflow-hub: 0.7.0
opt-einsum= 3.1.0
I am working on MAC OS High Sierra 10.13.6

**Comment by ntaherkhani** [comment]
this is the code for creating module:
import tensorflow_hub as hub
import tensorflow as tf
embed= hub.Module(“/path/to/saved/locally/pre-trained/ALBERT/Model/ALBERT_xxlarge")

this is the error that I got
Traceback (most recent call last):
File "/Users/……/python/helpers/pydev/pydevd.py", line 1741, in
main()
File "/Users/……/python/helpers/pydev/pydevd.py", line 1735, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "/Users/……/python/helpers/pydev/pydevd.py", line 1135, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "/Users/……/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "/Users/…….py", line 3, in
embed= hub.Module("/Users/……/Pretrain models/ALBERT/ALBERT_xxlarge")
File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/module.py", line 176, in init
tags=self._tags)
File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 386, in _create_impl
name=name)
File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 428, in init
op.name for op in self._meta_graph.meta_info_def.stripped_op_list.op})
File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 858, in register_ops_if_needed
"the c++ registry." % missing_ops)
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry.

I downloaded pre-trained ALBERT model from:
https://tfhub.dev/google/albert_xxlarge/2?tf-hub-format=compressed

thanks.

**Comment by liuqiangict** [comment]
Same issue with https://github.com/google-research/google-research/issues/108. No solution until now, maybe try https://tfhub.dev/google/albert_xxlarge/1.
