### ISSUE TITLE
Musiq : error on inference with musiq_imagenet_pretrain.npz, ValueError: Existing shape (384, 1000) differs from requested shape (384, 1)

### ISSUE THREAD

**Issue by Dragos-Stan** [google-research/google-research#1339]
Hello, 

I ran the predictions with the KONIQ checkpoint and it works ok.
But if I use imagenet_pretrain.npz checkpoint ( downloaded from https://console.cloud.google.com/storage/browser/gresearch/musiq;tab=objects?prefix=&forceOnObjectsSortingFiltering=false )

python -m musiq.run_predict_image \
  --ckpt_path=/tmp/spaq_ckpt.npz \
  --image_path=/tmp/image.jpg

then i get the following error : 

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/Musiq_project/musiq/run_predict_image.py", line 178, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/Musiq_project/musiq/run_predict_image.py", line 173, in main
    params, FLAGS.image_path)
  File "/content/Musiq_project/musiq/run_predict_image.py", line 145, in run_model_single_image
    logits = model.call(params, image)
  File "/usr/local/lib/python3.7/dist-packages/flax/nn/base.py", line 238, in wrapper
    return super_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flax/nn/base.py", line 238, in wrapper
    return super_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flax/nn/base.py", line 562, in call
    y = instance.apply(*args, **kwargs)
  File "/content/Musiq_project/musiq/model/multiscale_transformer.py", line 125, in apply
    x = nn.Dense(x, num_classes, name="head", kernel_init=nn.initializers.zeros)
  File "/usr/local/lib/python3.7/dist-packages/flax/nn/base.py", line 301, in __new__
    y = instance.apply(*args, **apply_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flax/nn/linear.py", line 164, in apply
    kernel = self.param('kernel', (inputs.shape[-1], features), kernel_init)
  File "/usr/local/lib/python3.7/dist-packages/flax/nn/base.py", line 591, in param
    param.shape, shape))

ValueError: Existing shape (384, 1000) differs from requested shape (384, 1)

Thanks in advance !

**Comment by FBehrad** [comment]
I used AVA checkpoint and I faced a similar problem.
