### ISSUE TITLE
kws_streaming Expected bool for argument 'enable_pcan' not 1

### ISSUE THREAD

**Issue by StuartIanNaylor** [google-research/google-research#1414]
@rybakov 
I thought I would try a ds_cnn on a esp32-s3 and thought the following would be correct as `--preprocess 'micro'` is needed as the other micro params are defaults.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/stuart/GoogleKWS/kws_streaming/train/model_train_eval.py", line 380, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/stuart/GoogleKWS/venv/lib/python3.10/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/stuart/GoogleKWS/venv/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/stuart/GoogleKWS/venv/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/stuart/GoogleKWS/kws_streaming/train/model_train_eval.py", line 156, in main
    train.train(flags)
  File "/home/stuart/GoogleKWS/kws_streaming/train/train.py", line 55, in train
    audio_processor = input_data.AudioProcessor(flags)
  File "/home/stuart/GoogleKWS/kws_streaming/data/input_data.py", line 127, in __init__
    self.prepare_processing_graph(flags)
  File "/home/stuart/GoogleKWS/kws_streaming/data/input_data.py", line 520, in prepare_processing_graph
    micro_frontend = frontend_op.audio_microfrontend(
  File "/home/stuart/GoogleKWS/venv/lib/python3.10/site-packages/tensorflow/lite/experimental/microfrontend/python/ops/audio_microfrontend_op.py", line 104, in audio_microfrontend
    return gen_audio_microfrontend_op.audio_microfrontend(
  File "/home/stuart/GoogleKWS/venv/lib/python3.10/site-packages/tensorflow/lite/experimental/microfrontend/ops/gen_audio_microfrontend_op.py", line 217, in audio_microfrontend
    enable_pcan = _execute.make_bool(enable_pcan, "enable_pcan")
  File "/home/stuart/GoogleKWS/venv/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 175, in make_bool
    raise TypeError("Expected bool for argument '%s' not %s." %
TypeError: Expected bool for argument 'enable_pcan' not 1.
```
I am using tensorflow2.11.0 as trying to work out what works best with my RTX30 series card and CUDA, so maybe its a bug due to being fresh or maybe its the params I used.
Its been a while since I looked at kws_streaming when I had a Gtx1070 as also when end checking accuracy the cuda drivers do not seem to like a GRU layer and accuracy shows approx 30% even though via TFLite they run well.
So could all be me as my memory is bad and still a bit confused, but I have enabled --feature_type 'mfcc_op' as the esp32-s3 has no problem with fft and --preprocess 'micro' but get the above.
The examples are great but would be wonderful to have one also for micro but still scratching my head slightly as with [esp32_dl ](https://github.com/espressif/esp-dl) Onnx like with others seems to be flavor of the month so maybe it just take a full TF model and convert from there, but anyway...
```
$CMD_TRAIN \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/ds_cnn_stream_micro/ \
--split_data 0 \
--wanted_words 'heymarvin,noise,unk,h1m1,h2m1,h1m2,h2m2' \
--mel_upper_edge_hertz 7600 \
--how_many_training_steps 10000,10000,5000,5000,5000,5000 \
--learning_rate 0.001,0.0005,0.0002,0.0001,0.00005,0.00001 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 40 \
--dct_num_features 20 \
--resample 0.0 \
--background_frequency 0.0 \
--alsologtostderr \
--train 1 \
--lr_schedule 'exp' \
--use_spec_augment 1 \
--time_masks_number 2 \
--time_mask_max_size 10 \
--frequency_masks_number 2 \
--frequency_mask_max_size 5 \
--feature_type 'mfcc_op' \
--fft_magnitude_squared 1 \
--preprocess 'micro' \
ds_cnn \
--cnn1_kernel_size "(3,3)" \
--cnn1_dilation_rate "(2,1)" \
--cnn1_strides "(1,1)" \
--cnn1_padding "valid" \
--cnn1_filters 300 \
--cnn1_act 'relu' \
--bn_momentum 0.98 \
--bn_center 1 \
--bn_scale 0 \
--bn_renorm 0 \
--dw2_kernel_size '(3,3),(3,3),(10,3),(5,3),(10,3)' \
--dw2_dilation_rate '(1,1),(2,2),(1,1),(2,2),(1,1)' \
--dw2_strides '(1,1),(1,1),(1,1),(1,1),(1,1)' \
--dw2_padding "valid" \
--dw2_act "'relu','relu','relu','relu','relu'" \
--cnn2_filters '300,300,300,300,300' \
--cnn2_act "'relu','relu','relu','relu','relu'" \
--dropout1 0.2
```

Is that correct and all that is needed is --fft_magnitude_squared & --preprocess 'micro'  or should it of just been ---preprocess 'micro'?
Also since I last looked there are a few more quantisation flags that I will also have to have a look at but thought would just ask whilst here as for quant from memory you just enabled --feature_type 'mfcc_op' is that different now?

Thanks.

PS yeah `--micro_enable_pcan True \` fixes it

**Comment by StuartIanNaylor** [comment]
With the RTX card and newer TF 
```
2022-12-08 04:14:49.318105: W tensorflow/c/c_api.cc:291] Operation '{name:'loss/mul' id:1075 op device:{requested: '', assigned: ''} def:{{{node loss/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss/mul/x, loss/dense_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
```
The GRU was with a CRNN but if its a quick and easy reply then please do but will look into that as pretty sure never saw these with the older 1070 card and think it was tf2.8 when I last used kws_streaming

**Comment by rybakov** [comment]
Please have a look at  [speech-feature-extraction-configs](https://github.com/google-research/google-research/tree/master/kws_streaming#speech-feature-extraction-configs)
In your command feature_type  will be ignored and only preprocess='micro' will be used:
```
--feature_type 'mfcc_op' \
--fft_magnitude_squared 1 \
--preprocess 'micro' \
```

I would suggest to use default speech feature extractor with preprocess='raw';
feature_type='mfcc_tf', it is better also to set use_tf_fft=1 (so that you can quantize your model). This way you have full control over the whole model and can run it end to end. 'mfcc_op' is a special op in TFLite (it can run only on CPU) and you can only set some parameters there.  'micro' is a very special use case (it can run only on CPU), model will be divided into two parts, the first part will have 'micro' speech feature extractor and second part is the model itself, so during inference you will have to run feature extractor using 'micro' and then feed extracted features into your model.

**Comment by StuartIanNaylor** [comment]
Thanks @rybakov looks like I got the wrong end of the stick with 'micro' it just looked very much like [the micro front-end](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/microfrontend) and made an assumption.

Thanks for all the work and if you ever get time to add a few more examples then please do :)
