### ISSUE TITLE
[RegNerf] Jax Error 

### ISSUE THREAD

**Issue by sandy-ssdut** [google-research/google-research#1427]
Hi,

I am running RegNerf, but there is a jax error:

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    from internal import configs, datasets, math, models, utils, vis  # pylint: disable=g-multiple-import
  File "/raid/liuzhaoliang/code/nerf/google-research/regnerf/internal/vis.py", line 17, in <module>
    import dm_pix as pix
  File "/home/lzl/.local/lib/python3.8/site-packages/dm_pix/__init__.py", line 16, in <module>
    from dm_pix._src import augment
  File "/home/lzl/.local/lib/python3.8/site-packages/dm_pix/_src/augment.py", line 24, in <module>
    import chex
  File "/home/lzl/.local/lib/python3.8/site-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/home/lzl/.local/lib/python3.8/site-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/home/lzl/.local/lib/python3.8/site-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/home/lzl/.local/lib/python3.8/site-packages/chex/_src/pytypes.py", line 36, in <module>
    PRNGKey = jax.random.KeyArray
AttributeError: module 'jax.random' has no attribute 'KeyArray'

**Comment by amughrabi** [comment]
I had the same logs; reinstalling the conda environment solved my issue.
