### ISSUE TITLE
module 'args' has no attribute 'use_dpt'

### ISSUE THREAD

**Issue by nickums** [google-research/google-research#1552]
after installing args (not in the . yaml), executing   pvg_lhq_test.py,  I get this:

Warning (from warnings module):[](
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 121
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
DeprecationWarning: pkg_resources is deprecated as an API

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('paste')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2349
    declare_namespace(parent)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2349
    declare_namespace(parent)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('repoze')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2870
    declare_namespace(pkg)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4
    if not hasattr(tensorboard, "__version__") or LooseVersion(
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\torch\utils\tensorboard\__init__.py", line 6
    ) < LooseVersion("1.15"):
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\eventlet\support\greenlets.py", line 6
    preserves_excinfo = (distutils.version.LooseVersion(greenlet.__version__)
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\eventlet\support\greenlets.py", line 7
    >= distutils.version.LooseVersion('0.3.2'))
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\dns\hash.py", line 23
    warnings.warn(
DeprecationWarning: dns.hash module will be removed in future versions. Please use hashlib instead.

Warning (from warnings module):
  File "C:\Python\Python38\lib\site-packages\dns\namedict.py", line 35
    class NameDict(collections.MutableMapping):
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3'
Using C:\Users\trade\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cpu as PyTorch extensions root...
Emitting ninja build file C:\Users\trade\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cpu\splatting_cpu\build.ninja...
Building extension module splatting_cpu...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Loading extension module splatting_cpu...
----------------- Options ---------------
            ada_sky_shift: False                         
             aspect_ratio: 1.0                           
               compositor: splat                         
                crop_size: 128                           
                 is_train: False                         	[default: None]
       load_from_opt_file: False                         
               local_rank: 0                             
                    model: render                        
                     name: infinite-nature-zero          
                  use_dpt: False                         
----------------- End -------------------
Traceback (most recent call last):
  File "C:\Python\Python38\GitHub\Infinite_Nature\pvg_lhq_test.py", line 55, in <module>
    inference_data_loader = LHQGANDataLoader(args,
  File "C:\Python\Python38\GitHub\Infinite_Nature\Data\nature_data_loader.py", line 28, in __init__
    dataset = LHQTestDataset(opt=args, data_list=data_list, phase=phase)
  File "C:\Python\Python38\GitHub\Infinite_Nature\Data\lhq_folder.py", line 34, in __init__
    self.use_dpt = opt.use_dpt
AttributeError: module 'args' has no attribute 'use_dpt')
>>>

**Comment by nickums** [comment]
This is for the Infinite_Nature project
