### ISSUE TITLE
kws_streaming: model conversion  to TfLite fails

### ISSUE THREAD

**Issue by smhsn** [google-research/google-research#1567]
Hi all, I have trained the kws_streaming model using my own dataset and am now trying to convert it to the TfLite. However, I get the following error: 
ValueError: Unable to save function b'__inference_speech_features_layer_call_and_return_conditional_losses_9410' because it captures graph tensor Tensor("streaming_1/speech_features/windowing_2/hann_window/sub_2:0", shape=(480,), dtype=float32) from a parent function which cannot be converted to a constant with `tf.get_static_value`.

Thje problem is the model cannot be saved in .tf format, and TfLite conversion function does not accept other formats (.h5 or .keras).
Does anybody have an idea how to solve this?

**Comment by smhsn** [comment]
Hi, thanks for the quick reply. Here are the details:

FLAGS.mel_upper_edge_hertz = 7600
FLAGS.window_size_ms = 30.0
FLAGS.window_stride_ms = 10.0
FLAGS.mel_num_bins = 80
FLAGS.dct_num_features = 40
FLAGS.feature_type = 'mfcc_tf'
FLAGS.preprocess = 'raw'
FLAGS.causal_data_frame_padding = 1
FLAGS.use_tf_fft = True
FLAGS.mel_non_zero_only = not FLAGS.use_tf_fft
FLAGS.train = 1
FLAGS.how_many_training_steps = '10000,10000,10000,10000'
FLAGS.learning_rate = '0.001,0.0005,0.0001,0.00002'
FLAGS.lr_schedule = 'linear'
FLAGS.verbosity = logging.INFO

FLAGS.resample = 0.15
FLAGS.time_shift_ms = 100
FLAGS.use_spec_augment = 1
FLAGS.time_masks_number = 2
FLAGS.time_mask_max_size = 25
FLAGS.frequency_masks_number = 2
FLAGS.frequency_mask_max_size = 7
FLAGS.pick_deterministically = 1

FLAGS.model_name = 'ds_tc_resnet'
FLAGS.activation = 'relu'
FLAGS.dropout = 0.0
FLAGS.ds_filters = '128, 64, 64, 64, 128, 128'
FLAGS.ds_filter_separable = '1, 1, 1, 1, 1, 1'
FLAGS.ds_repeat = '1, 1, 1, 1, 1, 1'
FLAGS.ds_residual = '0, 1, 1, 1, 0, 0' # residual can not be applied with stride
FLAGS.ds_kernel_size = '11, 5, 15, 17, 15, 1'
FLAGS.ds_dilation = '1, 1, 1, 1, 2, 1'
FLAGS.ds_stride = '1, 1, 1, 1, 1, 1'
FLAGS.ds_pool = '1, 2, 1, 1, 1, 1'
FLAGS.ds_padding = "'causal', 'causal', 'causal', 'causal', 'causal', 'causal'"

FLAGS.clip_duration_ms = 1500  
FLAGS.batch_size = 100

flags = model_flags.update_flags(FLAGS)

with open(os.path.join(flags.train_dir, 'flags.json'), 'wt') as f:
  json.dump(flags.__dict__, f)

train.train(flags)

model_non_stream_batch = models.MODELS[flags.model_name](flags)
weights_name = 'best_weights'
model_non_stream_batch.load_weights(os.path.join(train_dir, weights_name))

flags.data_shape = (total_stride * flags.window_stride_samples,)
window_stride = flags.data_shape[0]
mode = 'stream_internal'
inference_batch_size = 1
model_stream_internal = utils.to_streaming_inference(model_non_stream_batch, flags, Modes.STREAM_INTERNAL_STATE_INFERENCE)

tflite_streaming_model = utils.model_to_tflite(None, model_non_stream_batch, flags, Modes.STREAM_INTERNAL_STATE_INFERENCE)

**Comment by smhsn** [comment]
hi @rybakov, I used kws_streaming/train/model_train_eval.py to retrain and save the internal stream model as TfLite. The model flags are as follows: 

"Namespace(data_url='', data_dir='my_data/', lr_schedule='linear', optimizer='adam', background_volume=0.1, l2_weight_decay=0.0, background_frequency=0.8, split_data=0, silence_percentage=10.0, unknown_percentage=10.0, time_shift_ms=100.0, sp_time_shift_ms=0.0, testing_percentage=10, validation_percentage=10, how_many_training_steps='2500,2500,2500,2500', eval_step_interval=400, learning_rate='0.001,0.0005,0.0001,2E-05', batch_size=100, wanted_words='label1,label2', train_dir='models/ds_tc_resnet/', save_step_interval=100, start_checkpoint='', verbosity=0, optimizer_epsilon=1e-08, resample=0.15, sp_resample=0.0, volume_resample=0.0, train=1, sample_rate=16000, clip_duration_ms=1500, window_size_ms=30.0, window_stride_ms=10.0, preprocess='raw', feature_type='mfcc_tf', preemph=0.0, window_type='hann', mel_lower_edge_hertz=20.0, mel_upper_edge_hertz=7600.0, micro_enable_pcan=True, micro_features_scale=0.0390625, micro_min_signal_remaining=0.05, micro_out_scale=1, log_epsilon=1e-12, dct_num_features=40, use_tf_fft=True, mel_non_zero_only=False, fft_magnitude_squared=False, mel_num_bins=80, use_spec_augment=1, time_masks_number=2, time_mask_max_size=25, frequency_masks_number=2, frequency_mask_max_size=7, use_spec_cutout=0, spec_cutout_masks_number=3, spec_cutout_time_mask_size=10, spec_cutout_frequency_mask_size=5, return_softmax=0, novograd_beta_1=0.95, novograd_beta_2=0.5, novograd_weight_decay=0.001, novograd_grad_averaging=0, pick_deterministically=1, causal_data_frame_padding=1, wav=1, quantize=0, use_quantize_nbit=0, nbit_activation_bits=8, nbit_weight_bits=8, data_stride=1, restore_checkpoint=0, model_name='ds_tc_resnet', activation='relu', dropout=0.0, ds_filters='128, 64, 64, 64, 128, 128', ds_repeat='1, 1, 1, 1, 1, 1', ds_filter_separable='1, 1, 1, 1, 1, 1', ds_residual='0, 1, 1, 1, 0, 0', ds_padding="'causal', 'causal', 'causal', 'causal', 'causal', 'causal'", ds_kernel_size='11, 5, 15, 17, 15, 1', ds_stride='1, 1, 1, 1, 1, 1', ds_dilation='1, 1, 1, 1, 2, 1', ds_pool='1, 2, 1, 1, 1, 1', ds_max_pool=0, ds_scale=1, nbit_8bit_until_block=1, nbit_8bit_last=1, label_count=2, desired_samples=24000, window_size_samples=480, window_stride_samples=160, spectrogram_length=148, data_frame_padding='causal', summaries_dir='models/ds_tc_resnet/logs/', training=True)"

I added the following lines to kws_streaming/train/model_train_eval.py:
        "folder_name = opt_name + 'tflite_stream_state_internal'
        file_name = 'stream_state_internal.tflite'
        mode = modes.Modes.STREAM_INTERNAL_STATE_INFERENCE
        test.convert_model_tflite(flags, folder_name, mode, file_name,
                                  optimizations=optimizations)"

and replaced "sess" with "None" (eager mode) in kws_streaming/train/test.py/convert_model_tflite() function :
"kws_streaming.models.utils.model_to_tflite(None, model, flags, mode, path_model, optimizations))" 

model is trained, however for saving the stream internal model as tflite it gives the following error:

FAILED to convert to mode STREAM_INTERNAL_STATE_INFERENCE, tflite: Negative dimension size caused by subtracting 2 from 1 for '{{node streaming/average_pooling2d/AvgPool}} = AvgPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 1, 1], padding="VALID", strides=[1, 2, 1, 1]](streaming/dropout_1/Identity)' with input shapes: [1,1,1,64].

**Comment by tuannvhust** [comment]
@smhsn dear sir, I got trouble when re-training the model. Which is the conflict of the dependencies I'm installing. Can you specify the version of tf_nightly , tensorflow_addons and tensorflow_model_optimization you are using to train. That means a lot to me, cc @rybakov . Here are my bug : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/models1/kws_streaming/train/model_train_eval.py", line 112, in <module>
    import kws_streaming.models.att_mh_rnn as att_mh_rnn
  File "/workspace/models1/kws_streaming/models/att_mh_rnn.py", line 18, in <module>
    from kws_streaming.layers import speech_features
  File "/workspace/models1/kws_streaming/layers/speech_features.py", line 24, in <module>
    from kws_streaming.layers import random_shift
  File "/workspace/models1/kws_streaming/layers/random_shift.py", line 18, in <module>
    from keras.utils import control_flow_util
ImportError: cannot import name 'control_flow_util' from 'keras.utils' (/usr/local/lib/python3.8/site-packages/keras/utils/__init__.py)
root@6f1a60dcf9df:/workspace/models1# export TF_ENABLE_ONEDNN_OPTS=0
root@6f1a60dcf9df:/workspace/models1# python3 -m kws_streaming.train.model_train_eval --data_url '' --data_dir ./data1/ --train_dir ./models1/dnn_1/ --mel_upper_edge_hertz 7000 --how_many_training_steps 100,100,100 --learning_rate 0.0005,0.0001,0.00002 --window_size_ms 40.0 --window_stride_ms 20.0 --mel_num_bins 40 --dct_num_features 20 --resample 0.15 --alsologtostderr --train 1 dnn --units1 '64,128' --act1 "'relu','relu'" --pool_size 2 --strides 2 --dropout1 0.1 --units2 '128,256' --act2 "'linear','relu'"
2023-04-20 08:13:40.464407: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-20 08:13:40.505306: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-20 08:13:40.505873: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-20 08:13:41.408289: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/models1/kws_streaming/train/model_train_eval.py", line 112, in <module>
    import kws_streaming.models.att_mh_rnn as att_mh_rnn
  File "/workspace/models1/kws_streaming/models/att_mh_rnn.py", line 18, in <module>
    from kws_streaming.layers import speech_features
  File "/workspace/models1/kws_streaming/layers/speech_features.py", line 24, in <module>
    from kws_streaming.layers import random_shift
  File "/workspace/models1/kws_streaming/layers/random_shift.py", line 18, in <module>
    from keras.utils import control_flow_util
ImportError: cannot import name 'control_flow_util' from 'keras.utils' (/usr/local/lib/python3.8/site-packages/keras/utils/__init__.py)
```

**Comment by rybakov** [comment]
@smhsn, I think the issues is streaming pooling, please try ds_pool='1, 1, 1, 1, 1, 1'. 

It is possible to stream models with pooling > 1 wiht ds_pool='1, 2, 1, 1, 1, 1' but you will need to modify the size of the input tensor in streaming mode. For example with ds_pool='1, 2, 1, 1, 1, 1' you need to set [data_stride](https://github.com/google-research/google-research/blob/master/kws_streaming/train/base_parser.py#L517)=2. Input tensor in streaming mode is set in [line](https://github.com/google-research/google-research/blob/master/kws_streaming/models/utils.py#L285) by
```
input_data_shape = modes.get_input_data_shape(flags, mode)
```

@tuannvhust kws_streaming lib is always at sync with HEAD of tf_nightly , tensorflow_addons and tensorflow_model_optimization. The error 
```
ImportError: cannot import name 'control_flow_util' from 'keras.utils' 
```
means that your TF version is old, e.g. the same issue in [link](https://github.com/tensorflow/tensor2tensor/issues/1167)

**Comment by smhsn** [comment]
> @smhsn, I think the issues is streaming pooling, please try ds_pool='1, 1, 1, 1, 1, 1'.

I tried that but again I get the  following error : 

W0424 14:51:15.897528 28816 test.py:561] FAILED to convert to mode STREAM_INTERNAL_STATE_INFERENCE, tflite: Unable to save function b'__inference_speech_features_layer_call_and_return_conditional_losses_30649' because it captures graph tensor Tensor("streaming/speech_features/windowing_1/hann_window/sub_2:0", shape=(480,), dtype=float32) from a parent function which cannot be converted to a constant with `tf.get_static_value`.

I0424 14:51:15.913075 28816 model_train_eval.py:206] feature type mfcc_tf needs quantization aware training for quantization - it is not implemented

please note that features are FFT based (use_tf_fft=1) so conversion to Tflite should work without quantization aware training, or am I wrong?
