### ISSUE TITLE
Unable to run the experiment in local_forward_gradient

### ISSUE THREAD

**Issue by caesaretos** [google-research/google-research#1589]
I was unable to run the experiments in this [folder](https://github.com/google-research/google-research/tree/master/local_forward_gradient).

I installed all the requirements mentioned in the requirements.txt.

I tried to run `train_mixer_supervised.py`, but I got the following error: 

`Traceback (most recent call last):`
`  File "train_mixer_supervised.py", line 2532, in <module>`
`    app.run(main)`
`  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run`
`    _run_main(main, args)`
`  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main`
`    sys.exit(main(argv))`
`  File "train_mixer_supervised.py", line 2454, in main`
`    layer_sizes = get_layer_sizes(`
`  File "/home/google-research/local_forward_gradient/mixer_lib.py", line 125, in get_layer_sizes`
`    num_tokens_ = num_tokens_ // (downsample[blk]**2)`
`IndexError: list index out of range`

**Comment by macrocredit** [comment]
There is a small change to the flag here.

Change to: flags.DEFINE_integer('num_blocks', 4, 'number of mixer blocks')
Comment out: # flags.DEFINE_integer('num_blocks', 6, 'number of mixer blocks')

This should work on both single and multi-GPUs.
