### ISSUE TITLE
TFT Download Data

### ISSUE THREAD

**Issue by Duonijo** [google-research/google-research#1616]
Hey everyone,
Might be something wrong with what i'am doing but I try to run the experiment about TFT.
But I can't download data by running :

```
python3 -m script_download_data volatility res
```

I am getting things like 

```
#### Running download script ###
Resetting data folder...
Getting volatility data...
Pulling data from https://realized.oxford-man.ox.ac.uk/images/oxfordmanrealizedvolatilityindices.zip to res/data/volatility/oxfordmanrealizedvolatilityindices.zip
Traceback (most recent call last):
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/nicolas/Documents/Thèse/Projects/ED Forecasting/tft/script_download_data.py", line 646, in <module>
    main(expt_name=name, force_download=force, output_folder=folder)
  File "/Users/nicolas/Documents/Thèse/Projects/ED Forecasting/tft/script_download_data.py", line 603, in main
    download_function(expt_config)
  File "/Users/nicolas/Documents/Thèse/Projects/ED Forecasting/tft/script_download_data.py", line 109, in download_volatility
    download_and_unzip(url, zip_path, csv_path, data_folder)
  File "/Users/nicolas/Documents/Thèse/Projects/ED Forecasting/tft/script_download_data.py", line 92, in download_and_unzip
    download_from_url(url, zip_path)
  File "/Users/nicolas/Documents/Thèse/Projects/ED Forecasting/tft/script_download_data.py", line 59, in download_from_url
    wget.download(url, output_path)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/nicolas/miniforge3/envs/test_tft/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

```

I tried with wget to download data but it seems that they are unavailable.

Am I the one messing things up?

Thanks for you help

**Comment by heyimjonas** [comment]
Electricity worked for me.
I just checked the link of volatility, and it seems it got removed/is no longer accessible.
