### ISSUE TITLE
[F-VLM] pre-computed embeddings

### ISSUE THREAD

**Issue by luisdavid64** [google-research/google-research#1731]
Hi, thanks for the great repo @ https://github.com/google-research/google-research/tree/master/fvlm @weichengkuo
I just wanted to know how to obtain the pre-computed embeddings for a custom dataset to train F-VLM. Do I simply have to embed my dataset classes with CLIP?

**Comment by weichengkuo** [comment]
Thanks for the question @luisdavid64! Yes - I'll recommend using our reproduced CLIP (see example [here](https://github.com/google-research/google-research/blob/b7cb09ba04bf018f1ba1131ccd4c69be617e8e2f/fvlm/demo.py#L75) rather than the official CLIP for optimal performance, as there may be some minor/slight differences. The [demo.py](https://github.com/google-research/google-research/blob/master/fvlm/demo.py) shows an example of how to compute custom text embeddings for F-VLM, which are based on this input [argument](https://github.com/google-research/google-research/blob/b7cb09ba04bf018f1ba1131ccd4c69be617e8e2f/fvlm/demo.py#L57). [Here](https://github.com/google-research/google-research/blob/b7cb09ba04bf018f1ba1131ccd4c69be617e8e2f/fvlm/demo.py#L101) is where the text embedding computation starts from a list of category names. This [line](https://github.com/google-research/google-research/blob/b7cb09ba04bf018f1ba1131ccd4c69be617e8e2f/fvlm/demo.py#L120) is where the text embeddings are fully computed. Hope these help!

**Comment by luisdavid64** [comment]
Thank you for the prompt answer @weichengkuo, your answer definitely helps! I just had one last question regarding the pre-computed embeddings. Upon inspecting the resnet_50 precomputed  COCO embeddings, I notice they have a shape of `(1601, 1024)`, which is more than the number of classes in the dataset. May I know if there is some processing done to the class labels?

**Comment by weichengkuo** [comment]
No problem, yes the shape comes from adding the background and empty embeddings. Thanks!

**Comment by XuanHanTan** [comment]
Hi @weichengkuo , thank you for your work on FVLM! I tried computing embeddings for my custom dataset as per your suggestions, but I got this error when training the model.
```
I0518 16:45:43.971910 140090028156736 trainer_utils.py:622] Getting first batch.
I0518 16:45:45.016001 140090028156736 trainer_utils.py:624] Building model.
Traceback (most recent call last):
  File "/home/jupyter/fvlm/./train_and_eval.py", line 63, in <module>
    app.run(main)
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/jupyter/fvlm/./train_and_eval.py", line 53, in main
    trainer_utils.train(_OUTPUT_DIR.value)
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/jupyter/fvlm/utils/trainer_utils.py", line 627, in train
    variables = init_model(
  File "/home/jupyter/fvlm/utils/trainer_utils.py", line 324, in init_model
    return init_fn(rng_dict)
  File "/home/jupyter/fvlm/utils/trainer_utils.py", line 321, in <lambda>
    lambda rng_key: frozen_dict.freeze(model_fn(mode=mode).init(
  File "/home/jupyter/fvlm/utils/gin_utils.py", line 167, in wrapped
    return base(*args, **mapped_kwargs)
  File "/home/jupyter/fvlm/modeling/multitask_model.py", line 111, in __call__
    task_outputs = task_head(vision_features, text_features,
  File "/home/jupyter/fvlm/modeling/task_heads.py", line 399, in __call__
    class_outputs = self.compute_region_text_similarity(
  File "/home/jupyter/fvlm/modeling/task_heads.py", line 228, in compute_region_text_similarity
    class_outputs = jnp.einsum(
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4514, in einsum
    operands, contractions = contract_path(
  File "/opt/conda/envs/tensorflow/lib/python3.10/site-packages/opt_einsum/contract.py", line 228, in contract_path
    raise ValueError("Einstein sum subscript '{}' does not contain the "
ValueError: Einstein sum subscript 'ilk' does not contain the correct number of indices for operand 1.
  In call to configurable 'train' (<function train at 0x7f67c55284c0>)
```

I also noticed that the shape of my embeddings is (1, 91, 1024). Could this be a cause for concern? That being said, demo.py gives the same shape too.

Could you advise me on this issue?
