### ISSUE TITLE
[DITO] About train*.tfrecord and val*.tfrecord file

### ISSUE THREAD

**Issue by Xianqiao-Cai** [google-research/google-research#1887]
**Thank you so much for your great contribution.When i follow the steps [here](https://cloud.google.com/tpu/docs/tutorials/mask-rcnn-2.x?hl=zh-cn#prepare-coco) to set up the COCO dataset. Due to the version conflict problem of protobuf library, I still couldn't get the tfrecord file after many attempts. Then in [kaggle website,](https://www.kaggle.com/datasets/karthikeyanvijayan/coco-2017-tfrecords) I downloaded the tfrecord file of coco2017, but there was an error when running.The error message is below.Can you provide the tfrecord file used by the code.**

**Here is the log**:
python /home/cxq/fvlm/train_and_eval.py --output_dir=/home/cxq/fvlm/train_and_eval --config_path=/home/cxq/fvlm/dito/configs/dito_train_and_eval.gin --mode=eval
2024-01-05 11:17:39.536796: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-05 11:17:39.536845: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-05 11:17:39.536884: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-05 11:17:40.268877: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
loading annotations into memory...

Done (t=6.75s)
creating index...
index created!

/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/jax/_src/xla_bridge.py:945: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
  warnings.warn(
I0105 11:17:51.302165 140054668191552 xla_bridge.py:660] Unable to initialize backend 'cuda': 
I0105 11:17:51.302592 140054668191552 xla_bridge.py:660] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0105 11:17:51.304751 140054668191552 xla_bridge.py:660] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: 无法打开共享对象文件: 没有那个文件或目录
W0105 11:17:51.305198 140054668191552 xla_bridge.py:727] An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/jax/_src/xla_bridge.py:961: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  warnings.warn(
2024-01-05 11:17:54.623148: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.623617: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.623711: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.623792: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.623880: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
Traceback (most recent call last):
  File "/home/cxq/fvlm/train_and_eval.py", line 64, in <module>
2024-01-05 11:17:54.623939: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.624235: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    app.run(main)
2024-01-05 11:17:54.624286: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/absl/app.py", line 308, in run
2024-01-05 11:17:54.624385: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.624472: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    _run_main(main, args)
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
2024-01-05 11:17:54.624519: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    sys.exit(main(argv))
  File "/home/cxq/fvlm/train_and_eval.py", line 55, in main
    trainer_utils.evaluate(_OUTPUT_DIR.value)
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
2024-01-05 11:17:54.624564: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
2024-01-05 11:17:54.625150: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.625325: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.625394: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    return fn(*new_args, **new_kwargs)
  File "/home/cxq/fvlm/utils/trainer_utils.py", line 912, in evaluate
2024-01-05 11:17:54.625488: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
2024-01-05 11:17:54.625596: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    batch = next(data_generator)
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/flax/jax_utils.py", line 144, in prefetch_to_device
2024-01-05 11:17:54.625665: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at example_parsing_ops.cc:98 : INVALID_ARGUMENT: Feature: image/encoded (data type: string) is required but could not be found.
    enqueue(size)  # Fill up the buffer.
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/flax/jax_utils.py", line 141, in enqueue
    for data in itertools.islice(iterator, n):
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_utils.py", line 82, in _eager_dataset_iterator
    for elem in ds:
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 809, in `__next__`
    return self._next_internal()
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3028, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/cxq/anaconda3/envs/dito/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_17_device_/job:localhost/replica:0/task:0/device:CPU:0}} Feature: image/encoded (data type: string) is required but could not be found.
	 [[{{node parser/ParseSingleExample/ParseExample/ParseExampleV2}}]] [Op:IteratorGetNext] name: 
  In call to configurable 'evaluate' (<function evaluate at 0x7f5ebb64adc0>)
2024-01-05 11:17:58.945075: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by phamnhuvu-dev** [comment]
Hi @Xianqiao-Cai what did you do to resolve this problem?
