### ISSUE TITLE
[KWS_Streaming] AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'LocallyConnected1D'

### ISSUE THREAD

**Issue by leehucheng** [google-research/google-research#1927]
Hi,

I'm running the kws_streaming code following the instructions from here:
https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_12_labels.md#install-tensorflow-with-deps

When I tried to train the bc_resnet_1 model, I ran into the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/RAID/hucheng/voice_control/test/kws_streaming/train/model_train_eval.py", line 112, in <module>
    import kws_streaming.models.att_mh_rnn as att_mh_rnn
  File "/RAID/hucheng/voice_control/test/kws_streaming/models/att_mh_rnn.py", line 18, in <module>
    from kws_streaming.layers import speech_features
  File "/RAID/hucheng/voice_control/test/kws_streaming/layers/speech_features.py", line 26, in <module>
    from kws_streaming.layers import spectrogram_augment
  File "/RAID/hucheng/voice_control/test/kws_streaming/layers/spectrogram_augment.py", line 20, in <module>
    import tensorflow_model_optimization as tfmot
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/__init__.py", line 86, in <module>
    from tensorflow_model_optimization.python.core.api import clustering
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/api/__init__.py", line 16, in <module>
    from tensorflow_model_optimization.python.core.api import clustering
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py", line 16, in <module>
    from tensorflow_model_optimization.python.core.api.clustering import keras
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py", line 19, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_scope
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py", line 22, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras import cluster_wrapper
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py", line 24, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras import clustering_registry
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py", line 57, in <module>
    class ClusteringRegistry(object):
  File "/home/leehucheng/virtualenv/venv3/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py", line 76, in ClusteringRegistry
    layers.LocallyConnected1D: ['kernel'],
AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'LocallyConnected1D'`

I've followed the instructions and found the possible solution from here:
https://github.com/google-research/google-research/issues/1855

I've already updated the [tensorflow_model_optimization](https://www.tensorflow.org/model_optimization/guide/install) module but still got the same error.

Here are my pip packages:
`absl-py==1.4.0
astunparse==1.6.3
certifi==2023.11.17
charset-normalizer==3.3.2
distlib==0.3.8
dm-tree==0.1.8
filelock==3.13.1
flatbuffers==23.5.26
gast==0.5.4
google-pasta==0.2.0
graphviz==0.20.1
grpcio==1.60.0
h5py==3.10.0
idna==3.6
importlib-metadata==7.0.1
keras-nightly==3.0.4.dev2024013003
libclang==16.0.6
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.4
mdurl==0.1.2
ml-dtypes==0.3.2
namex==0.0.7
numpy==1.26.3
opt-einsum==3.3.0
packaging==23.2
platformdirs==4.1.0
protobuf==4.25.2
pydot==2.0.0
Pygments==2.17.2
pyparsing==3.1.1
requests==2.31.0
rich==13.7.0
six==1.16.0
tb-nightly==2.16.0a20240129
tensorboard-data-server==0.7.2
tensorflow-addons==0.23.0
tensorflow-io-gcs-filesystem==0.35.0
tensorflow-model-optimization==0.7.5
termcolor==2.4.0
tf-nightly==2.16.0.dev20240129
tf_keras-nightly==2.16.0.dev2024012910
typeguard==2.13.3
typing_extensions==4.9.0
urllib3==2.1.0
virtualenv==20.25.0
Werkzeug==3.0.1
wrapt==1.14.1
zipp==3.17.0`

Since tf_nightly is updated with tf_HEAD so I can't use python3.6 with pip install the tf_nightly to reproduce the experiment. Does anyone know what I need to do to get this code working?

**Comment by rybakov** [comment]
kws lib works at HEAD of tensorflow; tensorflow_addons and tensorflow_model_optimization. Could you create a fresh virtualenv and install all of these with nightly versions?

**Comment by leehucheng** [comment]
@rybakov thanks for your advice. However, the previous logs are the result of creating a fresh virtualenv with these nightly version. I'm not sure if there's any other dependency that I need to handle.

**Comment by kismeter** [comment]
@rybakov kms lib not working at currently latest nightly version, would you help solve it

**Comment by vdhanraj** [comment]
@rybakov I'm also finding that the kws library doesn't work on the available versions of tf-nightly, regardless of whatever replacements I can find for deprecated code, the code crashes (I thought it didn't before because it was training successfully, but it crashed after the training part). Can you help update the code so that it works with the current version of tf-nightly?
