### ISSUE TITLE
TCC: images_to_tfrecords.py on Penn Action dataset

### ISSUE THREAD

**Issue by arjung128** [google-research/google-research#197]
I am trying to reproduce the TCC results on the Penn Action dataset. While scripts have been provided for the Pouring dataset, they have not been provided for the Penn Action dataset. 

To be able to train on the Penn Action dataset, I downloaded the dataset and then tried running images_to_tfrecords.py. However, I get the following error:

```
2020-02-08 23:00:23.276804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "images_to_tfrecords.py", line 201, in <module>
    app.run(main)
  File "/home/arjung2/.conda/envs/tcc/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/arjung2/.conda/envs/tcc/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "images_to_tfrecords.py", line 197, in main
    FLAGS.expected_segments)
  File "images_to_tfrecords.py", line 188, in create_tfrecords
    FLAGS.action_label, frame_labels)
  File "../../tcc/dataset_preparation/dataset_utils.py", line 111, in write_seqs_to_tfrecords
    frame_labels_string=frame_labels_string)
  File "../../tcc/dataset_preparation/dataset_utils.py", line 80, in get_example
    context_features_dict = {'name': bytes_feature([name]),
  File "../../tcc/dataset_preparation/dataset_utils.py", line 39, in <lambda>
    bytes_feature = lambda v: feature(bytes_list=tf.train.BytesList(value=v))
TypeError: '1579' has type str, but expected one of: bytes
```

Interestingly, when I run the code multiple times, I get different numbers in the last line -- it is not deterministic. 

Any ideas about what might be going on? Thanks!

**Comment by yangsen228** [comment]
You need to add "name = name.encode()" before the line 80 in dataset_utils.py
