### ISSUE TITLE
AttributeError: 'jaxlib.xla_extension.ArrayImpl' object has no attribute 'split'

### ISSUE THREAD

**Issue by CultureAddiction** [google-research/google-research#2140]
I met this problem while building your demo through readme.

>  `(merf) gpuadmin@sg6:~/YBS/merf$ ./train.sh 
> 2024-07-10 10:11:11.173861: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
> 2024-07-10 10:11:11.194337: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
> 2024-07-10 10:11:11.194385: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> 2024-07-10 10:11:11.934812: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> 2024-07-10 10:11:13.328916: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> I0710 10:11:13.459211 140330885563328 xla_bridge.py:889] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
> I0710 10:11:13.460933 140330885563328 xla_bridge.py:889] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
> /home/gpuadmin/.miniconda3/envs/merf/lib/python3.9/site-packages/jax/_src/xla_bridge.py:1167: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
>   warnings.warn(
> Loading from COLMAP
> Warning: image_path not found for reconstruction
> Loading from COLMAP
> Warning: image_path not found for reconstruction
> 2024-07-10 10:11:25.929010: W external/xla/xla/service/gpu/nvptx_compiler.cc:765] The NVIDIA driver's CUDA version is 12.1 which is older than the ptxas CUDA version (12.5.82). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
> jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/gpuadmin/YBS/merf/train.py", line 562, in <module>
>     app.run(main)
>   File "/home/gpuadmin/.miniconda3/envs/merf/lib/python3.9/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/home/gpuadmin/.miniconda3/envs/merf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/home/gpuadmin/YBS/merf/train.py", line 95, in main
>     _, state, _, _, _ = train_utils.setup_model(
>   File "/home/gpuadmin/YBS/merf/internal/train_utils.py", line 398, in setup_model
>     model, variables = models.construct_model(rng, temp_rays, config)
>   File "/home/gpuadmin/YBS/merf/internal/models.py", line 358, in construct_model
>     init_variables = model.init(
>   File "/home/gpuadmin/YBS/merf/internal/models.py", line 300, in __call__
>     features, density = query_representation(
>   File "/home/gpuadmin/YBS/merf/internal/models.py", line 182, in query_representation
>     features = grid_utils.interpolate_based_on_local_coordinates(
>   File "/home/gpuadmin/YBS/merf/internal/grid_utils.py", line 175, in interpolate_based_on_local_coordinates
>     sparse_grid_y, y = y.split([8], axis=1)
> AttributeError: 'jaxlib.xla_extension.ArrayImpl' object has no attribute 'split'`

My environment:

> | NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
> |   0  NVIDIA GeForce RTX 2080 Ti      Off| 00000000:3B:00.0 Off |                  N/A |

I checked if this is the error occured by CUDA error, but seems not.

I wonder why i am getting "Could not find TensorRT" error. I installed TensorRT as well. 

> >>> import tensorrt
>>> print(tensorrt.__version__)
10.2.0.post1
>>> assert tensorrt.Builder(tensorrt.Logger())
[07/10/2024-10:07:21] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading

Why am i getting no split error?

**Comment by nfyfamr** [comment]
Hi @creiser , I ran into the same error. Could you share your brilliant idea with us?
