### ISSUE TITLE
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 28 (FlexBatchMatMul) failed to prepare.

### ISSUE THREAD

**Issue by fmbao** [google-research/google-research#220]
Hi big bro
When I run kws_streaming.model_train_eval.py by **CNN model** .It happend the error.
Environment:
Ubuntu 18.0.4
Tensorflow 2.1.0

Skipping registering GPU devices...
2020-03-13 15:24:52.786265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 15:24:52.786269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-03-13 15:24:52.786273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-03-13 15:24:53.758005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 15:24:53.758030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      
Traceback (most recent call last):
  File "/home/mi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mi/ASR/google-research/kws_streaming/train/model_train_eval.py", line 548, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/mi/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mi/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/mi/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/mi/ASR/google-research/kws_streaming/train/model_train_eval.py", line 185, in main
    test.tflite_non_stream_model_accuracy(flags, folder, fname)
  File "/home/mi/ASR/google-research/kws_streaming/train/test.py", line 453, in tflite_non_stream_model_accuracy
    interpreter.invoke()
  File "/home/mi/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 493, in invoke
    self._interpreter.Invoke()
  File "/home/mi/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 113, in Invoke
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_Invoke(self)
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 28 (FlexBatchMatMul) failed to prepare.

**Comment by fmbao** [comment]
顶 顶 顶

**Comment by fmbao** [comment]
顶顶顶

**Comment by fmbao** [comment]
Now I meet another error when i update  TF to 2.2.0
RuntimeError: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (17920 != 16896)Node number 35 (RESHAPE) failed to prepare.

**Comment by fmbao** [comment]
When I use att_rnn .Another error happend
ValueError: slice index 24 of dimension 1 out of bounds. for '{{node streaming/tf_op_layer_strided_slice/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, _cloned=true, begin_mask=5, ellipsis_mask=0, end_mask=5, new_axis_mask=0, shrink_axis_mask=2](streaming/bidirectional_1/concat, streaming/tf_op_layer_strided_slice/strided_slice/stack, streaming/tf_op_layer_strided_slice/strided_slice/stack_1, streaming/tf_op_layer_strided_slice/strided_slice/stack_2)' with input shapes: [1,1,128], [3], [3], [3] and with computed input tensors: input[1] = <0 24 0>, input[2] = <0 25 0>, input[3] = <1 1 1>.

**Comment by rybakov** [comment]
Hi fmbao,

Sorry for delay in my reply (I did not receive an issue notification).

Please run below script and let me know if cnn model fails:
cd /tmp/kws_streaming
virtualenv --system-site-packages -p python3 ./venv3
source ./venv3/bin/activate
pip install tensorflow==2.1.0-rc1

// location of kws_streaming
KWS_PATH=/tmp/kws_streaming

// location of unpacked https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz
DATA_PATH=$KWS_PATH/data2

// location of unpacked https://storage.googleapis.com/kws_models/models2.zip
MODELS_PATH=$KWS_PATH/models2

python -m kws_streaming.train.model_train_eval \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/cnn/ \
--mel_upper_edge_hertz 7000 \
--how_many_training_steps 10000,10000,10000 \
--learning_rate 0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 40 \
--dct_num_features 20 \
--resample 0.15 \
--alsologtostderr \
--train 0 \
cnn \
--cnn_filters '64,64,64,64,128,64,128' \
--cnn_kernel_size '(3,3),(5,3),(5,3),(5,3),(5,2),(5,1),(10,1)' \
--cnn_act "'relu','relu','relu','relu','relu','relu','relu'" \
--cnn_dilation_rate '(1,1),(1,1),(2,1),(1,1),(2,1),(1,1),(2,1)' \
--cnn_strides '(1,1),(1,1),(1,1),(1,1),(1,1),(1,1),(1,1)' \
--dropout1 0.5 \
--units2 '128,256' \
--act2 "'linear','relu'" 

You should observe something like:
...
TF Final test accuracy on non stream model = 95.10% (N=4800)
...
tflite Final test accuracy, non stream model = 95.03% (N=4890)
etc

Before running above script, I would also try
export CUDA_VISIBLE_DEVICES=-1
to validate that issue is related to running TFLite on CPU or GPU.

Best,
Oleg.

**Comment by rybakov** [comment]
Hi fmbao,

Please run below script with attention rnn:
cd /tmp/kws_streaming
virtualenv --system-site-packages -p python3 ./venv3
source ./venv3/bin/activate
pip install tensorflow==2.1.0-rc1

// location of kws_streaming
KWS_PATH=/tmp/kws_streaming

// location of unpacked https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz
DATA_PATH=$KWS_PATH/data2

// location of unpacked https://storage.googleapis.com/kws_models/models2.zip
MODELS_PATH=$KWS_PATH/models2
python -m kws_streaming.train.model_train_eval \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/att_rnn/ \
--mel_upper_edge_hertz 7000 \
--how_many_training_steps 10000,10000,10000 \
--learning_rate 0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 40 \
--dct_num_features 20 \
--resample 0.15 \
--alsologtostderr \
--train 0 \
att_rnn \
--cnn_filters '10,1' \
--cnn_kernel_size '(5,1),(5,1)' \
--cnn_act "'relu','relu'" \
--cnn_dilation_rate '(1,1),(1,1)' \
--cnn_strides '(1,1),(1,1)' \
--rnn_layers 2 \
--rnn_type 'gru' \
--rnn_units 128 \
--dropout1 0.1 \
--units2 '64,32' \
--act2 "'relu','linear'"

You should observe:
TF Final test accuracy on non stream model = 96.94% (N=4800)
TF Final test accuracy on non stream model = 96.73% (N=4800)
...
tflite test accuracy, non stream model = 96.94% 4800 out of 4890
tflite Final test accuracy, non stream model = 96.89% (N=4890)
...
FAILED to run TF streaming: slice index 24 of dimension 1 out of bounds. for 'streaming/tf_op_layer_strided_slice/strided_slice' (op: 'StridedSlice') with input shapes: [1,1,256], [3], [3], [3] and with computed input tensors: input[1] = <0 24 0>, input[2] = <0 25 0>, input[3] = <1 1 1>.


Attention RNN model is non streamable (because it uses bi-directional RNN) that is why it fails in streaming inference evaluation step with messages:
FAILED to run TF streaming: slice index 24
FAILED to convert to mode STREAM_EXTERNAL_STATE_INFERENCE, tflite:
FAILED to run TFLite streaming

This script kws_streaming.train.model_train_eval does several things:
1 Can train a model [Ok]
2 Evaluate TF model in non streaming mode [Ok] 
3 Convert non streaming TF model to non streaming TFLite and evaluate it [Ok]
4 Convert non streaming TF to streaming TF [Will Fail because model is not streamable]
5 Convert non streaming TF to streaming TFLite [Will Fail because model is not streamable]

I will disable evaluation of non streamable models in streaming mode, so there will be no confusion in log messages.

Best,
Oleg.

**Comment by rybakov** [comment]
Hi fmbao,

It is fixed, please confirm and close the ticket.

Best,
Oleg.
