### ISSUE TITLE
Seq2ACT: TensorFlow version conflict despite specifying 1.15 in requirements.txt

### ISSUE THREAD

**Issue by XinrunXu** [google-research/google-research#2231]
I'm encountering a TensorFlow version conflict while trying to run run.sh. My requirements.txt file clearly specifies tensorflow==1.15, and I have confirmed that TensorFlow 1.15 is installed. However, upon running run.sh, I receive an error message stating that TensorFlow is not installed and instructing me to install TensorFlow >= 2.1.0.

## To Reproduce
Install dependencies according to requirements.txt, including tensorflow==1.15.
Run run.sh.
Console show:

***************************************************************
Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TFDS. This allows you to choose to install either `tf-nightly` or `tensorflow`. Please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.
***************************************************************

Traceback (most recent call last):
  File "/root/miniconda3/envs/seq2act/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/seq2act/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share/zsp/120.92.108.176/wx/google-research/seq2act/bin/setup_test.py", line 22, in <module>
    from seq2act.bin import seq2act_train_eval
  File "/share/zsp/120.92.108.176/wx/google-research/seq2act/bin/seq2act_train_eval.py", line 26, in <module>
    from seq2act.models import seq2act_estimator
  File "/share/zsp/120.92.108.176/wx/google-research/seq2act/models/seq2act_estimator.py", line 23, in <module>
    from tensor2tensor.models import transformer
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensor2tensor/models/__init__.py", line 79, in <module>
    from tensor2tensor.models.research import moe_experiments
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensor2tensor/models/research/moe_experiments.py", line 24, in <module>
    from tensor2tensor.models import mtf_transformer2
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensor2tensor/models/mtf_transformer2.py", line 23, in <module>
    from mesh_tensorflow.transformer import moe
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/mesh_tensorflow/transformer/__init__.py", line 23, in <module>
    import mesh_tensorflow.transformer.dataset
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/mesh_tensorflow/transformer/dataset.py", line 94, in <module>
    import tensorflow_datasets as tfds
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/__init__.py", line 38, in <module>
    from tensorflow_datasets.core.load import DatasetCollectionLoader
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/load.py", line 43, in <module>
    from tensorflow_datasets.core.dataset_builders import huggingface_dataset_builder  # pylint:disable=unused-import
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builders/__init__.py", line 21, in <module>
    from tensorflow_datasets.core.dataset_builders.conll.conll_dataset_builder import ConllBuilderConfig
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builders/conll/__init__.py", line 20, in <module>
    from tensorflow_datasets.core.dataset_builders.conll.conll_dataset_builder_utils import *
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builders/conll/conll_dataset_builder_utils.py", line 136, in <module>
    "tokens": Sequence(Text()),
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/features/text_feature.py", line 77, in __init__
    doc=doc,
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/features/tensor_feature.py", line 96, in __init__
    self._dtype = dtype_utils.cast_to_numpy(dtype)
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/utils/dtype_utils.py", line 41, in cast_to_numpy
    if tf_already_loaded and isinstance(dtype, tf.dtypes.DType):
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/utils/lazy_imports_utils.py", line 79, in __getattr__
    raise exception
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/utils/lazy_imports_utils.py", line 74, in __getattr__
    module_name=self.module_name,
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/utils/lazy_imports_utils.py", line 185, in tf_success_callback
    ensure_tf_version(kwargs["module"])
  File "/share/zsp/120.92.108.176/wx/google-research/lib/python3.7/site-packages/tensorflow_datasets/core/tf_compat.py", line 51, in ensure_tf_version
    "This version of TensorFlow Datasets requires TensorFlow "
ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.

**Comment by Eryn-Y** [comment]
I'm struggling with the same issue, did you happen to find a workaround?
