### ISSUE TITLE
instruction_following_eval: Demo command not working (data version mismatch)

### ISSUE THREAD

**Issue by gabegrand** [google-research/google-research#2259]
The demo command for IFEval is no longer working. @lehougoogle this appears to be due to a similar data version mismatch as in https://github.com/google-research/google-research/issues/1856.
```
python3 -m instruction_following_eval.evaluation_main \
  --input_data=./instruction_following_eval/data/input_data.jsonl \
  --input_response_data=./instruction_following_eval/data/input_response_data_gpt4_20231107_145030.jsonl \
  --output_dir=./instruction_following_eval/data/

I1011 17:22:26.360844 140693496852480 evaluation_main.py:256] Generating eval_results_strict...
Traceback (most recent call last):
  File "<python_lib>/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<python_lib>/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<project_dir>/evaluation_main.py", line 277, in <module>
    app.run(main)
  File "<venv_dir>/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "<venv_dir>/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "<project_dir>/evaluation_main.py", line 259, in main
    outputs.append(func(inp, prompt_to_response))
  File "<project_dir>/evaluation_main.py", line 101, in test_instruction_following_strict
    response = prompt_to_response[inp.prompt]
KeyError: 'What is inside Shinto shrines? Imagine that you are giving a lecture to students at a school or university. Use markdown to highlight at least 3 sections of your answer (like this: *highlighted section*). Your answer must also contain at least 3 placeholders (an example of a placeholder is [address]).'
```

Closer inspection shows differences in args used in the prompts between the input and response files.

```
<input_data.jsonl>
What is inside Shinto shrines? Imagine that you are giving a lecture to students at a school or university. Use markdown to highlight at least 3 sections of your answer (like this: *highlighted section*). Your answer must also contain at least 3 placeholders (an example of a placeholder is [address]).

<input_response_data_gpt4_20231107_145030.jsonl>
What is inside Shinto shrines? Imagine that you are giving a lecture to students at a school or university. Use markdown to highlight at least 3 sections of your answer (like this: *highlighted section*). Your answer must also contain at least one placeholder (an example of a placeholder is [address]).
```

It would be nice if the files could be updated with the correct data versions!

**Comment by zswuser** [comment]
I also encountered this error just now. Thank you for your question, which helped me quickly identify the issue!

**Comment by DengNingyuan** [comment]
KeyError: 'What is inside Shinto shrines?

**Comment by Leili** [comment]
Any suggestions on how to resolve the above error?

**Comment by hijkzzz** [comment]
Any suggestions on how to resolve the above error?
