### ISSUE TITLE
NameError: name 'flags' is not defined

### ISSUE THREAD

**Issue by gautham-c** [google-research/google-research#2263]
I tried `bash graph_embedding/dmon/run.sh`
Issue, i'm facing 
```
+ python -m graph_embedding.dmon.train --epochs=2 --graph_path=graph_embedding/dmon/data/cora.npz
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/gauthamc/Desktop/Research/GCN/Dmon/google-research/graph_embedding/dmon/train.py", line 46, in <module>
    FLAGS = flags.FLAGS
            ^^^^^
NameError: name 'flags' is not defined
```

**Comment by pankaj-chowdary** [comment]
Problem could be because of multiple python versions(the xcode version of python) might be interfering with the version that you are working with.
I had the same problem on my Macbook M4, but when I started working on my windows, it worked just fine!

**Comment by moh1tt** [comment]
I think the issue is from a version of python. Try installing or checking the version of python installed and rerunning it.
