### ISSUE TITLE
It seems to have problems when I run the #run_pretraining.py#

### ISSUE THREAD

**Issue by luchenyao** [google-research/google-research#274]
Hello, how can I solve this problem:

`Traceback (most recent call last):
  File "run_pretraining.py", line 983, in <module>
    tf.app.run()
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 863, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_distill_steps)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/home/lcy/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2987, in _call_input_fn
    return input_fn(**kwargs)
  File "run_pretraining.py", line 747, in input_fn
    deterministic=(not is_training))
TypeError: interleave() got an unexpected keyword argument 'deterministic'
`
**The requirement.txt says I need to install tensorflow 1.15 but deterministic is an argument of TF 2.x**

**Comment by zaidalyafeai** [comment]
@luchenyao have you resolved that issue ?

**Comment by sercretalphabets** [comment]
did you resolve this problem?

**Comment by zaidalyafeai** [comment]
@sercretalphabets removing `deterministic` solves the problem.
