### ISSUE TITLE
Temporal Fusion Transformers ( tft ) AttributeError: module 'tensorflow' has no attribute 'ConfigProto'  incompatibility with tf 2.x

### ISSUE THREAD

**Issue by SachitNayak** [google-research/google-research#284]
I encountered the following error when running a sample program of Temporal Fusion Transformers (tft) see [here](https://aihub.cloud.google.com/u/0/p/products%2F9f39ad8d-ad81-4fd9-8238-5186d36db2ec)

Specifically this line seems to cause it:

`import tensorflow as tf
from libs.tft_model import TemporalFusionTransformer

# Specify GPU usage
tf_config = utils.get_default_tensorflow_config(tf_device="gpu", gpu_id=0)`

and the stacktrace is:
`Selecting GPU ID=0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-9367d03d4948> in <module>()
      3 
      4 # Specify GPU usage
----> 5 tf_config = utils.get_default_tensorflow_config(tf_device="gpu", gpu_id=0)
      6 tf.reset_default_graph()
      7 with tf.Graph().as_default(), tf.Session(config=tf_config) as sess:

/content/repo/tft/libs/utils.py in get_default_tensorflow_config(tf_device, gpu_id)
    151     print('Selecting GPU ID={}'.format(gpu_id))
    152 
--> 153     tf_config = tf.ConfigProto(log_device_placement=False)
    154     tf_config.gpu_options.allow_growth = True
    155 

AttributeError: module 'tensorflow' has no attribute 'ConfigProto' `

According to my understanding this is an issue due to incompatibility with tensorflow 2.x

I haven't yet tried the stackoverflow workaround mentioned [here](https://stackoverflow.com/questions/56127592/attributeerror-module-tensorflow-has-no-attribute-configproto)

Linking a related issue discussing migration to TF2 #260 

PS: I could work on this issue if its assigned to me - just migrating the ConfigProto part in the tft/libs/utils.py file ( not possibly migrating entire tft codebase to TF2)

**Comment by Ubikas** [comment]
Hi, yes you are right. Don't know why, but 10 days ago tensorflow.compat.v1 was changed to tensorflow. You have to change it back in utils.py and tft_model.py

**Comment by SachitNayak** [comment]
Yeah I noticed that Pull Request merge too! only 2 lines seemed to have been changed in that merge.
However, for now I'm using TF 1.14 and things run fine.

**Comment by Ubikas** [comment]
@SachitNayak, it's out of topic, but maybe do you know how to make it multi gpu by chance?

**Comment by SachitNayak** [comment]
@Ubikas I think there is a multi (distributed) GPU version of the hyperamater tuning code available in the libs/hyperparam_opt.py file. I have only 1 GPU, so I train on that. If you are asking me if I could make the training code to run on multiple GPUs, to be frank, I really don't know how to do that.

**Comment by Ubikas** [comment]
ye, somehow I missed it, never the less it is like:

> 1) HyperparamOptManager used for optimisation on a single machine/GPU.
> 2) DistributedHyperparamOptManager for multiple GPUs on different machines.

while I need multi gpu on one machine. Anyway, @SachitNayak,  thanks for pointing out.

**Comment by SachitNayak** [comment]
Sure, no problem...

**Comment by lorrp1** [comment]
Hello, im trying to run tft on colab, i have tried with tensorflow1.14 but now im getting this error:

> Normalised Quantile Loss for Test Data: P50=0.5706422806731868, P90=2.028424442640064
> Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f6b95a14128>>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1473, in __del__
>     self._session._session, self._handle)
> tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')
> Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f6b9597bd30>>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1473, in __del__
>     self._session._session, self._handle)
> tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')

**Comment by shathaa1983** [comment]
I have the same issue, any good solution?
