### ISSUE TITLE
AttributeError: 'function' object has no attribute 'resampler'

### ISSUE THREAD

**Issue by lz2004xxw** [google-research/google-research#285]
I  just type 
"python -m depth_from_video_in_the_wild.train \
  --data_dir=depth_from_video_in_the_wild/data_example \
  --checkpoint_dir=/tmp/my_experiment --train_steps=1"
 for test.

following err:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/train.py", line 231, in <module>
    app.run(main)
  File "/home/lvzhen/py351/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/lvzhen/py351/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/train.py", line 147, in main
    input_file=FLAGS.input_file)
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/model.py", line 92, in __init__
    self._build_train_graph()
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/model.py", line 114, in _build_train_graph
    self._build_loss()
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/model.py", line 301, in _build_loss
    trans, inv_rot, inv_trans), i, j)
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/consistency_losses.py", line 209, in rgbd_and_motion_consistency_loss
    frame2depth, frame2rgb)
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/consistency_losses.py", line 65, in rgbd_consistency_loss
    frame2depth_resampled = _resample_depth(frame2depth, pixel_xy)
  File "/home/lvzhen/depth/depth_from_video_in_the_wild/consistency_losses.py", line 289, in _resample_depth
    result = contrib_resampler.resampler.resampler(depth, coordinates)
AttributeError: 'function' object has no attribute 'resampler'

tensorboard              1.14.0
tensorboard-plugin-wit   1.6.0.post3
tensorflow               1.14.0
tensorflow-datasets      3.1.0
tensorflow-estimator     1.14.0
tensorflow-gpu           1.14.0
tensorflow-graphics      1.0.0

**Comment by lz2004xxw** [comment]
I have found reason and fixed it by replacing "contrib_resampler.resampler.resampler" by "contrib_resampler.resampler"
