### ISSUE TITLE
[scann] How to save the searcher?

### ISSUE THREAD

**Issue by NadiaRom** [google-research/google-research#355]
Is there the way to save `scann.scann_ops.py.scann_ops_pybind.ScannSearcher`? Pickle solution failed (I tried joblib). 
Thank you.

**Comment by DavidWiesner** [comment]
Yes you can with the `serialize` method on the `ScannSearcher`.  Regarding to the issue #397 this is only possible with the non-tensorflow version of the searcher.

```python
# create serialize target dir
os.makedirs('.scann_artefacts/glove/', exist_ok=True)

# serialize the searcher
searcher.serialize('.scann_artefacts/glove/')

# later... restore the searcher

# load the earcher with the dataset and the artefacts dir
searcher = scann.scann_ops_pybind.load_searcher(
                normalized_dataset, 
                '.scann_artefacts/glove/')

```

**Comment by MFajcik** [comment]
@DavidWiesner which version are you using? In version 1.1, `serialize` method crashes for me even in following dummy scenario:

```
# coding: utf-8
import numpy as np
import os

import scann
import time

start = time.time()
train = np.random.rand(1_000_000, 768)

searcher = scann.scann_ops_pybind.builder(
    db=train,
    num_neighbors=10,
    distance_measure="dot_product") \
    .tree(
    num_leaves=2000,
    num_leaves_to_search=100,
    training_sample_size=250_000) \
    .score_ah(
    dimensions_per_block=2,
    anisotropic_quantization_threshold=0.2) \
    .reorder(reordering_num_neighbors=100).build()
end = time.time()
print(f"Indexed in {(end - start) / 60} minutes!")

os.makedirs('.scann_artefacts/', exist_ok=True)
searcher.serialize(f'.scann_artefacts/serialize_test')
```

produces the output:

```
2020-10-01 11:52:06.382858: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-01 11:52:06.382881: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-10-01 11:52:18.600410: I scann/partitioning/partitioner_factory_base.cc:58] Size of sampled dataset for training partition: 249544
2020-10-01 11:55:38.117967: I ./scann/partitioning/kmeans_tree_partitioner_utils.h:89] PartitionerFactory ran in 3m19.517490462s.
Indexed in 5.038116590181986 minutes!
Traceback (most recent call last):
  File "/home/ifajcik/PycharmProjects/QA/fit_qa/scripts/pruning/scann_pruning.py", line 27, in <module>
    searcher.serialize(f'.scann_artefacts/serialize_test')
  File "/opt/anaconda3/envs/qaenv/lib/python3.6/site-packages/scann/scann_ops/py/scann_ops_pybind.py", line 56, in serialize
    self.searcher.serialize(artifacts_dir)
RuntimeError: Failed to extract SingleMachineFactoryOptions: 
```

**Comment by DavidWiesner** [comment]
@MFajcik I have used scann in version 1.0. But the problem is you will store your results in `.scann_artefacts/serialize_test` but this directory was not created yet.
```python
os.makedirs('.scann_artefacts/serialize_test', exist_ok=True)
searcher.serialize(f'.scann_artefacts/serialize_test')
```
will do the job

**Comment by stephenlagree** [comment]
I was able to serialize my model in version 1.0, but in 1.1 nothing gets saved to the serialize directory.

**Comment by srmykola** [comment]
@MFajcik Have you managed to get it working? Having the same issue, and the suggested by @DavidWiesner brings the same error.

**Comment by MFajcik** [comment]
IIRC, it was just that `serialize` expected folder name, not file name. Doing what @DavidWiesner mentioned in the last post worked for me.

**Comment by pseudonymmm** [comment]
After saving, I load the numpy searcher and then use the searched_batched method:
neighbors, distances = searcher.search_batched(data)

But it's giving me this error: 
AttributeError: 'ScannSearcher' object has no attribute 'searched_batched'

Any idea why this could be occurring? I'm loading this searcher within a particular python function, which is called by another function.

**Comment by Charlyo** [comment]
> @MFajcik I have used scann in version 1.0. But the problem is you will store your results in `.scann_artefacts/serialize_test` but this directory was not created yet.
> 
> ```python
> os.makedirs('.scann_artefacts/serialize_test', exist_ok=True)
> searcher.serialize(f'.scann_artefacts/serialize_test')
> ```
> 
> will do the job

By doing so, then can you load again the searcher. With score_ah present in the creation, it complains about a missing dataset if exact reorder is used.

**Comment by pseudonymmm** [comment]
@Charlyo Yes, I'm able to load the searcher. It gives me error in searcher.search_batched()

**Comment by Charlyo** [comment]
@pseudonymmm try to load again the [example](https://github.com/google-research/google-research/blob/master/scann/docs/example.ipynb) with any input. Are you able to load it?

**Comment by pseudonymmm** [comment]
Yes I'm able to load for this example and even the search_batched() method is working.

**Comment by pseudonymmm** [comment]
The error is only occurring when I'm using script. searcher.search_batched() method is working fine when used in a notebook. I need to use a script though. What could be the issue?

**Comment by saeideh-sh** [comment]
@DavidWiesner, I am using  ScaNN version 1.2.5. However, I am not able to save the serialized version of the searcher. I have used both numpy and tf approaches. For tf approach, I have even this error that the searcher does not have serialize_to_module().
```
record_count = normalized_dataset.shape[0]
print("start_reasercher")
start = time.time()
searcher = (
    scann.scann_ops_pybind.ScannSearche.builder(normalized_dataset, 10, "dot_product")
    .tree(
        num_leaves=record_count,
        num_leaves_to_search=record_count,
        training_sample_size=record_count,
    )
    .score_ah(2, anisotropic_quantization_threshold=0.2)
    .reorder(100)
    .build())

os.makedirs('.scann_artefacts/scann_index', exist_ok=True)
searcher.serialize(f'.scann_artefacts/scann_index')    
    
```
Inside the directory I have 'scann_assets.pbtxt' and I have this error RuntimeError: Failed reading scann_config.pb: Failed to open file .scann_artefacts/scann_index/scann_config.pb.

Any suggestion for that?

**Comment by saeideh-sh** [comment]
Update on my question: I was able to train and save ScaNN using the TensorFlow implementation available at: https://www.tensorflow.org/recommenders/examples/efficient_serving

I'd like to highlight two important notes:
1) If you are using ScaNN for document indexing, remember to normalize the embeddings before feeding them to the layer.

`normalized_dataset = embeddins_array / np.linalg.norm(embeddins_array , axis=1)[:, np.newaxis]
record_count = normalized_dataset.shape[0]
embeddings = tf.convert_to_tensor(normalized_dataset, dtype=tf.float32)        
embedding_dataset = tf.data.Dataset.from_tensor_slices(embeddings)
scann_model = tfrs.layers.factorized_top_k.ScaNN(num_reordering_candidates=record_count,
                                                   num_leaves_to_search=record_count,
                                                   distance_measure='dot_product')
scann_model.index_from_dataset(embedding_dataset.batch(32))`

2) Before saving the trained model, be sure to activate the model by making at least one inference. Otherwise, it won't save.
`scann_model(query_embedding,top_k)`

I hope this information is helpful to others! Cheers!"
