### ISSUE TITLE
problems when running bam/run_classifier.py 

### ISSUE THREAD

**Issue by SanPianWang** [google-research/google-research#36]
Hi there, a problem occured when running the bam/run_classifier.py.

Tensorflow seems to lock the `events.out.tfevents` file until the whole program end,  when execute the command `utils.rmkdir(config.checkpoints_dir)` at run_classfier.py line 271, it appears to can't be done and raise the error given below

Traceback (most recent call last):
  File "D:/bam/run_classifier.py", line 281, in <module>
    tf.app.run()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/bam/run_classifier.py", line 276, in main
    utils.rmkdir(config.checkpoints_dir)
  File "D:\bam\helpers\utils.py", line 71, in rmkdir
    rmrf(path)
  File "D:\bam\helpers\utils.py", line 60, in rmrf
    tf.gfile.DeleteRecursively(path)
  File "C:\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 563, in delete_recursively
    delete_recursively_v2(dirname)
  File "C:\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 577, in delete_recursively_v2
    pywrap_tensorflow.DeleteRecursively(compat.as_bytes(path), status)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remove a directory: bam_dir\models\debug-model\checkpoints; Directory not empty

The enviroment currently use : tensorflow-gpu 1.13.1 windows10.
However, when run this code on centos, the problem doesn't exist.
Really hope to give me some advice

**Comment by daisy-belle** [comment]
enviroment use: tf-gpu  1.12.0 , linux, python 3.6.8
there is the same error!
really hope to give me some advice ~

**Comment by Mahhos** [comment]
> Hi there, a problem occured when running the bam/run_classifier.py.
> 
> Tensorflow seems to lock the `events.out.tfevents` file until the whole program end, when execute the command `utils.rmkdir(config.checkpoints_dir)` at run_classfier.py line 271, `tf.gfile.DeleteRecursively` appears to can't be done and raise the error given below
> 
> ```
> Traceback (most recent call last):
>   File "D:/bam/run_classifier.py", line 281, in <module>
>     tf.app.run()
>   File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "D:/bam/run_classifier.py", line 276, in main
>     utils.rmkdir(config.checkpoints_dir)
>   File "D:\bam\helpers\utils.py", line 71, in rmkdir
>     rmrf(path)
>   File "D:\bam\helpers\utils.py", line 60, in rmrf
>     tf.gfile.DeleteRecursively(path)
>   File "C:\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 563, in delete_recursively
>     delete_recursively_v2(dirname)
>   File "C:\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 577, in delete_recursively_v2
>     pywrap_tensorflow.DeleteRecursively(compat.as_bytes(path), status)
>   File "C:\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remove a directory: bam_dir\models\debug-model\checkpoints; Directory not empty
> ```
> 
> The enviroment currently use : tensorflow-gpu 1.13.1 windows10.
> However, when run this code on centos, the problem doesn't exist.
> Really hope to give me some advice

Following the steps in the repo, I am trying to run command` python -m bam.run_classifier debug-model $BAM_DIR '{"debug": true}'` as a minimal test. However, below line of code, raise `Extra data: line 1 column 5 (char 4) error`. Do you have any idea what should be the root cause? I tried to run other commands, still, this line raises an issue with the JSON.

Line raining the error:
`\bam\run_classifier.py", line 258, in main config = configure.Config(topdir, model_name, **json.loads(hparams))`

Error:
`raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)`
