### ISSUE TITLE
[scann] Error: Reason: image not found

### ISSUE THREAD

**Issue by theUnkownName** [google-research/google-research#363]
I installed by source and it was successful after I did this [fix](https://github.com/google-research/google-research/issues/342) but it seems that is not finding scann and when I run `python -c "import scann"` it shows me this error

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/scann/__init__.py", line 1, in <module>
    from scann.scann_ops.py.scann_builder import ScannBuilder
  File "/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/scann/scann_ops/py/scann_builder.py", line 17, in <module>
    from scann.scann_ops.py import scann_ops
  File "/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/scann/scann_ops/py/scann_ops.py", line 25, in <module>
    "cc/_scann_ops.so"))
  File "/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/scann/scann_ops/cc/_scann_ops.so, 6): image not found
`

Any ideas on what can this be?  I'm using Mac Catalina 10.15.6

Thanks a lot!

**Comment by theUnkownName** [comment]
Never mind, the problem was during installation.

For mac I needed to change all `#include <hash_set>`


```
 #if defined __GNUC__ || defined __APPLE__
#include <ext/hash_set>
#else
#include <hash_set>
#endif
```

**Comment by eugeneyan** [comment]
Were you able to import and use scann sucessfully? After applying you fixes, I still faced the issues below both Python 3.7.9 and Python 3.8.6.

```>>> import scann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/__init__.py", line 3, in <module>
    from scann.scann_ops.py import scann_ops_pybind
  File "/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/py/scann_ops_pybind.py", line 30, in <module>
    import scann_pybind
ImportError: dlopen(/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/cc/python/scann_pybind.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/cc/python/scann_pybind.so
  Expected in: flat namespace
 in /Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/cc/python/scann_pybind.so
```

With Python 3.6.12 I get this issue:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.6/site-packages/scann/__init__.py", line 3, in <module>
    from scann.scann_ops.py import scann_ops_pybind
  File "/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.6/site-packages/scann/scann_ops/py/scann_ops_pybind.py", line 30, in <module>
    import scann_pybind
ImportError: dlopen(/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.6/site-packages/scann/scann_ops/cc/python/scann_pybind.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.6/site-packages/scann/scann_ops/cc/python/scann_pybind.so
  Expected in: flat namespace
 in /Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.6/site-packages/scann/scann_ops/cc/python/scann_pybind.so```
