### ISSUE TITLE
bam/run_classifier.py model always load distill_outputs from _train_predictions_1.pkl

### ISSUE THREAD

**Issue by SanPianWang** [google-research/google-research#37]
I was trying to train a BAM model using the command like `python -m bam.run_classifier rte-mrpc-bam-model $BAM_DIR '{"task_names": ["rte", "mrpc"], "distill": true, "teachers": {"rte": "rte-model", "mrpc": "mrpc-model"}}'` given in the Readme.md，an error occured like:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/yirongli/Desktop/bam/run_classifier.py", line 281, in <module>
    tf.app.run()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/Users/yirongli/Desktop/bam/run_classifier.py", line 274, in main
    model_runner.write_outputs([task], trial, split)
  File "C:/Users/yirongli/Desktop/bam/run_classifier.py", line 196, in write_outputs
    distill_input_fn, _, _ = self._preprocessor.prepare_predict(tasks, split)
  File "C:\Users\yirongli\Desktop\bam\data\preprocessing.py", line 69, in prepare_predict
    return self._serialize_dataset(tasks, False, split)
  File "C:\Users\yirongli\Desktop\bam\data\preprocessing.py", line 108, in _serialize_dataset
    self.serialize_examples(examples, is_training, tfrecords_path)
  File "C:\Users\yirongli\Desktop\bam\data\preprocessing.py", line 127, in serialize_examples
    tf_example = self._example_to_tf_example(example, is_training)
  File "C:\Users\yirongli\Desktop\bam\data\preprocessing.py", line 136, in _example_to_tf_example
    example, is_training))
  File "C:\Users\yirongli\Desktop\bam\task_specific\classification\classification_tasks.py", line 136, in featurize
    self._distill_inputs[eid])
KeyError: 2490
```
When I tried to figure out, i found that in `configure.py` line 131, model always load distill_outputs from _train_predictions_1.pkl no matter the student model requiring training or testing prediction by teacher model in `run_classifier.py` line 269. 
So it obviously goes wrong when get the testing prediction, hope to fix it

**Comment by clarkkev** [comment]
I don't see a bug. Line 131 loads from `{$BAM_DIR}/models/{teachers[task]}/output/{task}_train_predictions_1.pkl`. Therefore it should work as long as you have the files 
```
$BAM_DIR/models/mrpc-model/outputs/mrpc_train_predictions_1.pkl
$BAM_DIR/models/rte-model/outputs/rte_train_predictions_1.pkl
```
Based on the error message, it looks like the predictions file is present but incorrect in some way. Perhaps you trained the single-task models with {"debug": True} and are now training in non-debug-mode? Debug mode uses a tiny train set, so the written-out predictions won't cover the full train set.

**Comment by SanPianWang** [comment]
Thanks for your reply, after another trying, it fixed.
But i wonder that when writting the test outputs in `run_classifier.py` Line 269, the distill_input perhaps should be loaded from the corresponding files like: `{$BAM_DIR}/models/{teachers[task]}/output/{task}_test_predictions_1.pkl`? Due to the testing examples are pickling from the `dev.tsv`.
Is there any mismatch between the testing examples and distill inputs during the prediction?

**Comment by clarkkev** [comment]
Distillation is only used during training, not at test time. So although we write out the test predictions because they might be useful for evaluation or error analysis, they are never needed for training a BAM model.

**Comment by SanPianWang** [comment]
Thanks for the explanation

**Comment by Mahhos** [comment]
> Thanks for your reply, after another trying, it fixed.
> But i wonder that when writting the test outputs in `run_classifier.py` Line 269, the distill_input perhaps should be loaded from the corresponding files like: `{$BAM_DIR}/models/{teachers[task]}/output/{task}_test_predictions_1.pkl`? Due to the testing examples are pickling from the `test.tsv`
> Is there any mismatch between the testing examples and distill inputs during the prediction?

May I know how you fix this? I am running BAM, and on one of my datasets, I am getting key_error and I am not sure why.
