### ISSUE TITLE
flag --vocab_file=None: Flag --vocab_file must have a value other than None.

### ISSUE THREAD

**Issue by tungxd96** [google-research/google-research#405]
Traceback (most recent call last):
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/tungdinh/CSProjects/UW/Capstone/Research/google-research/goemotions/bert_classifier.py", line 1037, in <module>
    tf.compat.v1.app.run()
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/absl/app.py", line 293, in run
    flags_parser,
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/absl/app.py", line 362, in _run_init
    flags_parser=flags_parser,
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/absl/app.py", line 212, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tensorflow_core/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 636, in __call__
    self._assert_all_validators()
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 510, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/Users/tungdinh/.pyenv/versions/3.6.8/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 531, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --vocab_file=None: Flag --vocab_file must have a value other than None.

I'm running this program via this repo: https://github.com/tungxd96/google-research.git
First resolved error so far is to replace tensorflow v2 to tensorflow v1. Next, I'm receiving this error while running "python -m goemotions.bert_classifier". I found this vocab_file is assigned to None instead of a directory pointing to the vocabulary file. I can't find any vocabulary file in google-research/goemotions/data. Am I missing any important files so far besides downloading 3 csv files in full_datasets? Has someone faced this issue before? Please show me how to solve it. Thank you.

**Comment by AishwaryaAllada** [comment]
I am getting the same error. I replaced tf v2 to v1 and while running "extract_features.py", I am getting the same error.

:(

**Comment by krin-san** [comment]
First step of setup instructions in README file says to "Download the pre-trained BERT model from here and unzip them inside the bert directory". What there isn't said is that flag definitions has to be manually set to reflect path and file names of the downloaded files.

I faced the same issue with `bert_classifier.py` (PWD in `goemotions` folder) and here's changes I've added to make it working: 
```diff
-from goemotions.bert import modeling
-from goemotions.bert import optimization
-from goemotions.bert import tokenization
+from bert import modeling
+from bert import optimization
+from bert import tokenization
...
-flags.DEFINE_string("emotion_file", "goemotions/data/emotions.txt",
+flags.DEFINE_string("emotion_file", "data/emotions.txt",
...
-    "data_dir", "goemotions/data",
+    "data_dir", "data",
...
-    "bert_config_file", None,
+    "bert_config_file", 'bert/bert_config.json',
...
-flags.DEFINE_string("vocab_file", None,
+flags.DEFINE_string("vocab_file", 'bert/vocab.txt',
...
-    "output_dir", None,
+    "output_dir", 'bert',
...
-flags.DEFINE_string("sentiment_file", "goemotions/data/sentiment_dict.json",
+flags.DEFINE_string("sentiment_file", "data/sentiment_dict.json",
```
Patch file: [bert_classifier.patch.txt](https://github.com/google-research/google-research/files/7265037/bert_classifier.patch.txt)
