### ISSUE TITLE
AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM

### ISSUE THREAD

**Issue by alla15747** [google-research/google-research#413]
Selecting GPU ID=0
*** Training from defined parameters for electricity ***
Loading & splitting data...
/usr/local/lib/python3.6/dist-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
Formatting train-valid-test splits.
Setting scalers with training data...
*** Loading hyperparm manager ***
*** Running calibration ***
Params Selected:
dropout_rate: 0.1
hidden_layer_size: 5
learning_rate: 0.001
minibatch_size: 64
max_gradient_norm: 0.01
num_heads: 4
stack_size: 1
model_folder: data/saved_models/electricity/fixed
WARNING:tensorflow:From /content/google-research/tft/script_train_fixed_params.py:121: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

Resetting temp folder...
*** TemporalFusionTransformer params ***
# dropout_rate = 0.1
# hidden_layer_size = 5
# learning_rate = 0.001
# max_gradient_norm = 0.01
# minibatch_size = 64
# model_folder = data/saved_models/electricity/fixed
# num_heads = 4
# stack_size = 1
# total_time_steps = 192
# num_encoder_steps = 168
# num_epochs = 1
# early_stopping_patience = 5
# multiprocessing_workers = 5
# column_definition = [('id', <DataTypes.REAL_VALUED: 0>, <InputTypes.ID: 4>), ('hours_from_start', <DataTypes.REAL_VALUED: 0>, <InputTypes.TIME: 5>), ('power_usage', <DataTypes.REAL_VALUED: 0>, <InputTypes.TARGET: 0>), ('hour', <DataTypes.REAL_VALUED: 0>, <InputTypes.KNOWN_INPUT: 2>), ('day_of_week', <DataTypes.REAL_VALUED: 0>, <InputTypes.KNOWN_INPUT: 2>), ('hours_from_start', <DataTypes.REAL_VALUED: 0>, <InputTypes.KNOWN_INPUT: 2>), ('categorical_id', <DataTypes.CATEGORICAL: 1>, <InputTypes.STATIC_INPUT: 3>)]
# input_size = 5
# output_size = 1
# category_counts = [369]
# input_obs_loc = [0]
# static_input_loc = [4]
# known_regular_inputs = [1, 2, 3]
# known_categorical_inputs = [0]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/google-research/tft/script_train_fixed_params.py", line 238, in <module>
    use_testing_mode=True)  # Change to false to use original default params
  File "/content/google-research/tft/script_train_fixed_params.py", line 124, in main
    model = ModelClass(params, use_cudnn=use_gpu)
  File "/content/google-research/tft/libs/tft_model.py", line 456, in __init__
    self.model = self.build_model()
  File "/content/google-research/tft/libs/tft_model.py", line 1006, in build_model
    = self._build_base_graph()
  File "/content/google-research/tft/libs/tft_model.py", line 929, in _build_base_graph
    = get_lstm(return_state=True)(historical_features,
  File "/content/google-research/tft/libs/tft_model.py", line 907, in get_lstm
    lstm = tf.keras.layers.CuDNNLSTM(
AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM

**Comment by r3v1** [comment]
If you are using tensorflow 2.x, you can replace `import tensorflow as tf` by `import tensorflow.compat.v1 as tf`, at least, it works for me
