### ISSUE TITLE
AttributeError: module 'tensorflow.keras.backend' has no attribute 'get_session'

### ISSUE THREAD

**Issue by alla15747** [google-research/google-research#414]
Extracting 10 samples...
Cached data "valid" updated
*** Fitting TemporalFusionTransformer ***
Getting batched_data
Using cached training data
Using cached validation data
Using keras standard fit
Train on 100 samples, validate on 10 samples
2020-10-09 07:11:36.762729: W tensorflow/c/c_api.cc:326] Operation '{name:'TemporalFusionTransformer/lstm/while' id:3156 op device:{} def:{{{node TemporalFusionTransformer/lstm/while}} = While[T=[DT_INT32, DT_INT32, DT_INT32, DT_VARIANT, DT_FLOAT, ..., DT_VARIANT, DT_VARIANT, DT_VARIANT, DT_VARIANT, DT_VARIANT], _lower_using_switch_merge=true, _num_original_outputs=45, _read_only_resource_inputs=[8, 9, 10], body=TemporalFusionTransformer_lstm_while_body_3416[], cond=TemporalFusionTransformer_lstm_while_cond_3415[], output_shapes=[[], [], [], [], [?,5], ..., [], [], [], [], []], parallel_iterations=32](TemporalFusionTransformer/lstm/while/loop_counter, TemporalFusionTransformer/lstm/while/maximum_iterations, TemporalFusionTransformer/lstm/time, TemporalFusionTransformer/lstm/TensorArrayV2_1, TemporalFusionTransformer/layer_normalization_4/add, TemporalFusionTransformer/layer_normalization_5/add, TemporalFusionTransformer/lstm/strided_slice, TemporalFusionTransformer/lstm/TensorArrayUnstack/TensorListFromTensor, TemporalFusionTransformer/lstm/lstm_cell/kernel, TemporalFusionTransformer/lstm/lstm_cell/recurrent_kernel, TemporalFusionTransformer/lstm/lstm_cell/bias, TemporalFusionTransformer/lstm/while/EmptyTensorList, TemporalFusionTransformer/lstm/while/EmptyTensorList_1, TemporalFusionTransformer/lstm/while/EmptyTensorList_2, TemporalFusionTransformer/lstm/while/EmptyTensorList_3, TemporalFusionTransformer/lstm/while/EmptyTensorList_4, TemporalFusionTransformer/lstm/while/EmptyTensorList_5, TemporalFusionTransformer/lstm/while/EmptyTensorList_6, TemporalFusionTransformer/lstm/while/EmptyTensorList_7, TemporalFusionTransformer/lstm/while/EmptyTensorList_8, TemporalFusionTransformer/lstm/while/EmptyTensorList_9, TemporalFusionTransformer/lstm/while/EmptyTensorList_10, TemporalFusionTransformer/lstm/while/EmptyTensorList_11, TemporalFusionTransformer/lstm/while/EmptyTensorList_12, TemporalFusionTransformer/lstm/while/EmptyTensorList_13, TemporalFusionTransformer/lstm/while/EmptyTensorList_14, TemporalFusionTransformer/lstm/while/EmptyTensorList_15, TemporalFusionTransformer/lstm/while/EmptyTensorList_16, TemporalFusionTransformer/lstm/while/EmptyTensorList_17, TemporalFusionTransformer/lstm/while/EmptyTensorList_18, TemporalFusionTransformer/lstm/while/EmptyTensorList_19, TemporalFusionTransformer/lstm/while/EmptyTensorList_20, TemporalFusionTransformer/lstm/while/EmptyTensorList_21, TemporalFusionTransformer/lstm/while/EmptyTensorList_22, TemporalFusionTransformer/lstm/while/EmptyTensorList_23, TemporalFusionTransformer/lstm/while/EmptyTensorList_24, TemporalFusionTransformer/lstm/while/EmptyTensorList_25, TemporalFusionTransformer/lstm/while/EmptyTensorList_26, TemporalFusionTransformer/lstm/while/EmptyTensorList_27, TemporalFusionTransformer/lstm/while/EmptyTensorList_28, TemporalFusionTransformer/lstm/while/EmptyTensorList_29, TemporalFusionTransformer/lstm/while/EmptyTensorList_30, TemporalFusionTransformer/lstm/while/EmptyTensorList_31, TemporalFusionTransformer/lstm/while/EmptyTensorList_32, TemporalFusionTransformer/lstm/while/EmptyTensorList_33)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
100/100 [==============================] - ETA: 0s - loss: 1.9711WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v1.py:2048: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
100/100 [==============================] - 3s 33ms/sample - loss: 1.9711 - val_loss: 1.5490
Cannot load from data/saved_models/electricity/fixed/tmp, skipping ...
Using cached validation data
Optimal model found, updating
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/google-research/tft/script_train_fixed_params.py", line 238, in <module>
    use_testing_mode=True)  # Change to false to use original default params
  File "/content/google-research/tft/script_train_fixed_params.py", line 136, in main
    opt_manager.update_score(params, val_loss, model)
  File "/content/google-research/tft/libs/hyperparam_opt.py", line 227, in update_score
    model.save(self.hyperparam_folder)
  File "/content/google-research/tft/libs/tft_model.py", line 1307, in save
    tf.keras.backend.get_session(),
AttributeError: module 'tensorflow.keras.backend' has no attribute 'get_session'

**Comment by zhang4ever** [comment]
use tensorflow.compat.v1.keras.backend instead if you are using tf2.x version
