### ISSUE TITLE
scann core dump when python import

### ISSUE THREAD

**Issue by lancelot1989** [google-research/google-research#430]
once python import scann, python crash & core dump with error 'Illigal instruction'. is there any problem with compablity?

system info
```
[root@k8s-new-node-2-37nir tmp]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@k8s-new-node-2-37nir tmp]# uname -a
Linux k8s-new-node-2-37nir.vclound.com 4.20.7-1.el7.elrepo.x86_64 #1 SMP Wed Feb 6 13:17:46 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@k8s-new-node-2-37nir tmp]# python3 --version
Python 3.6.0
[root@k8s-new-node-2-37nir tmp]# pip3 --version
pip 20.2.4 from /usr/local/python36/lib/python3.6/site-packages/pip (python 3.6)
```

gdb info
```
Core was generated by `python3'.
Program terminated with signal 4, Illegal instruction.
#0  0x00007fbaaf0b1c54 in InitDefaultsscc_info_FixedPoint_scann_2fproto_2fexact_5freordering_2eproto() () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 glibc-2.17-157.el7_3.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 libuuid-2.23.2-33.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 readline-6.2-11.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007fbaaf0b1c54 in InitDefaultsscc_info_FixedPoint_scann_2fproto_2fexact_5freordering_2eproto() () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
#1  0x00007fbaaf19cf23 in google::protobuf::internal::(anonymous namespace)::InitSCC_DFS(google::protobuf::internal::SCCInfoBase*) () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
#2  0x00007fbaaf19cf0f in google::protobuf::internal::(anonymous namespace)::InitSCC_DFS(google::protobuf::internal::SCCInfoBase*) () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
#3  0x00007fbaaf19cf0f in google::protobuf::internal::(anonymous namespace)::InitSCC_DFS(google::protobuf::internal::SCCInfoBase*) () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
#4  0x00007fbaaf19cdc0 in google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*) () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
#5  0x00007fbaaf0e2545 in google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*) () from /usr/local/python36/lib/python3.6/site-packages/scann/scann_ops/cc/_scann_ops.so
#6  0x00007fbaffd5b1e3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#7  0x00007fbaffd5f8f6 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#8  0x00007fbaffd5aff4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#9  0x00007fbaffd5efeb in _dl_open () from /lib64/ld-linux-x86-64.so.2
#10 0x00007fbaff92cfbb in dlopen_doit () from /lib64/libdl.so.2
#11 0x00007fbaffd5aff4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#12 0x00007fbaff92d5bd in _dlerror_run () from /lib64/libdl.so.2
#13 0x00007fbaff92d051 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#14 0x00007fbabd53d88a in tensorflow::internal::LoadLibrary(char const*, void**) () from /usr/local/python36/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#15 0x00007fbabd523af7 in tensorflow::(anonymous namespace)::PosixEnv::LoadLibrary(char const*, void**) () from /usr/local/python36/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#16 0x00007fbabd1e30b4 in tensorflow::LoadLibrary(char const*, void**, void const**, unsigned long*) () from /usr/local/python36/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#17 0x00007fbac1b811b7 in TF_LoadLibrary () from /usr/local/python36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

**Comment by mnikitin** [comment]
Same problem. 
Any updates?

**Comment by hemendra-srivastava** [comment]
+1, facing same issue (centos-7)
