### ISSUE TITLE
Uflow Train on custom dataset

### ISSUE THREAD

**Issue by lazrak-mouad** [google-research/google-research#512]
Thank you for this awesome work. 

When trying to train the UFlow network on the billiard dataset, I had the following error message : Unknown data format "custom". 
After looking at the uflow_data.py file I found no support for 'custom' dataset format on the make_train_iterator function. 

Is there a way to avoid this error ?

Finally, kindly share any tips for training Uflow on an unsupervised dataset other than 'Flying chairs', 'Sintel', 'Kitti'.

Best regards,
Mouad Lazrak.

**Comment by lazrak-mouad** [comment]
Update !!

To train on a custom dataset you need to change the format from 'custom' to 'chairs' on the flag train_on, this way the training program will call the 'make_dataset' from generic_flow_dataset.py as flow_dataset.

Please let me know if my remark is valid or not.

**Comment by AustinCStone** [comment]
Yes, what you said is correct. There is also a premade script to convert any video to a trainable dataset: https://github.com/google-research/google-research/blob/master/uflow/misc/convert_video_to_dataset.py

**Comment by lazrak-mouad** [comment]
Thank you for your response.

I've managed to train on a custom dataset and save checkpoints. Now I'm wondering if there is a way to evaluate on a custom dataset to.

**Comment by BAniys** [comment]
Thank you for your great work. I would like to know if it is possible to evaluate on a custom dataset?

**Comment by infi2021** [comment]
@lazrak-mouad Im unable to train of custom dataset with either train_on flag as custom or chairs, created the TF records using the convert_video_to_dataset.py,. Can you please let me know how you trained on your custom dataset

**Comment by infi2021** [comment]
@lazrak-mouad While training using the chairs as the train_on flag im getting this error, any help appreciated 

Layers in a Sequential model should only have a single input tensor, but we receive a <class 'list'> input: [<tf.Tensor 'pwc_flow/mul_2000:0' shape
=(1, 96, 128, 32) dtype=float32>, <tf.Tensor 'pwc_flow/add_88:0' shape=(1, 96, 128, 2) dtype=float32>]

**Comment by lazrak-mouad** [comment]
Hey, for your first question here is an alternative solution :
You need to change the line 116 on uflow_data.py file to the following : elif 'chairs' in data_format or 'custom' in data_format:
And then use the command provided in the readme to train your network.

For the second one I think you have an input shape issue. I think it's related to the way you converted your video to a dataset. I don't know if you have noticed that you should change line 81 in uflow/misc/convert_video_to_dataset.py to the following : 
convert_video(FLAGS.video_path, FLAGS.output_path). 

Also I don't understand why you have a list of two tensors as input, normally you should have a single tensor with shape (batch_size, 2, height, width, 3).

If you can share more I would be glad to help as much as I can.

**Comment by 1261847510** [comment]
i also created the TF records using the convert_video_to_dataset.py on my own video and tried training using the charis as the train_on flags, but i got this error as below, any help appreciated.

Starting training loop.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\wyx\git_repo\uflow\uflow_main.py", line 379, in <module>
    app.run(main)
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "E:\wyx\git_repo\uflow\uflow_main.py", line 338, in main
    log_update = uflow.train(
  File "E:\wyx\git_repo\uflow\uflow_net.py", line 523, in train
    for _, batch in zip(range(num_steps), data_it):
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 761, in __next__
    return self._next_internal()
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 744, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2727, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\ProgramData\Anaconda3\envs\uflow\lib\site-packages\tensorflow\python\framework\ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0 [Op:IteratorGetNext]

**Comment by n1dhi** [comment]
Hi, @lazrak-mouad  can you please tell me how to go about evaluating a model trained on custom dataset?

**Comment by zerotwotnt** [comment]
@lazrak-mouad hey,while I use the convert_video_to_dataset.py. I use a 640x368 video about 30 second and generate a document.I use it and 'chair' as the train_on flag and I get the same error with @infi2021 .like tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'list'> input: [<tf.Tensor 'pwc_flow/sequential_5/leaky_re_lu_10/LeakyRelu:0' shape=(1, 96, 128, 32) dtype=float32>, <tf.Tensor 'pwc_flow/add_13:0' shape=(1, 96, 128, 2) dtype=float32>]
Consider rewriting this model with the Functional API.
but this is a WARNING and the program can be run.I'd like to ask you about this.
