### ISSUE TITLE
Uflow train on KITTI15

### ISSUE THREAD

**Issue by Kewenjing1020** [google-research/google-research#514]
Hi, I found some small mistakes in `data_conversion_scripts/convert_KITTI_flow_to_tfrecords.py`, for example:

> line 71: flow_path = os.path.join(data_dir, FLAGS.subdir, 'flow_' + version, 

After fixing generating the KITTI15 tfrecords data, I tried to do training. In training,  
```
Restoring model from checkpoint uflow/checkpoints/kitti15.
Making eval datasets and eval functions.
Making training iterator.
Starting training loop.

Traceback (most recent call last):
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/proj/xcdhdstaff1/wenjingk/SLAM/uflow/uflow_main.py", line 379, in <module>
    app.run(main)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/proj/xcdhdstaff1/wenjingk/SLAM/uflow/uflow_main.py", line 357, in main
    uflow_plotting.print_log(log, epoch)
  File "/proj/xcdhdstaff1/wenjingk/SLAM/uflow/uflow_plotting.py", line 46, in print_log
    np.mean(log['total-loss'][-mean_over_num_steps:]))
KeyError: 'total-loss'

```
The train data loader **train_it** is empty and the training loop wasn't executed.

**Comment by yyuuliang** [comment]
I have the same error, did u resolve this ?

**Comment by AustinCStone** [comment]
I've just noticed your comment and am looking into the issue. Would you mind sharing your fix in a pull request and sharing the command you used to train?

**Comment by yyuuliang** [comment]
hi @AustinCStone 
I haven't resovled this issue. I found that if I using the dataset converted from Kitti, the data loader can't load data and the iterator train_it is empty. so the training wont start. 
I have no problem when using Sintel dataset.
