### ISSUE TITLE
[uflow] error when evaluating model on sintel

### ISSUE THREAD

**Issue by Kewenjing1020** [google-research/google-research#515]
Hi, I've used the code to train model on sintel dataset. The training is not completed and I try to do evaluation on the mediate models. I use the script: 
```
python3 -m uflow.uflow_evaluator --eval_on="sintel:uflow/data_tfrecords/sintel/test/clean" --plot_dir=uflow/plot/sinte    l --checkpoint_dir=uflow/checkpoints/sintel
```
then I get the following error:
```
I0107 17:50:51.010394 140387742058304 uflow_evaluator.py:61] New checkpoint found: uflow/checkpoints/sintel/ckpt-526
2021-01-07 17:50:51.090070: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at example_parsing_ops.cc:476 : Invalid argument: I
nconsistent number of elements for feature flow_uv: 0 vs 1
2021-01-07 17:50:51.090382: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at iterator_ops.cc:941 : Invalid argument: Inconsis
tent number of elements for feature flow_uv: 0 vs 1
         [[{{node ParseSingleSequenceExample/ParseSequenceExample/ParseSequenceExampleV2}}]]
2021-01-07 17:50:51.092987: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at example_parsing_ops.cc:476 : Invalid argument: I
nconsistent number of elements for feature flow_uv: 0 vs 1
Traceback (most recent call last):
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py", line 1897, in execution_mo
de
    yield
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 659, in _next
_internal
    output_shapes=self._flat_output_shapes)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2479, in iterat
or_get_next_sync
    _ops.raise_from_not_ok_status(e, name)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_n
ot_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inconsistent number of elements for feature flow_uv: 0 vs 1
         [[{{node ParseSingleSequenceExample/ParseSequenceExample/ParseSequenceExampleV2}}]] [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/proj/xcdhdstaff1/wenjingk/SLAM/google-research-master/uflow/uflow_evaluator.py", line 98, in <module>
    app.run(main)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/proj/xcdhdstaff1/wenjingk/SLAM/google-research-master/uflow/uflow_evaluator.py", line 92, in main
    evaluate()
  File "/proj/xcdhdstaff1/wenjingk/SLAM/google-research-master/uflow/uflow_evaluator.py", line 66, in evaluate
    eval_results = evaluate_fn(uflow)
  File "/proj/xcdhdstaff1/wenjingk/SLAM/uflow/uflow_data.py", line 277, in eval_function
    width, progress_bar, plot_dir, num_plots)
  File "/proj/xcdhdstaff1/wenjingk/SLAM/uflow/data/data_utils.py", line 222, in evaluate
    for test_batch in it:
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __nex
t__
    return self.next()
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next
_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py", line 1900, in execution_mo
de
    executor_new.wait()
  File "/scratch/workspace/wenjingk/anaconda-3.6/lib/python3.7/site-packages/tensorflow_core/python/eager/executor.py", line 67, in wait
    pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inconsistent number of elements for feature flow_uv: 0 vs 1
         [[{{node ParseSingleSequenceExample/ParseSequenceExample/ParseSequenceExampleV2}}]]

If you suspect this is an IPython 7.12.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```
I think it's strange, because when i do evaluation on Chairs, it works well.  Could you help to fix this problem?

**Comment by lazrak-mouad** [comment]
Hi,

Could you please explain how did you managed to train your network. I'm trying the following command "python -m uflow.uflow_main --train_on="chairs:uflow/video_data" --from_scratch=True  --batch_size=1 --checkpoint_dir="uflow/checkpoints" --plot_dir="uflow/plots", but no checkpoints or plots are saved.

Thnak you.

**Comment by Kewenjing1020** [comment]
> Hi,
> 
> Could you please explain how did you managed to train your network. I'm trying the following command "python -m uflow.uflow_main --train_on="chairs:uflow/video_data" --from_scratch=True --batch_size=1 --checkpoint_dir="uflow/checkpoints" --plot_dir="uflow/plots", but no checkpoints or plots are saved.
> 
> Thnak you.

Hi, I used this command `#python3 -m uflow.uflow_main --train_on="chairs:uflow/data_tfrecords/train" --plot_dir=uflow/plot --init_checkpoint_dir=uflow/checkpoints/chairs_batch1 -    -checkpoint_dir=uflow/checkpoints/chairs_test --batch_size=1`, and I do have checkpoints generated. 
Have you generate tf_record data?

**Comment by lazrak-mouad** [comment]
I tried your command but still no checkpoints saved.

As a training dataset I'm using the script "convert_video_to_dataset.py" to convert a video stream to a dataset and I think its systematicly transformed to tfRecords format.

Also, I'm training Uflow for just one epoch using flag "from_scratch=True".

This my full command !python -m uflow.uflow_main --train_on="custom:uflow/video_data" --from_scratch=True  --batch_size=1 --checkpoint_dir=uflow/checkpoints --tensorboard_logdir=uflow/plots --plot_dir=uflow/plot

I'm curious about your checkpoints size, since I'm using google colab and the memory is limited.

**Comment by ShengyeLi** [comment]
> > Hi,
> > Could you please explain how did you managed to train your network. I'm trying the following command "python -m uflow.uflow_main --train_on="chairs:uflow/video_data" --from_scratch=True --batch_size=1 --checkpoint_dir="uflow/checkpoints" --plot_dir="uflow/plots", but no checkpoints or plots are saved.
> > Thnak you.
> 
> Hi, I used this command `#python3 -m uflow.uflow_main --train_on="chairs:uflow/data_tfrecords/train" --plot_dir=uflow/plot --init_checkpoint_dir=uflow/checkpoints/chairs_batch1 - -checkpoint_dir=uflow/checkpoints/chairs_test --batch_size=1`, and I do have checkpoints generated.
> Have you generate tf_record data?

Hi, did you attempt to train on multiple GPUs?

**Comment by Kewenjing1020** [comment]
> > > Hi,
> > > Could you please explain how did you managed to train your network. I'm trying the following command "python -m uflow.uflow_main --train_on="chairs:uflow/video_data" --from_scratch=True --batch_size=1 --checkpoint_dir="uflow/checkpoints" --plot_dir="uflow/plots", but no checkpoints or plots are saved.
> > > Thnak you.
> > 
> > 
> > Hi, I used this command `#python3 -m uflow.uflow_main --train_on="chairs:uflow/data_tfrecords/train" --plot_dir=uflow/plot --init_checkpoint_dir=uflow/checkpoints/chairs_batch1 - -checkpoint_dir=uflow/checkpoints/chairs_test --batch_size=1`, and I do have checkpoints generated.
> > Have you generate tf_record data?
> 
> Hi, did you attempt to train on multiple GPUs?

No

**Comment by AustinCStone** [comment]
The Sintel test data does not include labels so you cannot evaluate on it (it is failing to find the flow_uv feature because it is not there). In our paper, in order to perform ablations and test the impact of our changes, we would train on the test data (which does not include labels) and then evaluate on the train data (which does include labels). The test data is what is actually uploaded to the evaluation server, so they keep the labels private.
