### ISSUE TITLE
[depth_and_motion_learning] Imagenet Checkpoint

### ISSUE THREAD

**Issue by LucasSloan** [google-research/google-research#589]
The README for depth_and_motion says that you should supply a checkpoint for the depth model pretrained on imagenet.  Can you release such a model checkpoint?

**Comment by yangxl-2014-fe** [comment]
The pre-trained ResNet-18 model used by struct2depth / depth_from_video_in_the_wild / depth_and_motion_learning is the same as [this](https://github.com/dalgu90/resnet-18-tensorflow.git)

```bash
git clone https://github.com/dalgu90/resnet-18-tensorflow.git
cd resnet-18-tensorflow
wget https://d2j0dndfm35trm.cloudfront.net/resnet-18.t7

# Optional if necessary:
#   pip install torchfile
#
#   edit extract_torch_t7.py:
#     import cPickle as pickle --> import pickle  # https://github.com/JuliaPy/PyCallJLD.jl/issues/6#issuecomment-421732697

python extract_torch_t7.py

# The generated:
#    ./init/
#        model.ckpt.data-00000-of-00001
#        model.ckpt.index
#        model.ckpt.meta
# could be used for training depth_and_motion_learning.
```

**Comment by LucasSloan** [comment]
FYI for anyone in the future, I also had to replace some

```
import tensorflow as tf
```

with

```
import tensorflow.compat.v1 as tf
```
in order to make everything work.

**Comment by WeihengXia0123** [comment]
Thanks for the soluton!

> The pre-trained ResNet-18 model used by struct2depth / depth_from_video_in_the_wild / depth_and_motion_learning is the same as [this](https://github.com/dalgu90/resnet-18-tensorflow.git)
> 
> ```shell
> git clone https://github.com/dalgu90/resnet-18-tensorflow.git
> cd resnet-18-tensorflow
> wget https://d2j0dndfm35trm.cloudfront.net/resnet-18.t7
> 
> # Optional if necessary:
> #   pip install torchfile
> #
> #   edit extract_torch_t7.py:
> #     import cPickle as pickle --> import pickle  # https://github.com/JuliaPy/PyCallJLD.jl/issues/6#issuecomment-421732697
> 
> python extract_torch_t7.py
> 
> # The generated:
> #    ./init/
> #        model.ckpt.data-00000-of-00001
> #        model.ckpt.index
> #        model.ckpt.meta
> # could be used for training depth_and_motion_learning.
> ```

**Comment by Tord-Zhang** [comment]
@yangxl-2014-fe Hi, thanks for your solution, but I meet a problem when initialize the model with imagenet pretrained weights, I get the error message below:
`python3 -m depth_and_motion_learning.depth_motion_field_train --model_dir=kitti_test '--param_overrides={
    "model": {
      "input": {
        "data_path": "vid2depth/KITTI_procesed/train.txt"
      }
    },
    "trainer": {
      "max_steps": 450000
      "init_ckpt": "depth_and_motion_learning/init/model.ckpt",
      "init_ckpt_type": "imagenet"
    }
  }'
2022-05-16 20:26:14.298942: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Warning: To use the exr data format, please install the OpenEXR package following the instructions detailed in the README at github.com/tensorflow/graphics.
Warning: To use the threejs_vizualization, please install the colabtools package following the instructions detailed in the README at github.com/tensorflow/graphics.
Traceback (most recent call last):
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/parameter_container.py", line 189, in parse_object
    object_or_json_or_file = json.loads(object_or_json_or_file)
  File "/home/tiger/anaconda3/envs/tf/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/tiger/anaconda3/envs/tf/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/tiger/anaconda3/envs/tf/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 7 (char 156)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/parameter_container.py", line 222, in parse_object
    f = open(object_or_json_or_file)
FileNotFoundError: [Errno 2] No such file or directory: '{\n    "model": {\n      "input": {\n        "data_path": "vid2depth/KITTI_procesed/train.txt"\n      }\n    },\n    "trainer": {\n      "max_steps": 450000\n      "init_ckpt": "depth_and_motion_learning/init/model.ckpt",\n      "init_ckpt_type": "imagenet"\n    }\n  }'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiger/anaconda3/envs/tf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tiger/anaconda3/envs/tf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/depth_motion_field_train.py", line 38, in <module>
    app.run(main)
  File "/home/tiger/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/tiger/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/depth_motion_field_train.py", line 32, in main
    training_utils.train(depth_motion_field_model.input_fn,
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/training_utils.py", line 290, in train
    params.override(FLAGS.param_overrides)
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/parameter_container.py", line 429, in override
    self._override(
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/parameter_container.py", line 470, in _override
    params_dict = parse_dict(params_dict)
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/parameter_container.py", line 266, in parse_dict
    return parse_object(dict_or_json_or_file, allow_dict=True)
  File "/mnt/bd/lq-zhangtaolucky7/dataset/AbsDepth/google-research/depth_and_motion_learning/parameter_container.py", line 247, in parse_object
    raise ValueError(message)
ValueError: Unable to parse override parameters either as a literal JSON or as a python dictionary literal or as the name of a file that exists.

GFile error: [Errno 2] No such file or directory: '{\n    "mode...

JSON parsing error: Expecting ',' delimiter: line 9 column 7 (char 156)

Python dict parsing error: invalid syntax (<unknown>, line 9)

Override parameters:
{
    "model": {
      "input": {
        "data_path": "vid2depth/KITTI_procesed/train.txt"
      }
    },
    "trainer": {
      "max_steps": 450000
      "init_ckpt": "depth_and_motion_learning/init/model.ckpt",
      "init_ckpt_type": "imagenet"
    }
  }.
Debug Info:
Expected counts of ":" (7) to be half of string delimiters: ' (0) and " (20)
Char  Count

' ==> 0
" ==> 20
{ ==> 4
} ==> 4
: ==> 7
, ==> 2`

Any idea why this happen? Thanks
