### ISSUE TITLE
About requirements.txt

### ISSUE THREAD

**Issue by hewittzgh** [google-research/google-research#631]
In my practice, I found that the package version in requirements.txt is written in xxx >= yyy format, such as 'tensorflow-probability >= 0.11.1', but it seems that pip3 installs the latest version of the package by default according to requirements.txt, which resulting in an error:  'ERROR: The version of TensorFlow requires Tensorflow version >=2.4; Detected an Installation of Version 2.3.0.'.
When I manually changed >= to == and installed the specified version of the software package, for example, tensorflow-probability==0.11.1, the error was fixed. So it is recommended to specify the minimum version in requirements.txt to avoid conflicts with the tensorflow version.

**Comment by hewittzgh** [comment]
I also found that you have modified the code about importing 'string_int_lable_map_pd2'. In label_map_util.py, line 19, 'from object_detection.protos import string_int_label_map_pb2', it does not work under my test. I still need to download object_detection and compile it with the protoc tool. Can be imported, it is recommended to compile by default and import directly by tf3d.utils.protos.

**Comment by hewittzgh** [comment]
When I was using tensroboard, I found that the 3D map under the mesh tag could not be displayed. Is the mesh plugin in the tf-nightly version? Do I  need to use the nightly version of tensorboard to display the mesh map normally?

**Comment by afathi3** [comment]
I just added an update that should fix the string_int_label_map_pb2 issue. Let me know if it still is there.
We are working on the pip install issue (sorry for the inconvenience)

**Comment by hewittzgh** [comment]
@afathi3 Sorry, your update did not work properly.This is my error message:
```
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0316 01:00:52.480308 140413338064704 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0316 01:00:52.480569 140413338064704 train.py:149] writing path is /tmp/tf3d_experiment/seg_rio_001
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/google-research-tf3d/tf3d/train.py", line 221, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/google-research-tf3d/tf3d/train.py", line 154, in main
    __import__(module_name)
  File "/google-research-tf3d/tf3d/gin_imports.py", line 25, in <module>
    from tf3d.instance_segmentation import metric as instance_segmentation_metric
  File "/google-research-tf3d/tf3d/instance_segmentation/metric.py", line 20, in <module>
    from tf3d import base_ap_metric
  File "/google-research-tf3d/tf3d/base_ap_metric.py", line 23, in <module>
    from tf3d.utils import label_map_util
  File "/google-research-tf3d/tf3d/utils/label_map_util.py", line 19, in <module>
    from tf3d.utils.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'
```
My fix: Run `protoc string_int_label_map.proto --python_out=.` under `utils/protos` folder and I can get a `string_int_label_map_pb2.py` file. The error was then fixed.

PS:  I also want to ask about the display problem of mesh in tensorboard: https://github.com/google-research/google-research/issues/631#issuecomment-799462735

**Comment by afathi3** [comment]
Thank you @hewittzgh.
We have updated the [setup](https://github.com/google-research/google-research/blob/master/tf3d/doc/setup.md) and also [Op compilation instructions](https://github.com/google-research/google-research/blob/master/tf3d/ops/README.md). Please take another look and let us know if you still have an issue.

**Comment by hewittzgh** [comment]
The error https://github.com/google-research/google-research/issues/631#issuecomment-799867859 has been fixed. Thanks!
I still haven't been able to solve the problem with the 3D image display in the TensorBoard's Mesh TAB. Here is my screenshot:
![屏幕快照 2021-03-18 上午11 45 48](https://user-images.githubusercontent.com/60736416/111570532-09b1bf80-87e0-11eb-82cd-d48a12da6c98.png)
You can see that there are empty Spaces where the image should be displayed.
This is my system environment:
> docker images: tensorflow/tensorflow:2.3.0-gpu
> nvidia-docker
Models can be trained and validated normally in my environment, but the tensorboard.mesh can not work.

**Comment by HRLTY** [comment]
Hi @hewittzgh,
if eval_val_mesh folder's event file has meaningful non empty size, I suggest debugging into this [line](https://github.com/google-research/google-research/blob/07f7097a781a4a176a78fd84c30931ab8ebf48b2/tf3d/utils/callback_utils.py#L320)'s parameters, check if they are reasonable format.
On the other hand, Tensorboard will likely crash when so many meshes(10+) are to be displayed at the same time.
Thanks.

**Comment by hewittzgh** [comment]
In my test, there was a error with the update of string_int_lable_map.proto and label_map_util.py in utils folder.The following is my error message:
```
root@c31432fd4a88:/google-research-tf3d# bash tf3d/semantic_segmentation/scripts/rio/run_eval_locally.sh
EVAL_DIR at /google-research-tf3d/tf3d_experiment/seg_rio_001...
2021-03-19 09:07:41.415679: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/google-research-tf3d/tf3d/eval.py", line 166, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/google-research-tf3d/tf3d/eval.py", line 141, in main
    __import__(module_name)
  File "/google-research-tf3d/tf3d/gin_imports.py", line 34, in <module>
    from tf3d.semantic_segmentation import metric as semantic_segmentation_metric
  File "/google-research-tf3d/tf3d/semantic_segmentation/metric.py", line 24, in <module>
    from object_detection.utils import label_map_util
  File "/google-research-tf3d/object_detection/utils/label_map_util.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "/google-research-tf3d/object_detection/protos/string_int_label_map_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x1astring_int_label_map.proto\x12\x17object_detection.protos\"\xee\x01\n\x15StringIntLabelMapItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12M\n\tkeypoints\x18\x04 \x03(\x0b\x32:.object_detection.protos.StringIntLabelMapItem.KeypointMap\x12\x14\n\x0c\x61ncestor_ids\x18\x05 \x03(\x05\x12\x16\n\x0e\x64\x65scendant_ids\x18\x06 \x03(\x05\x1a(\n\x0bKeypointMap\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\"Q\n\x11StringIntLabelMap\x12<\n\x04item\x18\x01 \x03(\x0b\x32..object_detection.protos.StringIntLabelMapItem')
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/descriptor.py", line 942, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "string_int_label_map.proto":
  string_int_label_map.proto: A file with this name is already in the pool.
```
I downloaded the object_detection module of tensorflow, compiled the proto file separately in the protos folder, and copied the generated file to the utils/protos folder under the tf3d folder. This error was fixed.
The following are the two generated files(Because can not upload py files, I changed it to txt format). After comparison, it is found that many of them are different. I have not learned protoc, so I don’t know what caused this error.

[string_int_label_map_pb2(from_tf3d_utils_proto).txt](https://github.com/google-research/google-research/files/6170475/string_int_label_map_pb2.from_tf3d_utils_proto.txt)
[string_int_label_map_pb2(from_object_detection_module).txt](https://github.com/google-research/google-research/files/6170477/string_int_label_map_pb2.from_object_detection_module.txt)

PS: 
1. Under tf3d/datasets/labelmaps, I found that there is no pbtxt corresponding to the rio data set.
2. Under tf3d/object_detection, I also did not find the script and .gin file of the rio data set.

Thanks!
