### ISSUE TITLE
Getting no registered kernels ConfigureDistributedTPU for 'meta_pseudo_labels'

### ISSUE THREAD

**Issue by nies14** [google-research/google-research#651]
Traceback (most recent call last):
  File "meta_pseudo_labels/main.py", line 463, in main
    train_tpu(params, should_eval=should_eval)
  File "meta_pseudo_labels/main.py", line 237, in train_tpu
    set_tpu_info(params)
  File "meta_pseudo_labels/main.py", line 68, in set_tpu_info
    topology_proto = sess.run(tpu_init)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by node ConfigureDistributedTPU (defined at /usr/local/lib/p
ython3.7/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [tpu_embedding_config="", is_global_init=false, embedding_config=""]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>
         [[ConfigureDistributedTPU]]
I0322 13:53:47.967103 140539649898304 main.py:470] Failed 50 times. Retry!

**Comment by liujiaming1996** [comment]
i have the same problem. And i summarize some corresponding questions in mpl code.
 (btw, i use colab-tpu to run this work.)
question 1: i can not find the parameter 'num_cores_per_replica' in main.py(line 71). And the paremeter is not defined in flag_utils.py. 
question 2: i donot know which tpu_lib  is imported in main.py(line 66).
thank you very much!

**Comment by liujiaming1996** [comment]
> Traceback (most recent call last): File "meta_pseudo_labels/main.py", line 463, in main train_tpu(params, should_eval=should_eval) File "meta_pseudo_labels/main.py", line 237, in train_tpu set_tpu_info(params) File "meta_pseudo_labels/main.py", line 68, in set_tpu_info topology_proto = sess.run(tpu_init) File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 956, in run run_metadata_ptr) File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run feed_dict_tensor, options, run_metadata) File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run run_metadata) File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by node ConfigureDistributedTPU (defined at /usr/local/lib/p ython3.7/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [tpu_embedding_config="", is_global_init=false, embedding_config=""] Registered devices: [CPU, XLA_CPU] Registered kernels: [[ConfigureDistributedTPU]] I0322 13:53:47.967103 140539649898304 main.py:470] Failed 50 times. Retry!

Hi, have u solved this problem?

**Comment by liujiaming1996** [comment]
In first thread, the code can initial the model successful. But in the second thread, 'ConfigureDistributedTPU' can not find ‘TPU’?
