### ISSUE TITLE
kws_streaming TF 2.5

### ISSUE THREAD

**Issue by StuartIanNaylor** [google-research/google-research#703]
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'training/Adam/gradients/gradients/gru/cell/while_grad/gru/cell/while_grad': Connecting to invalid output 51 of source node gru/cell/while which has 51 outputs. Try using tf.compat.v1.experimental.output_all_intermediates(True).`

**Comment by StuartIanNaylor** [comment]
Apols me using an older fork

**Comment by StuartIanNaylor** [comment]
I thought it might be because of the older fork but works on 2.4.1 but not 2.5

**Comment by rybakov** [comment]
please share more details about how to reproduce the error.

**Comment by StuartIanNaylor** [comment]
```
W0515 01:51:17.825679 140248402396992 module_wrapper.py:153] From /home/stuart/google-kws/kws_streaming/train/train.py:49: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

I0515 01:51:17.928516 140248402396992 train.py:69] Namespace(act1="'linear','relu'", background_frequency=0.8, background_volume=0.1, batch_size=100, causal_data_frame_padding=0, clip_duration_ms=1000, cnn_act="'relu','relu'", cnn_dilation_rate='(1,1),(1,1)', cnn_filters='16,16', cnn_kernel_size='(3,3),(5,3)', cnn_strides='(1,1),(1,1)', data_dir='/home/stuart/Dataset-builder/dataset/', data_frame_padding=None, data_stride=1, data_url='', dct_num_features=20, desired_samples=16000, dropout1=0.1, eval_step_interval=400, feature_type='mfcc_op', fft_magnitude_squared=True, frequency_mask_max_size=5, frequency_masks_number=2, gru_units='256', how_many_training_steps='6000,6000,6000,6000', l2_weight_decay=0.0, label_count=3, learning_rate='0.001,0.0005,0.0001,0.00002', log_epsilon=1e-12, lr_schedule='exp', mel_lower_edge_hertz=20.0, mel_non_zero_only=1, mel_num_bins=40, mel_upper_edge_hertz=7600.0, model_name='crnn', novograd_beta_1=0.95, novograd_beta_2=0.5, novograd_grad_averaging=0, novograd_weight_decay=0.001, optimizer='adam', optimizer_epsilon=1e-08, pick_deterministically=0, preemph=0.0, preprocess='raw', quantize=0, resample=0.0, return_sequences='0', return_softmax=0, sample_rate=16000, save_step_interval=100, silence_percentage=10.0, sp_resample=0.0, sp_time_shift_ms=0.0, spec_cutout_frequency_mask_size=5, spec_cutout_masks_number=3, spec_cutout_time_mask_size=10, spectrogram_length=49, split_data=0, start_checkpoint='', stateful=1, summaries_dir='/home/stuart/google-kws/models2/crnn_state/logs/', testing_percentage=10, time_mask_max_size=10, time_masks_number=2, time_shift_ms=100.0, train=1, train_dir='/home/stuart/google-kws/models2/crnn_state/', training=True, units1='128,256', unknown_percentage=10.0, use_spec_augment=1, use_spec_cutout=0, use_tf_fft=0, validation_percentage=10, verbosity=0, volume_resample=0.0, wanted_words='silence,notkw,kw', wav=1, window_size_ms=40.0, window_size_samples=640, window_stride_ms=20.0, window_stride_samples=320, window_type='hann')
2021-05-15 01:51:18.472312: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.472656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.392GHz coreCount: 6 deviceMemorySize: 3.94GiB deviceMemoryBandwidth: 104.43GiB/s
2021-05-15 01:51:18.472766: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.473114: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.473378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-05-15 01:51:18.695905: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3392225000 Hz
2021-05-15 01:51:18.977733: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.978064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.392GHz coreCount: 6 deviceMemorySize: 3.94GiB deviceMemoryBandwidth: 104.43GiB/s
2021-05-15 01:51:18.978127: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.978416: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.978667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-05-15 01:51:18.978698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-15 01:51:18.978708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-05-15 01:51:18.978716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-05-15 01:51:18.978791: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.979082: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-15 01:51:18.979403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3129 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:Layer cell will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
W0515 01:51:18.979778 140248402396992 recurrent_v2.py:413] Layer cell will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(100, 16000)]            0         
_________________________________________________________________
speech_features (SpeechFeatu (100, 49, 20)             0         
_________________________________________________________________
tf_op_layer_ExpandDims (Tens [(100, 49, 20, 1)]        0         
_________________________________________________________________
stream (Stream)              (100, 47, 18, 16)         160       
_________________________________________________________________
stream_1 (Stream)            (100, 43, 16, 16)         3856      
_________________________________________________________________
reshape (Reshape)            (100, 43, 256)            0         
_________________________________________________________________
gru (GRU)                    (100, 1, 256)             394752    
_________________________________________________________________
stream_2 (Stream)            (100, 256)                0         
_________________________________________________________________
dropout (Dropout)            (100, 256)                0         
_________________________________________________________________
dense (Dense)                (100, 128)                32896     
_________________________________________________________________
dense_1 (Dense)              (100, 256)                33024     
_________________________________________________________________
dense_2 (Dense)              (100, 3)                  771       
=================================================================
Total params: 465,459
Trainable params: 465,459
Non-trainable params: 0
_________________________________________________________________
I0515 01:51:19.321968 140248402396992 train.py:71] None
I0515 01:51:19.619409 140248402396992 train.py:107] Training from step: 1 
2021-05-15 01:51:21.140477: W tensorflow/c/c_api.cc:335] Operation '{name:'gru/cell/while' id:661 op device:{} def:{{{node gru/cell/while}} = While[T=[DT_INT32, DT_INT32, DT_INT32, DT_VARIANT, DT_FLOAT, ..., DT_VARIANT, DT_VARIANT, DT_VARIANT, DT_VARIANT, DT_VARIANT], _lower_using_switch_merge=true, _num_original_outputs=53, _read_only_resource_inputs=[7, 8, 9], body=gru_cell_while_body_1256_rewritten[], cond=gru_cell_while_cond_1255_rewritten[], output_shapes=[[], [], [], [], [100,256], ..., [], [], [], [], []], parallel_iterations=32](gru/cell/while/loop_counter, gru/cell/while/maximum_iterations, gru/cell/time, gru/cell/TensorArrayV2_1, gru/cell/ReadVariableOp, gru/cell/strided_slice, gru/cell/TensorArrayUnstack/TensorListFromTensor, gru/cell/gru_cell/bias, gru/cell/gru_cell/kernel, gru/cell/gru_cell/recurrent_kernel, gru/cell/while/EmptyTensorList, gru/cell/while/EmptyTensorList_1, gru/cell/while/EmptyTensorList_2, gru/cell/while/EmptyTensorList_3, gru/cell/while/EmptyTensorList_4, gru/cell/while/EmptyTensorList_5, gru/cell/while/EmptyTensorList_6, gru/cell/while/EmptyTensorList_7, gru/cell/while/EmptyTensorList_8, gru/cell/while/EmptyTensorList_9, gru/cell/while/EmptyTensorList_10, gru/cell/while/EmptyTensorList_11, gru/cell/while/EmptyTensorList_12, gru/cell/while/EmptyTensorList_13, gru/cell/while/EmptyTensorList_14, gru/cell/while/EmptyTensorList_15, gru/cell/while/EmptyTensorList_16, gru/cell/while/EmptyTensorList_17, gru/cell/while/EmptyTensorList_18, gru/cell/while/EmptyTensorList_19, gru/cell/while/EmptyTensorList_20, gru/cell/while/EmptyTensorList_21, gru/cell/while/EmptyTensorList_22, gru/cell/while/EmptyTensorList_23, gru/cell/while/EmptyTensorList_24, gru/cell/while/EmptyTensorList_25, gru/cell/while/EmptyTensorList_26, gru/cell/while/EmptyTensorList_27, gru/cell/while/EmptyTensorList_28, gru/cell/while/EmptyTensorList_29, gru/cell/while/EmptyTensorList_30, gru/cell/while/EmptyTensorList_31, gru/cell/while/EmptyTensorList_32, gru/cell/while/EmptyTensorList_33, gru/cell/while/EmptyTensorList_34, gru/cell/while/EmptyTensorList_35, gru/cell/while/EmptyTensorList_36, gru/cell/while/EmptyTensorList_37, gru/cell/while/EmptyTensorList_38, gru/cell/while/EmptyTensorList_39, gru/cell/while/EmptyTensorList_40, training/Adam/gradients/gradients/gru/cell/while_grad/gradients/TensorArrayV2Read/TensorListGetItem_grad/TensorListElementShape_0/accumulator:0, training/Adam/gradients/gradients/gru/cell/while_grad/gradients/TensorArrayV2Read/TensorListGetItem_grad/TensorListLength_0/accumulator:0)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
Traceback (most recent call last):
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'training/Adam/gradients/gradients/gru/cell/while_grad/gru/cell/while_grad': Connecting to invalid output 51 of source node gru/cell/while which has 51 outputs. Try using tf.compat.v1.experimental.output_all_intermediates(True).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stuart/google-kws/kws_streaming/train/model_train_eval.py", line 366, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/stuart/google-kws/kws_streaming/train/model_train_eval.py", line 147, in main
    train.train(flags)
  File "/home/stuart/google-kws/kws_streaming/train/train.py", line 147, in train
    result = model.train_on_batch(train_fingerprints, train_ground_truth)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1094, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 4020, in __call__
    session = get_session(inputs)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 745, in get_session
    _initialize_variables(session)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 1193, in _initialize_variables
    is_initialized = session.run(
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'training/Adam/gradients/gradients/gru/cell/while_grad/gru/cell/while_grad': Connecting to invalid output 51 of source node gru/cell/while which has 51 outputs. Try using tf.compat.v1.experimental.output_all_intermediates(True).
```
tensorflow-2.5.0-cp38-cp38-manylinux2010_x86_64.whl

```
```

$CMD_TRAIN \

--data_url '' \

--data_dir $DATA_PATH/ \

--train_dir $MODELS_PATH/crnn_state/ \

--mel_upper_edge_hertz 7600 \

--how_many_training_steps 20000,20000,20000,20000 \

--learning_rate 0.001,0.0005,0.0001,0.00002 \

--window_size_ms 40.0 \

--window_stride_ms 20.0 \

--mel_num_bins 40 \

--dct_num_features 20 \

--resample 0.15 \

--alsologtostderr \

--train 1 \

--lr_schedule 'exp' \

--use_spec_augment 1 \

--time_masks_number 2 \

--time_mask_max_size 10 \

--frequency_masks_number 2 \

--frequency_mask_max_size 5 \

--feature_type 'mfcc_op' \

--fft_magnitude_squared 1 \

crnn \

--cnn_filters '16,16' \

--cnn_kernel_size '(3,3),(5,3)' \

--cnn_act "'relu','relu'" \

--cnn_dilation_rate '(1,1),(1,1)' \

--cnn_strides '(1,1),(1,1)' \

--gru_units 256 \

--return_sequences 0 \

--dropout1 0.1 \

--units1 '128,256' \

--act1 "'linear','relu'" \

--stateful 1

```

1st step bangs out and apols thought it would be univeral as some sort of API change causing this with 2.5?

**Comment by rybakov** [comment]
Thank you for sharing the log. It looks like there was an issue with symbolic loops / control flow. I would suggest to try tf nightly or if you prefer to use tf 2.5 then I would try to set unroll=True in the [code](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/gru.py#L63)

**Comment by StuartIanNaylor** [comment]
Its OK @rybakov prob will prefer to use 2.5 and was just eager to test some of the tflite post quant changes and see if and what...

I am OK with 2.4.1 and was just reporting back as 2.5 is still hot from the press.

Thanks for g-kws seriosly great PS any chance background noise could be matched to the RMS of classification so you can have more control without it becoming the foreground?

**Comment by rybakov** [comment]
"Unroll" just removes the symbolic loops in the model, it does not affect anything else, I tested it on tf 2.6 nightly and it works ok.

Without "Unroll", I confirm that InvalidArgumentError happens on tf 2.6 (so it looks like this issues happens on 2.5.1 and above).
Please report this issue at tf github.

"any chance background noise could be matched to the RMS of classification so you can have more control without it becoming the foreground?"
This customization is up to you: current set up was selected for comparing with other papers.

**Comment by StuartIanNaylor** [comment]
Not sure what to post but many thanks
