### ISSUE TITLE
Index Out of Range Error in tokenization using TF Hub for Pretrained Albert Models

### ISSUE THREAD

**Issue by jsmith09** [google-research/google-research#73]
I am getting _**Index out of Range**_ error in tokenization.py when running a finetune Albert large model with TF Hub. I printed out the vocab file and printing out the token before the error. You can see the error and print-outs below. 
```
Vocab File: b'/tmp/tfhub_modules/c88f9d4ac7469966b2fab3b577a8031ae23e125a/assets/30k-clean.model'
Token:  

Traceback (most recent call last):
  File "/home/smithj13/anaconda3/envs/tf-gpu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/smithj13/anaconda3/envs/tf-gpu/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/smithj13/Documents/ml-tests/falling-albert/albert/run_classifier_with_tfhub.py", line 318, in <module>
    tf.compat.v1.app.run()
  File "/home/smithj13/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/smithj13/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/smithj13/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/smithj13/Documents/ml-tests/falling-albert/albert/run_classifier_with_tfhub.py", line 185, in main
    tokenizer = create_tokenizer_from_hub_module(FLAGS.albert_hub_module_handle)
  File "/home/smithj13/Documents/ml-tests/falling-albert/albert/run_classifier_with_tfhub.py", line 161, in create_tokenizer_from_hub_module
    spm_model_file=FLAGS.spm_model_file)
  File "/home/smithj13/Documents/ml-tests/falling-albert/albert/tokenization.py", line 249, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/home/smithj13/Documents/ml-tests/falling-albert/albert/tokenization.py", line 203, in load_vocab
    token = token.strip().split()[0]
IndexError: list index out of range
```
**Albert Finetune Shell Script**
```
#!/bin/bash
pip install -r albert/requirements.txt
python -m albert.run_classifier_with_tfhub \
--albert_hub_module_handle=https://tfhub.dev/google/albert_xlarge/1 \
--task_name=cola \
--do_train=true \
--do_eval=true  \
--data_dir=./data-to-albert \
--max_seq_length=128  \
--train_batch_size=32  \
--learning_rate=2e-05 \
--num_train_epochs=3.0  \
--output_dir=./checkpoints/test
```
```

**Comment by LysandreJik** [comment]
I am getting the same errors on all the available TF hub models.

**Comment by PavelKovalets** [comment]
Seems like this happens because of '\n' lines in vocab file, [similar case described here](https://github.com/google-research/google-research/issues/72#issuecomment-546587491). But it is not clear how to handle this, maybe the files are corrupted?

**Comment by eaplatanios** [comment]
I'm not sure what the python script is doing but the vocabulary is not simply a text file. It's a SentencePiece model file (which is basically a protobuf-serialized file) and must be deserialized using either protobuf directly or the SentencePiece python API.

**Comment by KodairaTomonori** [comment]
'30k-clean.model' is 'spm_model_file', not 'vocab_file'.
The code changes are:
```
diff --git a/albert/run_classifier_with_tfhub.py b/albert/run_classifier_with_tfhub.py
index 92fef74..26f4339 100644                                                         
--- a/albert/run_classifier_with_tfhub.py                                             
+++ b/albert/run_classifier_with_tfhub.py                                             
@@ -156,6 +156,7 @@ def create_tokenizer_from_hub_module(albert_hub_module_handle):   
     with tf.Session() as sess:                                                       
       vocab_file, do_lower_case = sess.run([tokenization_info["vocab_file"],         
                                             tokenization_info["do_lower_case"]])     
+    FLAGS.spm_model_file = vocab_file                                                
   return tokenization.FullTokenizer(                                                 
       vocab_file=vocab_file, do_lower_case=do_lower_case,                            
       spm_model_file=FLAGS.spm_model_file)                                           
```

**Comment by YujiOshima** [comment]
Thanks @eaplatanios @KodairaTomonori .
I have resolved Index out of Range error but I got another error like blow.

```
LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_23/layer_23/inner_group_0/LayerNorm_1/batchnorm/add_1' (op type: AddV2)
```

Do you have any ideas? Thanks!

**Comment by mnsrmov** [comment]
Upgrade your tensorflow to at least 1.15.

**Comment by chiragsanghvi10** [comment]
> Thanks @eaplatanios @KodairaTomonori .
> I have resolved Index out of Range error but I got another error like below.
> 
> ```
> LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_23/layer_23/inner_group_0/LayerNorm_1/batchnorm/add_1' (op type: AddV2)
> ```
> 
> Do you have any ideas? Thanks!

@YujiOshima Hi, I am still facing the same issue, can you help me with how did you resolve the issue?

**Comment by chiragsanghvi10** [comment]
This is what I am executing, I tried to enter the task_name as stsb, 

`python run_classifier.py 
--data_dir /home/chirag/git/albert_pytorch/albert_english_pytorch/dataset/sts-b/train.tsv 
--model_type sts-b_output 
--model_name_or_path https://tfhub.dev/google/albert_xlarge/2 
--task_name stsb
--output_dir /home/chirag/git/albert_pytorch/albert_english_pytorch/outputs 
--spm_model_file /home/chirag/git/albert_pytorch/albert_english_pytorch/prev_trained_model/albert_base_v2/30k-clean.model
`

I am getting the following ValueError message
```

Traceback (most recent call last):
  File "run_classifier.py", line 465, in <module>
    main()
  File "run_classifier.py", line 386, in main
    raise ValueError("Task not found: %s" % (args.task_name))
ValueError: Task not found: stsb
```
Any idea? Thanks

**Comment by mnsrmov** [comment]
> > Thanks @eaplatanios @KodairaTomonori .
> > I have resolved Index out of Range error but I got another error like below.
> > ```
> > LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_23/layer_23/inner_group_0/LayerNorm_1/batchnorm/add_1' (op type: AddV2)
> > ```
> > 
> > 
> > Do you have any ideas? Thanks!
> 
> @YujiOshima Hi, I am still facing the same issue, can you help me with how did you resolve the issue?

For version one you, if you use the latest tensorflow 1 it'll fix both problems. However, I have not found a sensible solution for version 2 yet.

**Comment by insop** [comment]
> Upgrade your tensorflow to at least 1.15.

I am using 1.15 but seeing the same issue, I am keep reading the thread...

```
$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.15.0
```
