### ISSUE TITLE
Incompatible function arguments when importing flax.nn

### ISSUE THREAD

**Issue by juneskiafc** [google-research/google-research#749]
To replicate:
```console
conda create -n ptopk python=3.8
pip install -r requirements.txt
python image_classification.py --config <some config> --workdir /tmp
```

Getting incompatible function arguments error when image_classification.py tries to import flax.nn:

```console
TypeError: jit(): incompatible function arguments. The following argument types are supported:
    1. (fun: function, cache_miss: function, get_device: function, static_argnums: List[int], static_argnames: List[str] = [], donate_argnums: List[int] = [], cache: jaxlib.xla_extension.jax_jit.CompiledFunctionCache = None) -> object

Invoked with: <function _rfft_transpose at 0x7f22f751fdc0>, <function _cpp_jit.<locals>.cache_miss at 0x7f22f751fe50>, <function _cpp_jit.<locals>.get_device_info at 0x7f22f751fee0>, <function _cpp_jit.<locals>.get_jax_enable_x64 at 0x7f22f751ff70>, <function _cpp_jit.<locals>.get_jax_disable_jit_flag at 0x7f22f7526040>, (0, 2)
```

OS Info:
Ubuntu 20.04.1 LTS

**Comment by wztdream** [comment]
same issue here, and as flax.nn already deprecated so should update to flax.linen too

**Comment by wztdream** [comment]
In my case this is just due to not install cuda and cudnn, after properly install them, everything goes ok

**Comment by Aiden-yang-qq** [comment]
Here's a same mistake when I "import jax" in python, the error info says:
`import jax

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/jax/__init__.py", line 93, in <module>
    from . import image
…………

TypeError: jit(): incompatible function arguments. The following argument types are supported:
    1. (fun: function, cache_miss: function, get_device: function, static_argnums: List[int], static_argnames: List[str] = [], donate_argnums: List[int] = [], cache: jaxlib.xla_extension.jax_jit.CompiledFunctionCache = None) -> object

Invoked with: <function _rfft_transpose at 0x7f5d7f4f70d0>, <function _cpp_jit.<locals>.cache_miss at 0x7f5d7f4f7160>, <function _cpp_jit.<locals>.get_device_info at 0x7f5d7f4f71f0>, <function _cpp_jit.<locals>.get_jax_enable_x64 at 0x7f5d7f4f7280>, <function _cpp_jit.<locals>.get_jax_disable_jit_flag at 0x7f5d7f4f7310>, (0, 2)`

and I don't know how to solve it.

**Comment by sammens** [comment]
You have to installed the required library which is found in the `requirement.txt` file

**Comment by Dittonal** [comment]
pip install flax==0.3.1 jax==0.2.10 works
