### ISSUE TITLE
tf3d use my pointcloud data gives tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= 0

### ISSUE THREAD

**Issue by zhangyuyi99** [google-research/google-research#777]
I am trying to feed my point cloud data into the semantic segmentation sparseconvunet by modifying run_train_local.py and adding new siemens_spec.py, siemens_dataset_frame.py and siemens_train.gin. Waymo semantic segmentation can train smoothly but the siemens one is not working. 

I get stuck on this error: 

```
I0809 09:53:35.545849 140474592175936 train.py:117] Model fit starting for 100 epochs, 10                                                                    0 step per epoch, total batch size:2
I0809 09:53:36.200485 140474592175936 callback_utils.py:370] Saving ckpt for epoch: 0 at                                                                     /tmp/tf3d_experiment/seg_siemens_001/model
Epoch 1/100
Traceback (most recent call last):
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/runpy.py", line 193, in _run_module_                                                                    as_main
    "__main__", mod_spec)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sdl/assem/users/yvu2cv/tf3d/train.py", line 222, in <module>
    app.run(main)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/absl/app.py", line 303                                                                    , in run
    _run_main(main, args)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/absl/app.py", line 251                                                                    , in _run_main
    sys.exit(main(argv))
  File "/sdl/assem/users/yvu2cv/tf3d/train.py", line 177, in main
    train(strategy=strategy, write_path=write_path)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/gin/config.py", line 1                                                                    069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/gin/utils.py", line 41                                                                    , in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/gin/config.py", line 1                                                                    046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/sdl/assem/users/yvu2cv/tf3d/train.py", line 124, in train
    verbose=1 if FLAGS.run_functions_eagerly else 2)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/kera                                                                    s/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/kera                                                                    s/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/kera                                                                    s/engine/training.py", line 806, in train_function
    return step_function(self, iterator)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/kera                                                                    s/engine/training.py", line 795, in step_function
    data = next(iterator)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/dist                                                                    ribute/input_lib.py", line 649, in __next__
    return self.get_next()
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/dist                                                                    ribute/input_lib.py", line 694, in get_next
    self._iterators[i].get_next_as_list_static_shapes(new_name))
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/dist                                                                    ribute/input_lib.py", line 1474, in get_next_as_list_static_shapes
    return self._iterator.get_next()
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/data                                                                    /ops/multi_device_iterator_ops.py", line 581, in get_next
    result.append(self._device_iterators[i].get_next())
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/data                                                                    /ops/iterator_ops.py", line 825, in get_next
    return self._next_internal()
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/data                                                                    /ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/eage                                                                    r/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/u/yvu2cv/miniconda3/envs/tf3d/lib/python3.6/site-packages/tensorflow/python/eage                                                                    r/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0                                                                     >= 0
         [[{{node random_uniform}}]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
  In call to configurable 'train' (<function train at 0x7fc2c2df4048>)

```

Does anyone have clue on what caused this? Any help will be appreciated!

**Comment by zhangyuyi99** [comment]
Code to reproduce the error is here: https://github.com/zhangyuyi99/google-research/tree/master/tf3d
