### ISSUE TITLE
Error about convert MobileBERT to TFLite 

### ISSUE THREAD

**Issue by bhbruce** [google-research/google-research#780]
@saberkun @renjie-liu 
I would like to convert mobilebert to tflite format.
I use the quantized weight you offered in the repo with tensorflow 1.15. https://github.com/google-research/google-research/tree/master/mobilebert#pre-trained-checkpoints 

But the error occurs when I try to convert the model to int8 tflite model. 
I use the flag: `--use_post_quantization  --activation_quantization`

Log:
```
2021-08-13 09:03:07.437436: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-08-13 09:03:09.818900: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2021-08-13 09:03:09.818948: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 7077 nodes (-6520), 7317 edges (-6524), time = 1308.49194ms.
2021-08-13 09:03:09.818955: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 7077 nodes (0), 7317 edges (0), time = 426.431ms.
Traceback (most recent call last):
  File "run_squad_ptq.py", line 653, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_squad_ptq.py", line 642, in main
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 993, in convert
    inference_output_type)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 239, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 78, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Invalid quantization params for op GATHER at index 2 in subgraph 0
```

I also try to convert the model in Tensorflow 2.3/2.4/2.6. In those versions, the model can convert successfully to tflite.
However, a runtime error occurs during inference.
```
RuntimeError: tensorflow/lite/kernels/dequantize.cc:75 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 2 (DEQUANTIZE) failed to prepare.
 ```
I've referred to #325. It still does not work.
I can convert model weights to integers, but whenever I want to convert activation error happened.

Another question: why the model which I converts to fp32 tflite model cannot show in Netron? Your models in tfhub can do. Are there any differences between tfhub models and https://github.com/google-research/google-research/tree/master/mobilebert#pre-trained-checkpoints?

**Comment by jk78346** [comment]
How did you work when you use tf2.3/2.4/2.6? What did you modify exactly?

I tried tf2.x and got this error: 
```
Traceback (most recent call last):
  File "mobilebert/run_squad.py", line 32, in <module>
    from mobilebert import modeling
  File "/home/khsu4/google-research/mobilebert/modeling.py", line 32, in <module>
    from tensorflow.contrib import layers as contrib_layers
ModuleNotFoundError: No module named 'tensorflow.contrib'
```
It seems like the same error message as mentioned [here](https://github.com/google-research/google-research/issues/325), any idea?
