### ISSUE TITLE
error training svdf_resnet on custom data

### ISSUE THREAD

**Issue by srewai** [google-research/google-research#809]
Hi @rybakov , 

I am trying to follow the steps [here for quantization](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_30k_12_labels.md) with the below command on custom data. Below is the command used:
```
$CMD_TRAIN \
--wanted_words 'srewai' \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/svdf_resnet/ \
--mel_upper_edge_hertz 7600 \
--how_many_training_steps 20000,20000,20000,20000 \
--learning_rate 0.001,0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 80 \
--dct_num_features 40 \
--resample 0.15 \
--time_shift_ms 100 \
--feature_type 'mfcc_op' \
--fft_magnitude_squared 1 \
--preprocess 'raw' \
--train 1 \
--lr_schedule 'exp' \
svdf_resnet \
--block1_memory_size '7' \
--block2_memory_size '7' \
--block3_memory_size '11,11' \
--block1_units1 '32' \
--block2_units1 '50' \
--block3_units1 '50,128' \
--blocks_pool '2,2,1' \
--use_batch_norm 1 \
--bn_scale 1 \
--activation 'relu' \
--svdf_dropout 0.0 \
--svdf_pad 1 \
--svdf_use_bias 0 \
--dropout1 0.0 \
--units2 '64' \
--flatten 0
```
The model summary looks like this.
```
Instructions for updating:
Colocations handled automatically by placer.
W0903 18:00:45.072718 140373190989632 deprecation.py:347] From /lhome/srauniy/test2/sonu-venv/lib/python3.6/site-packages/keras/layers/normalization/batch_normalization.py:532: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(100, 16000)]       0           []                               
__________________________________________________________________________________________________
speech_features (SpeechFeature  (100, 49, 40)        0           ['input_1[0][0]']                
s)                                                                                                
__________________________________________________________________________________________________
dense_1 (Dense)                 (100, 49, 32)        1280        ['speech_features[0][0]']        
__________________________________________________________________________________________________
svdf_1_0 (Svdf)                 (100, 49, 32)        1632        ['speech_features[0][0]']        
__________________________________________________________________________________________________
batch_normalization_1 (BatchNo  (100, 49, 32)        128         ['dense_1[0][0]']                
rmalization)                                                                                      
__________________________________________________________________________________________________
add (Add)                       (100, 49, 32)        0           ['svdf_1_0[0][0]',               
                                                                  'batch_normalization_1[0][0]']  
__________________________________________________________________________________________________
activation (Activation)         (100, 49, 32)        0           ['add[0][0]']                    
__________________________________________________________________________________________________
max_pooling1d (MaxPooling1D)    (100, 24, 32)        0           ['activation[0][0]']             
__________________________________________________________________________________________________
dense_3 (Dense)                 (100, 24, 50)        1600        ['max_pooling1d[0][0]']          
__________________________________________________________________________________________________
svdf_2_0 (Svdf)                 (100, 24, 50)        2150        ['max_pooling1d[0][0]']          
__________________________________________________________________________________________________
batch_normalization_3 (BatchNo  (100, 24, 50)        200         ['dense_3[0][0]']                
rmalization)                                                                                      
__________________________________________________________________________________________________
add_1 (Add)                     (100, 24, 50)        0           ['svdf_2_0[0][0]',               
                                                                  'batch_normalization_3[0][0]']  
__________________________________________________________________________________________________
activation_1 (Activation)       (100, 24, 50)        0           ['add_1[0][0]']                  
__________________________________________________________________________________________________
max_pooling1d_1 (MaxPooling1D)  (100, 11, 50)        0           ['activation_1[0][0]']           
__________________________________________________________________________________________________
svdf_3_0 (Svdf)                 (100, 11, 50)        3250        ['max_pooling1d_1[0][0]']        
__________________________________________________________________________________________________
dense_6 (Dense)                 (100, 11, 128)       6400        ['max_pooling1d_1[0][0]']        
__________________________________________________________________________________________________
svdf_3_1 (Svdf)                 (100, 11, 128)       8320        ['svdf_3_0[0][0]']               
__________________________________________________________________________________________________
batch_normalization_6 (BatchNo  (100, 11, 128)       512         ['dense_6[0][0]']                
rmalization)                                                                                      
__________________________________________________________________________________________________
add_2 (Add)                     (100, 11, 128)       0           ['svdf_3_1[0][0]',               
                                                                  'batch_normalization_6[0][0]']  
__________________________________________________________________________________________________
activation_2 (Activation)       (100, 11, 128)       0           ['add_2[0][0]']                  
__________________________________________________________________________________________________
max_pooling1d_2 (MaxPooling1D)  (100, 9, 128)        0           ['activation_2[0][0]']           
__________________________________________________________________________________________________
global_average_pooling1d (Glob  (100, 128)           0           ['max_pooling1d_2[0][0]']        
alAveragePooling1D)                                                                               
__________________________________________________________________________________________________
dropout (Dropout)               (100, 128)           0           ['global_average_pooling1d[0][0]'
                                                                 ]                                
__________________________________________________________________________________________________
dense_7 (Dense)                 (100, 64)            8256        ['dropout[0][0]']                
__________________________________________________________________________________________________
dense_8 (Dense)                 (100, 3)             195         ['dense_7[0][0]']                
==================================================================================================
Total params: 33,923
Trainable params: 32,983
Non-trainable params: 940
__________________________________________________________________________________________________
I0903 18:00:45.455425 140373190989632 train.py:71] None
```

But it fails at the time of converting into tflite stream. Here is the error:

```
I0903 18:01:06.509099 140373190989632 test.py:510] tflite test accuracy, non stream model = 74.63% 200 out of 221
I0903 18:01:06.552580 140373190989632 test.py:514] tflite Final test accuracy, non stream model = 75.11% (N=221)
I0903 18:01:06.553761 140373190989632 model_train_eval.py:257] run TFlite streaming model accuracy evaluation
W0903 18:01:07.091468 140373190989632 test.py:560] FAILED to convert to mode STREAM_EXTERNAL_STATE_INFERENCE, tflite: Negative dimension size caused by subtracting 3 from 1 for '{{node streaming/max_pooling1d/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 3, 1, 1], padding="VALID", strides=[1, 2, 1, 1]](streaming/max_pooling1d/ExpandDims)' with input shapes: [1,1,1,32].
I0903 18:01:07.091856 140373190989632 test.py:364] tflite stream model state external with reset_state 1
I0903 18:01:07.342433 140373190989632 model_train_eval.py:282] FAILED to run TFLite streaming: Mmap of '7' at offset '0' failed with error '22'.

```
Below is my environment :

```
Package                       Version
----------------------------- -------------------
absl-py                       0.13.0
argon2-cffi                   21.1.0
astunparse                    1.6.3
async-generator               1.10
attrs                         21.2.0
backcall                      0.2.0
bleach                        4.1.0
cached-property               1.5.2
cachetools                    4.2.2
certifi                       2021.5.30
cffi                          1.14.6
charset-normalizer            2.0.4
cycler                        0.10.0
dataclasses                   0.8
decorator                     5.0.9
defusedxml                    0.7.1
dm-tree                       0.1.6
entrypoints                   0.3
flatbuffers                   1.12
gast                          0.4.0
google-auth                   1.35.0
google-auth-oauthlib          0.4.5
google-pasta                  0.2.0
graphviz                      0.17
grpcio                        1.39.0
h5py                          3.1.0
idna                          3.2
importlib-metadata            4.8.1
ipykernel                     5.5.5
ipython                       7.16.1
ipython-genutils              0.2.0
ipywidgets                    7.6.4
jedi                          0.18.0
Jinja2                        3.0.1
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                7.0.2
jupyter-console               6.4.0
jupyter-core                  4.7.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.1
keras-nightly                 2.7.0.dev2021083107
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.1
libclang                      11.1.0
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.3.4
mistune                       0.8.4
nbclient                      0.5.4
nbconvert                     6.0.7
nbformat                      5.1.3
nest-asyncio                  1.5.1
notebook                      6.4.3
numpy                         1.19.5
oauthlib                      3.1.1
opt-einsum                    3.3.0
packaging                     21.0
pandocfilters                 1.4.3
parso                         0.8.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.1
pip                           21.2.4
prometheus-client             0.11.0
prompt-toolkit                3.0.20
protobuf                      3.17.3
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
pydot                         1.4.2
Pygments                      2.10.0
pyparsing                     2.4.7
pyrsistent                    0.18.0
python-dateutil               2.8.2
pyzmq                         22.2.1
qtconsole                     5.1.1
QtPy                          1.10.0
requests                      2.26.0
requests-oauthlib             1.3.0
rsa                           4.7.2
scipy                         1.5.4
Send2Trash                    1.8.0
setuptools                    57.4.0
six                           1.15.0
tb-nightly                    2.6.0a20210806
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.0
tensorflow-addons             0.14.0
tensorflow-model-optimization 0.6.0
termcolor                     1.1.0
terminado                     0.11.1
testpath                      0.5.0
tf-estimator-nightly          2.7.0.dev2021083108
tf-nightly                    2.7.0.dev20210806
tornado                       6.1
traitlets                     4.3.3
typeguard                     2.12.1
typing-extensions             3.7.4.3
urllib3                       1.26.6
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.1
wheel                         0.37.0
widgetsnbextension            3.5.1
wrapt                         1.12.1
zipp                          3.5.0
```
The data folder has 1-sec recordings as below:

```
data folder:
_background_noise_  bed  bird  cat  dog  happy  srewai  house  marvin  my_recorded_files  sheila  tree  wow
 ```

Please help me here. The data folder contains cd my

**Comment by rybakov** [comment]
It is a known issue [stackoverflow](https://stackoverflow.com/questions/57658509/how-to-invoke-the-flex-delegate-for-tflite-interpreters), there are are two options to solve it: 1 rebuild tf with bazel with enabled flex delegate; 2 use tf as it is but do not use flex ops in your model and replace 
```
--feature_type 'mfcc_op' \
```
by 
```
--feature_type 'mfcc_tf' \
```
The last one will use standard tf ops (this is what we used in the paper). 'mfcc_op' is a good option if you plan to quantize you model.

**Comment by srewai** [comment]
Thanks @rybakov , when I replace the suggested , I still get the error the second error:

```
2021-09-04 18:41:59.625944: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:351] Ignored output_format.
2021-09-04 18:41:59.625969: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored drop_control_dependency.
2021-09-04 18:41:59.636301: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-09-04 18:41:59.698157: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1922] Estimated count of arithmetic ops: 66.155 M  ops, equivalently 33.077 M  MACs

Estimated count of arithmetic ops: 66.155 M  ops, equivalently 33.077 M  MACs
I0904 18:42:00.552432 139941496817472 test.py:510] tflite test accuracy, non stream model = 32.34% 200 out of 221
I0904 18:42:00.605312 139941496817472 test.py:514] tflite Final test accuracy, non stream model = 32.13% (N=221)
I0904 18:42:00.606071 139941496817472 model_train_eval.py:236] run TF evalution only without optimization/quantization
I0904 18:42:01.808442 139941496817472 model_train_eval.py:255] FAILED to run TF streaming: Negative dimension size caused by subtracting 3 from 1 for '{{node streaming/max_pooling1d/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 3, 1, 1], padding="VALID", strides=[1, 2, 1, 1]](streaming/max_pooling1d/ExpandDims)' with input shapes: [1,1,1,32].
I0904 18:42:01.809512 139941496817472 model_train_eval.py:257] run TFlite streaming model accuracy evaluation
W0904 18:42:02.433501 139941496817472 test.py:560] FAILED to convert to mode STREAM_EXTERNAL_STATE_INFERENCE, tflite: Negative dimension size caused by subtracting 3 from 1 for '{{node streaming/max_pooling1d/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 3, 1, 1], padding="VALID", strides=[1, 2, 1, 1]](streaming/max_pooling1d/ExpandDims)' with input shapes: [1,1,1,32].
I0904 18:42:02.433842 139941496817472 test.py:364] tflite stream model state external with reset_state 1
I0904 18:42:02.692718 139941496817472 model_train_eval.py:282] FAILED to run TFLite streaming: Mmap of '7' at offset '0' failed with error '22'.
I0904 18:42:02.693176 139941496817472 model_train_eval.py:194] feature type mfcc_tf needs quantization aware training for quantization - it is not implemented
```

**Comment by rybakov** [comment]
With option "mfcc_tf" you should follow [kws_experiments_paper_12_labels](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md): these are not quantized models.

If you need quantized models then it has to be [kws_experiments_quantized_12_labels](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_quantized_12_labels.md) in this case you will need tflite flex, as descried in [stackoverflow](https://stackoverflow.com/questions/57658509/how-to-invoke-the-flex-delegate-for-tflite-interpreters).

It was designed this way because TFLite did not support some tf ops and I had to use custom TFLite ops with "mfcc_op" (for quantized models) or their direct tf re-implementation with "mfcc_tf" (for non quantized models). In the last case if you enable quantization it will also quantize DFT weights which will degrade model accuracy. Now TFLite supports all ops in this lib, so I can try to enable quantization of "mfcc_tf" too.

**Comment by rybakov** [comment]
There is also issue with striding parameter in the model. I will submit a fix on Monday.
After that you should also add:
```
--data_stride 4 \
```

**Comment by srewai** [comment]
@rybakov, thanks so much for your help.  kws_experiments_paper_12_labels do not have svdf_resnet training example and svdf works fine for me. So, once you have time to implement the changes, please add a comment here for the heads up! :)

Thanks again!

**Comment by rybakov** [comment]
svdf_resnet was added after paper was published. It was not streamable, so in the last CL I made it streamable. Please try
```
$CMD_TRAIN \
--wanted_words 'srewai' \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/svdf_resnet/ \
--mel_upper_edge_hertz 7600 \
--how_many_training_steps 20000,20000,20000,20000 \
--learning_rate 0.001,0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 80 \
--dct_num_features 40 \
--resample 0.15 \
--time_shift_ms 100 \
--feature_type 'mfcc_tf' \
--fft_magnitude_squared 1 \
--preprocess 'raw' \
--train 1 \
--lr_schedule 'exp' \
--data_stride 4 \
svdf_resnet \
--block1_memory_size '7' \
--block2_memory_size '7' \
--block3_memory_size '11,11' \
--block1_units1 '32' \
--block2_units1 '50' \
--block3_units1 '50,128' \
--blocks_pool '2,2,1' \
--use_batch_norm 1 \
--bn_scale 1 \
--activation 'relu' \
--svdf_dropout 0.0 \
--svdf_pad 1 \
--svdf_use_bias 0 \
--dropout1 0.0 \
--units2 '64' \
--flatten 0
```

**Comment by srewai** [comment]
@rybakov,  you're amazing! Thank you so much for your help! It works :)
I really appreciate it. Very quick response!

**Comment by srewai** [comment]
If you don't mind I have few questions as below, just for confirmation:

Consider the below data folder :
```
data folder:
_background_noise_  bed  bird  cat  dog  happy  srewai  house  marvin   sheila  tree  wow
```
Q.1 if we train a model with `--wanted-word 'srewai'`, it will consider everything else in the data folder (bed,bird,dog,house,marvin,sheila,tree,wow) as unknown words but still use these words for training the model, right?

Q.2 How do I add additonal background noise for the training? Do I just add the noise .wav files into the _background_noise_ folder?  Is there limitaion on number of **files** and **audio file length* in _background_noise_ folder?

**Comment by srewai** [comment]
@rybakov , got my answers, simply great! Thanks again!

**Comment by srewai** [comment]
Following the [inference notebook](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/02_inference.ipynb)

I see that the model is converted into streaming mode as below, (Run streaming inference with TFLite):

```
tflite_streaming_model = utils.model_to_tflite(sess, model_non_stream_batch, flags, Modes.STREAM_EXTERNAL_STATE_INFERENCE)
tflite_stream_fname = 'tflite_stream.tflite'



with open(os.path.join(MODEL_PATH, tflite_stream_fname), 'wb') as fd:
  fd.write(tflite_streaming_model)
```

But after training a model, we already have the `tflite_stream.tflite` file, so not sure why not use that directly?

The notebook loads use `model_content`, for `tf.lite.Interpreter` as an argument,
```
example 1:interpreter = tf.lite.Interpreter(**model_content**=tflite_non_streaming_model)
```

Isn't it ok to just load the streaming .tflite file from the models folder like below and run it for inference?

```
example 2: interpreter = tf.lite.Interpreter(**model_path**='path_to_/tflite_stream.tflite')
```

I tried example 1 and example 2 and both of them predict different labels for the same input by the same `.tflite` model. 
I want to implement .tflite model on embedded platform in C++. 

Do you have some recommendations to directly implement the available .tflite  in C++ and skip converting functions like```utils.model_to_tflite```  and others from python to C++ that have been used in the inference notebook.

**Comment by rybakov** [comment]
If you trained your model, then all conversion to streaming is already done (you can use it as it is) so there is no need to convert the model again. Your example 1 and example 2 should be numerically the same, I guess there is a difference in flags parameters, which are used for converting a model in colab (I would suggest to use model generated by training script, utils.model_to_tflite is part of it any way).

I do not have open sourced c++ demo. But there are a lot of [examples](https://stackoverflow.com/questions/56837288/tensorflow-lite-c-api-example-for-inference) of running tflite module in c++. TFLite c++ api is similar to python, you will need to re-implement [py](https://github.com/google-research/google-research/blob/e5e376157ef4e5c425cf9ee1da06537d930067fe/kws_streaming/train/inference.py#L104) in c++.

**Comment by srewai** [comment]
@rybakov , you are an amazing person! Thanks again! You have always helped me extra mile :)
Yes, the difference is in the flag parameter that might have caused the varying results. I am going to use the models generated post model training and will re-implement part of inference.py in c++ as suggested.

**Comment by srewai** [comment]
Hi @rybakov, 

I am trying to train `sdvf` model with custom data split with the below directory structure and training parameters.

```
(venv) srewai@las:~/path/final_dataset$ ls -l
_background_noise_
       < doing_the_dishes.wav   
          dude_miaowing.wav  
         ...
testing  
      < down  
               gen-12.wav 
                ..
         eight  
              gen-1.wav 
               ...
         five  
              xyz.wav
              ... 
         four  
             ...
         hey_babuni 
         nine  
         no  
         on  
         one  
         seven  
         six  
         three  
         two  
         up  
         zero
             abc.wav
training  
          < down  
               gen-3.wav 
                ..
         eight  
              gen-2.wav 
               ...
         five  
              xyzr.wav
              ... 
         four  
             ...
         hey_babuni 
         nine  
         no  
         on  
         one  
         seven  
         six  
         three  
         two  
         up  
         zero
             abcx.wav
validation
           < down  
               gen-3.wav 
                ..
         eight  
              gen-12.wav 
               ...
         five  
              xeyz.wav
              ... 
         four  
             ...
         hey_babuni 
         nine  
         no  
         on  
         one  
         seven  
         six  
         three  
         two  
         up  
         zero
              #abcd.wav
 ```
```
$CMD_TRAIN \
--data_url '' \
--wanted_words hey_babuni \
--split_data 0 \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/svdf/ \
--mel_upper_edge_hertz 7600 \
--how_many_training_steps 20000,20000,20000,20000 \
--learning_rate 0.001,0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 80 \
--dct_num_features 30 \
--resample 0.15 \
--alsologtostderr \
--time_shift_ms 100 \
--train 1 \
svdf \
--svdf_memory_size 4,10,10,10,10,10 \
--svdf_units1 256,256,256,256,256,256 \
--svdf_act "'relu','relu','relu','relu','relu','relu'" \
--svdf_units2 128,128,128,128,128,-1 \
--svdf_dropout 0.0,0.0,0.0,0.0,0.0,0.0 \
--svdf_pad 0 \
--dropout1 0.0 \
--units2 '' \
--act2 ''

```
But I am getting the exception error as:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lhome/srauniy/test2/kws_streaming/train/model_train_eval.py", line 367, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/lhome/srauniy/test2/sonu-venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/lhome/srauniy/test2/sonu-venv/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/lhome/srauniy/test2/sonu-venv/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/lhome/srauniy/test2/kws_streaming/train/model_train_eval.py", line 147, in main
    train.train(flags)
  File "/lhome/srauniy/test2/kws_streaming/train/train.py", line 51, in train
    audio_processor = input_data.AudioProcessor(flags)
  File "/lhome/srauniy/test2/kws_streaming/data/input_data.py", line 124, in __init__
    self.prepare_split_data_index(wanted_words, flags.split_data, file_ext)
  File "/lhome/srauniy/test2/kws_streaming/data/input_data.py", line 324, in prepare_split_data_index
    raise Exception('Unknown word ' + word)
Exception: Unknown word six

```

All the folders `one two three..` in the training, testing, and validation are phonetic segmentation of `--wanted_word hey_babuni`.
I am considering these as contrasting examples of the wanted word. Would you please help me with what is missing here and causing the error? Also, do you think creating contrasting examples using phonetic segmentation would help for a robust model by reducing the number of false positives?

Thank you!

**Comment by rybakov** [comment]
My previous [answer](https://github.com/google-research/google-research/issues/809#issuecomment-916235510) was for a case when lib will split data for you with option 
```
--split_data 1 \
```
But here you are using custom data split with 
```
--split_data 0 \
```
so you have to control all data on your own: data split and labels. As it is shown [here](https://github.com/google-research/google-research/blob/master/kws_streaming/data/input_data_utils.py#L96) SILENCE_LABEL and UNKNOWN_WORD_LABEL will not be added to your wanted_words as it was with split_data=1.
In this case (split_data=0) folders "testing"/"training"/"validation" should have only wanted. 
For example if you have wanted_words: "hey_babuni", "other" then testing folders will contain
```
testing  
      < other     "you can copy here all wav files from other folders 'down', 'eight', 'five' etc..."
               gen-12.wav 
               gen-1.wav 
               xeyz.wav
                ..
         hey_babuni 
```
Sub-folders names (in "testing" folder) have to be the same with wanted_words. Number of wanted_words is the number of categories in the classifier.

"training" and "validation" folders should have the same structure as "testing" above.

**Comment by srewai** [comment]
@rybakov . Thank you so much for the clarification. Here, I want to use the phonetic segmentation of the `--ẁanted_word hey babuni` to be treated as  UNKNOWN_WORD_LABEL so that the model is more robust to avoid false positives. So all the contents of the folder `other` are individual sounds (phonetic segmentation) of `ẁanted word hey babuni` which means these are *not* the list of my wanted words but I want the model to learn them as  UNKNOWN_WORD_LABEL. 

Q.1. Is this a good approach for a robust model to avoid false positives, please suggest?
Q.2  I still want to have 3 output labels, or there is a better approach: 

'hey babuni'
“silence”
“unknown” (all individual sounds, phonetic segmentation).

Thank you for your understanding!

**Comment by rybakov** [comment]
It sounds reasonable to add segments to the “unknown” bucket for reducing false positives. You could also use them as separate labels.
Another standard approach for controlling false positive is thresholding neural net output score (positive rate also will be impacted), in addition you could check that the score is passing a threshold several times before making a final decision.

**Comment by rybakov** [comment]
For example you can collect many hours of speech which does not have any key command. Then compute the distributions of output scores and set a threshold to satisfy your conditions for example probability of false alarm.

**Comment by srewai** [comment]
Thank you so much! But how does this work in the case of --split 1 ?

**Comment by srewai** [comment]
@rybakov , while performing quantization there is talk about calibration dataset for full quantization. How do I achieve this, are there steps mentioned anywhere?

**Comment by rybakov** [comment]
@srewai please have a look at [issues/836](https://github.com/google-research/google-research/issues/836) it discusses post training quantization with calibration data. I am also working on quantization aware training which will not requre calibration data, but I do not have ETA yet.

**Comment by srewai** [comment]
@rybakov, I wish you a happy new year :)
I quickly wanted to ask you, is there anywhere you've also calculated the precision and recall of the models in the code? if not could you please give me any hints on the same.:)

**Comment by rybakov** [comment]
Thank you, happy new year! 

It is a multiclass precision recall, so I would suggest to look at [link](https://towardsdatascience.com/multi-class-metrics-made-simple-part-i-precision-and-recall-9250280bddc2), [link](https://stats.stackexchange.com/questions/51296/how-do-you-calculate-precision-and-recall-for-multiclass-classification-using-co)

**Comment by srewai** [comment]
@rybakov, thank you.
