### ISSUE TITLE
Error about converting stream_state_internal KWS model to tflite

### ISSUE THREAD

**Issue by wenjingyang** [google-research/google-research#828]
Hi, 
I had problem to convert stream_state_internal KWS model to tflite. I have tried both converting from tfpb and h5. The issue is same. Does anyone have any idea? I used "micro" as preprocess.

Thanks. 

Model: 
[ds_cnn_stream.zip](https://github.com/google-research/google-research/files/7223822/ds_cnn_stream.zip)

Traceback (most recent call last):
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node functional_1/stream/AssignVariableOp was passed float from functional_1/stream/ReadVariableOp/resource:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_convert.py", line 16, in <module>
    tfmodel = converter.convert()
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 808, in convert
    _convert_to_constants.convert_variables_to_constants_v2_as_graph(
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1108, in convert_variables_to_constants_v2_as_graph
    frozen_func = _construct_concrete_function(func, output_graph_def,
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 999, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 621, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/home/temp/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node functional_1/stream/AssignVariableOp was passed float from functional_1/stream/ReadVariableOp/resource:0 incompatible with expected resource.

**Comment by wenjingyang** [comment]
One more comments. I also tried 'raw' preprocess, the tflite can be generated successfully.

**Comment by rybakov** [comment]
Here is a [test](https://github.com/google-research/google-research/blob/master/kws_streaming/models/utils_test.py#L136) validating that conversion works with any frontend: is shows that [model with external state](https://github.com/google-research/google-research/blob/master/kws_streaming/models/utils_test.py#L177) can be converted. Frontend type should not matter.

Streaming with internal state is still in dev mode in tflite, but streaming with external state works ok. If you are interested in converting your model to streaming tflite with internal state, then you should use this [example](https://github.com/google-research/google-research/blob/master/kws_streaming/models/ds_tc_resnet_eager_test.py#L29). This feature was added recently, it works only in **eager mode**. You can use above example for conversion to streaming tflite with internal state, but it has to be executed separately from kws_streaming (kws_streaming runs in session mode for backward compatibility with tf v1 and streaming with external state). Streaming with internal state also has some issues with quantization and we are working on it. Please confirm that you use tf-nightly, so that all latest features are supported.

[ds_cnn_stream.zip](https://github.com/google-research/google-research/files/7223822/ds_cnn_stream.zip) is not enought to reproduce your issues, I also need to see how you convert the model in "run_convert.py".

**Comment by wenjingyang** [comment]
@rybakov . Thanks for your help. The run_convert.py is below. 


import tensorflow as tf
from kws_streaming.layers import stream
custom_objects={"Stream":stream.Stream}
#model = tf.keras.models.load_model('models1/ds_cnn_stream1/stream_state_internal.h5', custom_objects=custom_objects)
#converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter = tf.lite.TFLiteConverter.from_saved_model( 'models1/ds_cnn_stream1/stream_state_internal')
#converter.inference_type = inference_type
#converter.experimental_new_quantizer = experimental_new_quantizer
converter.experimental_enable_resource_variables = True
converter.target_spec.supported_ops = [
      tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
  ]
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tfmodel = converter.convert()
open ("model.tflite" , "wb") .write(tfmodel)

**Comment by wenjingyang** [comment]
Hi,  @rybakov 
Thanks again. The problem is solved with tf-night(2.7.0.dev20210824). The version tensorflow2.3 had this issue.
