### ISSUE TITLE
Does hitnet require a lot of GPU memory?

### ISSUE THREAD

**Issue by jahad9819jjj** [google-research/google-research#849]
I try to use [HITNET](https://github.com/google-research/google-research/tree/master/hitnet).

GPU : Nvidia GeForce RTX 2060 SUPER
Memory Size : 7981MiB

```
root@2c4b59e82551:/workspace/hitnet# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

I attempted stereo matching for MiddleBury as follows:
```
bash predict_middlebury.sh
```
Then It will omit an error like the following:
```:bash
(ellipsis)

2021-10-19 05:19:40.789846: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 2 Chunks of size 482344960 totalling 920.00MiB
2021-10-19 05:19:40.789866: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 2 Chunks of size 1543503872 totalling 2.88GiB
2021-10-19 05:19:40.789886: I tensorflow/core/common_runtime/bfc_allocator.cc:921] Sum Total of in-use chunks: 4.37GiB
2021-10-19 05:19:40.789905: I tensorflow/core/common_runtime/bfc_allocator.cc:923] total_region_allocated_bytes_: 6694947840 memory_limit_: 6694948044 available bytes: 204 curr_region_allocation_bytes_: 8589934592
2021-10-19 05:19:40.789937: I tensorflow/core/common_runtime/bfc_allocator.cc:929] Stats:
Limit:                  6694948044
InUse:                  4697149440
MaxInUse:               5784235008
NumAllocs:                    1400
MaxAllocSize:           1946157056

2021-10-19 05:19:40.790006: W tensorflow/core/common_runtime/bfc_allocator.cc:424] *************************_*****************__*****_________************************____________*****
2021-10-19 05:19:40.790060: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_grad_input_ops.cc:1063 : Resource exhausted: OOM when allocating tensor with shape[2,32,2048,2944] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[2,32,2048,2944] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node graph/fe_shared/conv_upsample_0/conv2d_transpose}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[graph/reference_output_disparity/_155]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[2,32,2048,2944] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node graph/fe_shared/conv_upsample_0/conv2d_transpose}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict_test.py", line 301, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "predict_test.py", line 255, in main
    reference_disparity = sess.run(reference, feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[2,32,2048,2944] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node graph/fe_shared/conv_upsample_0/conv2d_transpose (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[graph/reference_output_disparity/_155]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[2,32,2048,2944] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node graph/fe_shared/conv_upsample_0/conv2d_transpose (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'graph/fe_shared/conv_upsample_0/conv2d_transpose':
  File "predict_test.py", line 301, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "predict_test.py", line 238, in main
    tf.import_graph_def(graph_def, name='graph')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3561, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

So I changed the code as follows and tried again, but I still get the same error.

```:bash
# on predict_middlebury.sh
- MODEL_NAME="middlebury_d400.pb"
+ MODEL_NAME="middlebury_d160.pb"
```
and 
```:python
# on predict.py
config = tf.ConfigProto(
          gpu_options=tf.GPUOptions(
              per_process_gpu_memory_fraction=0.8,
              allow_growth=True
              )
          )
```

I think it is generally known that the `Resource exhausted` problem can be solved by lowering the batch size, but I assume that Hitnet does not have a batch size. Is this assumption correct?

I think the reason Hitnet can't run is because it's not avoiding `Resource exhausted`, does anyone know how to work around this problem?

**Comment by jahad9819jjj** [comment]
Okay, so I tried to check resolution below : 
```
In [1]: import cv2

In [2]: img_l = cv2.imread('/home/ubuntu/Flowers-perfect/im0.png')

In [3]: img_l.shape[0]
Out[3]: 1980

In [4]: img_l.shape[1]
Out[4]: 2880
```
and I have created the following shell script that crops and then inputs image-pair into HITNET like this.
```
MODEL_PATH="/tmp/hitnet/models"

# max_disparity = 400
MODEL_NAME="middlebury_d400.pb"

DATA_PATTERN="/workspace/hitnet/Flowers-perfect/"

LEFT_PATTERN="/workspace/hitnet/Flowers-perfect/im0.png"
RIGHT_PATTERN="/workspace/hitnet/Flowers-perfect/im1.png"
GT_LEFT_PATTERN="/workspace/hitnet/Flowers-perfect/disp0.pfm"

#!/bin/bash
set -e
set -x


pip3 install -r requirements.txt

mkdir -p $MODEL_PATH
wget -P $MODEL_PATH -N https://storage.googleapis.com/tensorflow-graphics/models/hitnet/default_models/$MODEL_NAME

python3 predict_test.py \
  --data_pattern=$DATA_PATTERN \
  --model_path=$MODEL_PATH/$MODEL_NAME \
  --png_disparity_factor=128 \
  --iml_pattern=$LEFT_PATTERN \
  --imr_pattern=$RIGHT_PATTERN \
  --gtl_pattern=$GT_LEFT_PATTERN \
  --input_channels=3 \
  --predict_right=false \
  --save_png=true \
  --save_pfm=true \
  --evaluate=false \
  --max_test_number=10000 \
  --crop_left 990 \
  --crop_bottom 1440
```

But I got same errors...

**Comment by FUJI-W** [comment]
I tried HITNET with GPU: Nvidia GeForce RTX 3060, Memory Size : 6GB. 
And I get the same error. Have you solved it now?

**Comment by jahad9819jjj** [comment]
@FUJI-W It is not an essential solution, but it could be deduced by downsampling the input image.
The resolution criteria at that time were not clear, and 1080/720 could be inferred, but not 720/480, so experimental downsampling was necessary.

**Comment by FUJI-W** [comment]
Thanks a lot! It works!
