### ISSUE TITLE
Notebook Error When Using Color Upsampler

### ISSUE THREAD

**Issue by salqaryan** [google-research/google-research#902]
Hi,

My input is a single .png format image, whenever I finish running stage1, stage2 (color upsampler) produces this error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/google-research/coltran/custom_colorize.py", line 244, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/google-research/coltran/custom_colorize.py", line 223, in main
    out = model.sample(bit_cond=prev_gen, gray_cond=gray_64)
  File "/content/google-research/coltran/models/upsampler.py", line 115, in sample
    logits = self.upsampler(bit_cond, gray_cond, training=False)
  File "/content/google-research/coltran/models/upsampler.py", line 101, in upsampler
    channel = tf.concat((channel, gray_embed), axis=-1)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [5,64,64,512] vs. shape[1] = [1,64,64,512] [Op:ConcatV2] name: concat

What could be causing this?
Thank you

**Comment by MechCoder** [comment]
Does this comment fix your issue? (https://github.com/google-research/google-research/issues/838#issuecomment-930699980)

You can set the `--batch_size` flag to 1.

**Comment by MechCoder** [comment]
@salqaryan Did this fix your issue?
