### ISSUE TITLE
[widget-caption][screen2words] Could you please provide the requirements for running?

### ISSUE THREAD

**Issue by wuchiuwong** [google-research/google-research#922]
Hi, I am a beginner in UI understanding and found your amazing work, but I have some trouble reproducing your work.
I tried to run your code on the recent environment (`python 3, tensorflow==2.7.0, apache_beam==2.34.0`), but I got an error:
```
Traceback (most recent call last):
  File "E:/github/google-research/widget_caption/create_tf_example_main.py", line 364, in <module>
    app.run(main)
  File "D:\Anaconda3\envs\tf25\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "D:\Anaconda3\envs\tf25\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "E:/github/google-research/widget_caption/create_tf_example_main.py", line 360, in main
    runners.DataflowRunner().run_pipeline(pipeline)
TypeError: run_pipeline() missing 1 required positional argument: 'options'
```

It seems that `run_pipeline` in the recent `apache_beam` (`2.34.0`) takes two input parameters: `pipeline` and `options`. 
I checked the `apache_beam` API documentation and found that until version 2.9.0, `run_pipeline` only needs the parameter `pipeline`, but version 2.9.0 and previous versions only support python 2.7 but not python 3, which makes me confused. 
Could you please provide the requirements for running?

**Comment by khushboo-anand0909** [comment]
@wuchiuwong Has your error resolved? If yes, could you please let me know the fix. Thanks.
