### ISSUE TITLE
Why can't I download the package?

### ISSUE THREAD

**Issue by Kevin-Patyk** [google-research/google-research#952]
I am trying to download the rogue-score package for Python, but I cannot. I have tried everything. 

When I use pip, I get this error: 

`C:\Users\onef0>pip install rogue-score
ERROR: Could not find a version that satisfies the requirement rogue-score (from versions: none)
ERROR: No matching distribution found for rogue-score`

Then, when I cloning it from github, I get this error:

`C:\Users\onef0>pip install git+https://github.com/google-research/google-research/tree/master/rouge
Collecting git+https://github.com/google-research/google-research/tree/master/rouge
  Cloning https://github.com/google-research/google-research/tree/master/rouge to c:\users\onef0\appdata\local\temp\pip-req-build-ogcfgrb9
  Running command git clone -q https://github.com/google-research/google-research/tree/master/rouge 'C:\Users\onef0\AppData\Local\Temp\pip-req-build-ogcfgrb9'
  fatal: repository 'https://github.com/google-research/google-research/tree/master/rouge/' not found
WARNING: Discarding git+https://github.com/google-research/google-research/tree/master/rouge. Command errored out with exit status 128: git clone -q https://github.com/google-research/google-research/tree/master/rouge 'C:\Users\onef0\AppData\Local\Temp\pip-req-build-ogcfgrb9' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/google-research/google-research/tree/master/rouge 'C:\Users\onef0\AppData\Local\Temp\pip-req-build-ogcfgrb9' Check the logs for full command output.`

Finally, I have tried downloading the package files and then installing them manually and this also has not worked:

`C:\Users\onef0>cd C:\Users\onef0\Desktop\rouge_score-0.0.4`

`C:\Users\onef0\Desktop\rouge_score-0.0.4>python setup.py install
Traceback (most recent call last):
  File "C:\Users\onef0\Desktop\rouge_score-0.0.4\setup.py", line 1, in <module>
    import setuptools
  File "C:\Users\onef0\anaconda3\lib\site-packages\setuptools\__init__.py", line 16, in <module>
    import setuptools.version
  File "C:\Users\onef0\anaconda3\lib\site-packages\setuptools\version.py", line 1, in <module>
    import pkg_resources
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 78, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 10, in <module>
    from pkg_resources.extern.pyparsing import (  # noqa
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
    __import__(extant)
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "C:\Users\onef0\anaconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "C:\Users\onef0\anaconda3\lib\traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "C:\Users\onef0\anaconda3\lib\traceback.py", line 366, in extract
    f.line
  File "C:\Users\onef0\anaconda3\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\onef0\anaconda3\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\onef0\anaconda3\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\onef0\anaconda3\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
AttributeError: module 'tokenize' has no attribute 'open'`

I need this for my thesis, as I am doing text summarization using huggingface transformers and I cannot run my script without it. Any help would be greatly appreciated. Thank you!

**Comment by Kevin-Patyk** [comment]
I found the solution (I am using windows 10) - the solution is to install it from the URL from the PyPI website:

`C:\Users\onef0>pip install https://files.pythonhosted.org/packages/1f/56/a81022436c08b9405a5247b71635394d44fe7e1dbedc4b28c740e09c2840/rouge_score-0.0.4-py2.py3-none-any.whl`
