### ISSUE TITLE
[VATT] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.

### ISSUE THREAD

**Issue by AlyssaYoung** [google-research/google-research#997]
Hi, @hassanhub. I encountered this problem and  failed to solve it after searching for several solutions to similar(just look like similar) issues.

As you mentioned in #962, I modified the `objectives.py` for conducting a multi-gpu pre-training experiment and encountered this problem. Then I tried to inplement a single-gpu version and also encountered this problem.

The error information is as:
```
2022-02-11 15:07:20.266179: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.266326: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.266722: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.268130: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.268490: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    app.run(main)
  File "anaconda3/envs/vatt/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "anaconda3/envs/vatt/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 93, in main
    return executor.run(mode=params.mode)
  File "experiments/base.py", line 439, in run
    self.train()
  File "experiments/base.py", line 280, in train
    metrics = train_step(data_iterator, num_iterations)
  File "anaconda3/envs/vatt/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "anaconda3/envs/vatt/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) INVALID_ARGUMENT:  slice index 0 of dimension 0 out of bounds.
         [[{{node strided_slice_3}}]]
         [[while/body/_1/while/IteratorGetNext]]
         [[while/body/_1/while/model/tx_mlp_fac/backbone_stack/audio_module/wat_base/RandomShuffle/_72]]
  (1) INVALID_ARGUMENT:  slice index 0 of dimension 0 out of bounds.
         [[{{node strided_slice_3}}]]
         [[while/body/_1/while/IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_step_97988]

Function call stack:
train_step -> train_step

2022-02-11 15:07:20.269632: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.269706: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.271021: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.271261: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.271735: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.274001: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.274614: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.275279: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.275625: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
2022-02-11 15:07:20.276116: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds

I mainly modified the `base.py` and `objectives.py`. Since I'm not familiar with Tensorflow framework, the code base_and_objectives.tar.gz may exists a lot of  ridiculous problems. Do you have some idea about this problem?

Thanks.

**Comment by AlyssaYoung** [comment]
The modified `base.py` and  `objectives.py`  are listed in the attachment.

**Comment by AlyssaYoung** [comment]
attachment

**Comment by AlyssaYoung** [comment]
Since I failed to attach files, I copy the modified code here.

I mainly modified the `def create_train_step()` in `base.py` and `def _calculate_nce()` in `objectives.py` and code about distributed setting.
```
def create_train_step(self):
    """Constructs an op that runs a train step and returns the metrics."""

    model = self.model

    @tf.function
    def train_step(iterator, num_iterations):
      optimizer = model.optimizer
      trainable_variables = model.trainable_variables
      gradient_clip_norm = self.params.train.gradient_clip_norm
      for _ in tf.range(num_iterations - 1):
        print('num_iterations', num_iterations)
        inputs, labels = self.prepare_inputs(iterator.get_next())
        print(inputs["video"].shape, inputs["audio"].shape, inputs["text"].shape)
        outputs = model(inputs, training=True)
        print(outputs.keys())
        all_losses = model.loss_fn(labels=labels,
                                  outputs=outputs)
        losses = {}
        for k, v in all_losses.items():
          losses[k] = tf.reduce_mean(v)
          losses[k] = tf.where(tf.math.is_nan(v), 0., v)

        per_replica_loss = losses['total_loss']

        grads = tf.gradients(per_replica_loss, trainable_variables)
        grads = [tf.where(tf.math.is_nan(g), 0., g) for g in grads]
        if gradient_clip_norm > 0:
          grads, _ = tf.clip_by_global_norm(grads, gradient_clip_norm)
        optimizer.apply_gradients(zip(grads, trainable_variables))  

      inputs, labels = self.prepare_inputs(iterator.get_next())
      outputs = model(inputs, training=True)
      all_losses = model.loss_fn(labels=labels,
                                outputs=outputs)
      losses = {}
      for k, v in all_losses.items():
        losses[k] = tf.reduce_mean(v)
        losses[k] = tf.where(tf.math.is_nan(v), 0., v)

      per_replica_loss = losses['total_loss']

      grads = tf.gradients(per_replica_loss, trainable_variables)
      grads = [tf.where(tf.math.is_nan(g), 0., g) for g in grads]
      if gradient_clip_norm > 0:
        grads, _ = tf.clip_by_global_norm(grads, gradient_clip_norm)
      optimizer.apply_gradients(zip(grads, trainable_variables))  
      per_replica_metrics = losses

      return per_replica_metrics

    return train_step
```

```
  def _calculate_nce(self,
                     embed_1,
                     embed_2,
                     embed_2_mask=None):
    """Calculate NCE / MIL-NCE loss between embed_1 and embed_2."""

    embed_1_all = embed_1
    embed_2_all = embed_2
    if embed_2_mask is not None:
      embed_2_mask_all = embed_2_mask
    else:
      embed_2_mask_all = None

    # Get number of local videos and number of total videos (across replicas).
    batch_size = embed_1.shape.as_list()[0]  # B
    print('batch_size:', batch_size)
    batch_size_all = embed_1_all.shape.as_list()[0]  # B_all

    # Compute positive similarities by using local2local.
    sim_local2local = self._calculate_similarity(
        embed_1=embed_1,
        embed_2=embed_2,
        batch_size_1=batch_size,
        batch_size_2=batch_size,
        temperature=self._temperature,
        )

    # Set to 0 all non diag entries (to only keep positive candidate scores).
    id_m = tf.eye(batch_size)  # [B, B]
    print("id_m shape:", id_m.shape)
    print("sim_local2local shape:", sim_local2local.shape)
    assert id_m.shape == sim_local2local.shape[:-1]
    sim_pos = tf.reduce_sum(sim_local2local * id_m[:, :, None], axis=1)

    # Compute negative similarities by using local2all in a symmetric fashion.
    sim_sp_local2all = self._calculate_similarity(
        embed_1=embed_1,
        embed_2=embed_2_all,
        batch_size_1=batch_size,
        batch_size_2=batch_size_all,
        temperature=self._temperature,
        )

    if embed_2_mask is not None:
      mask_f_all = tf.cast(1 - embed_2_mask_all, dtype=tf.float32)
      sim_sp_local2all = sim_sp_local2all - mask_f_all[None, :, None]*LARGE_NUM

    sim_sp_all2local = self._calculate_similarity(
        embed_1=embed_1_all,
        embed_2=embed_2,
        batch_size_1=batch_size_all,
        batch_size_2=batch_size,
        temperature=self._temperature,
        )

    # Transpose into [B, B_all, L']
    sim_sp_all2local = tf.transpose(sim_sp_all2local, perm=[1, 0, 2])

    if embed_2_mask is not None:
      mask_f = tf.cast(1 - embed_2_mask, dtype=tf.float32)
      sim_sp_all2local = sim_sp_all2local - mask_f[:, None, None] * LARGE_NUM

    # We obtain the symmetric scores (x, y) and (y, x) by concatenation.
    sim_all = tf.concat([sim_sp_local2all, sim_sp_all2local], axis=1)
    sim_all = tf.reshape(sim_all, [batch_size, -1])

    # Compute the log sum exp (numerator) of the NCE loss.
    logsumexp_pos = tf.reduce_logsumexp(sim_pos, axis=1)
    # Compute the log sum exp (denominator) of the NCE loss.
    logsumexp_all = tf.reduce_logsumexp(sim_all, axis=1)
    # Compute the loss.
    loss = logsumexp_all - logsumexp_pos
    print(loss.shape)
    if embed_2_mask is not None:
      # Divide by number of examples.
      valid_examples = tf.reduce_sum(embed_2_mask)
      scaling_factor = tf.math.divide_no_nan(tf.cast(tf.size(embed_2_mask),
                                                     dtype=tf.float32),
                                             valid_examples)

      loss = loss * embed_2_mask * scaling_factor

    # If there are no valid examples, logsumexp_all could be a NaN.
    loss = tf.where(tf.math.is_nan(loss),
                    tf.zeros(loss.shape),
                    tf.identity(loss))
    # Average over batch samples.
    loss = tf.reduce_mean(loss)
    
    return loss
```

**Comment by alizaree** [comment]
Hi @AlyssaYoung , 
Have you figured out the solution by any chance? I am encountering the same problem using cpu ( for the moment) and I can't figure out why I am getting this error.
Best,

**Comment by sainivedh19pt** [comment]
Hi @hassanhub,

Thanks for the wonderful work. 

I'm trying to reproduce the pretraining step of VATT buut facing the same error as everyone above. 
` OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.`

It would be very helpful if you could guide us past the error.

Best

**Comment by JixiangGao** [comment]
Hi @AlyssaYoung, @alizaree , @sainivedh19pt and @hassanhub ,

Have you figured out the solution by any chance? 
It would be very helpful if you could guide me past the error.

Best

**Comment by HounaidaM** [comment]
Hi @JixiangGao, @AlyssaYoung, @alizaree , @sainivedh19pt and @hassanhub ,

Have you figured out the solution by any chance?
It would be very helpful if you could guide me past the error.

Best

**Comment by BetelhemNebebe** [comment]
I have a similar error "OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds." with an additional message 
"slice index 0 of dimension 0 out of bounds.
         [[{{node strided_slice_2}}]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
         [[IteratorGetNext]] [Op:__inference_inference_step_26864]"
that comes from [this line](https://github.com/google-research/google-research/blob/2b2c362f274e801ea4af19e68f0154dcbe1496da/vatt/experiments/base.py#L386). Was anyone able to fix it?

**Comment by cooper12121** [comment]
> Hi, @hassanhub. I encountered this problem and failed to solve it after searching for several solutions to similar(just look like similar) issues.
> 
> As you mentioned in #962, I modified the `objectives.py` for conducting a multi-gpu pre-training experiment and encountered this problem. Then I tried to inplement a single-gpu version and also encountered this problem.
> 
> The error information is as:
> 
> ```
> 2022-02-11 15:07:20.266179: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.266326: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.266722: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.268130: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.268490: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> Traceback (most recent call last):
>   File "main.py", line 97, in <module>
>     app.run(main)
>   File "anaconda3/envs/vatt/lib/python3.9/site-packages/absl/app.py", line 303, in run
>     _run_main(main, args)
>   File "anaconda3/envs/vatt/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "main.py", line 93, in main
>     return executor.run(mode=params.mode)
>   File "experiments/base.py", line 439, in run
>     self.train()
>   File "experiments/base.py", line 280, in train
>     metrics = train_step(data_iterator, num_iterations)
>   File "anaconda3/envs/vatt/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "anaconda3/envs/vatt/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
>     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
>   (0) INVALID_ARGUMENT:  slice index 0 of dimension 0 out of bounds.
>          [[{{node strided_slice_3}}]]
>          [[while/body/_1/while/IteratorGetNext]]
>          [[while/body/_1/while/model/tx_mlp_fac/backbone_stack/audio_module/wat_base/RandomShuffle/_72]]
>   (1) INVALID_ARGUMENT:  slice index 0 of dimension 0 out of bounds.
>          [[{{node strided_slice_3}}]]
>          [[while/body/_1/while/IteratorGetNext]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_train_step_97988]
> 
> Function call stack:
> train_step -> train_step
> 
> 2022-02-11 15:07:20.269632: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.269706: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.271021: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.271261: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.271735: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.274001: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.274614: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.275279: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.275625: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds.
> 2022-02-11 15:07:20.276116: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:108 : INVALID_ARGUMENT: slice index 0 of dimension 0 out of bounds
> 
> I mainly modified the `base.py` and `objectives.py`. Since I'm not familiar with Tensorflow framework, the code base_and_objectives.tar.gz may exists a lot of  ridiculous problems. Do you have some idea about this problem?
> 
> Thanks.
> ```

hi,@AlyssaYoung have you fix this problem ,i'm also encounter this problem.

**Comment by cooper12121** [comment]
> Have you figured out the solution by any chance?
> It would be very helpful if you could guide me past the error.

after i test ,this error must come from the dataset, the code of construct dmvr dataset ,but i don't know how to fix it

**Comment by mrqc** [comment]
Please be also aware that whenever you do some looping over an object, e.g.:

`for row in model.weights:
    ...`

Then this would also appear because you are iterating over the "weights" object. Instead do:

`for row in get_value(model.weights):
    ...`

where get_value is in keras.backend package (or slt)
